#!/usr/bin/env bash
# Lightweight checklist for operators to simulate bursty telemetry and observe backpressure.
# This script does not publish MQTT traffic itself (no credentials here); it documents commands
# and optional in-container metric scrapes. Run from a host with docker compose and a running prod stack.
set -euo pipefail

cat <<'EOF'
Telemetry burst smoke — operator checklist
============================================

Prerequisites
-------------
- Stack up: `make prod-up` (or equivalent) from deployments/prod with METRICS_ENABLED=true
  on worker + mqtt-ingest for observable counters (see .env.production.example).
- Valid MQTT credentials (same as devices) and a test topic under your MQTT_TOPIC_PREFIX.

1) Baseline metrics (from VPS host, compose project running)
------------------------------------------------------------
Worker (JetStream projection + lag); replace service name if different:

  docker compose --env-file .env.production -f docker-compose.prod.yml exec -T worker sh -c \
    'addr="${WORKER_METRICS_LISTEN:-127.0.0.1:9091}"; case "$addr" in :*) addr="127.0.0.1$addr";; esac; \
     curl -fsS "http://$addr/metrics"' \
    | grep -E 'avf_telemetry_(consumer_lag|projection_backlog|projection_failures|projection_flush_seconds|duplicate)'

mqtt-ingest (dispatch / drops are in logs; dispatch counter):

  docker compose --env-file .env.production -f docker-compose.prod.yml exec -T mqtt-ingest sh -c \
    'addr="${MQTT_INGEST_METRICS_LISTEN:-127.0.0.1:9093}"; case "$addr" in :*) addr="127.0.0.1$addr";; esac; \
     curl -fsS "http://$addr/metrics"' \
    | grep -E 'avf_mqtt_ingest_dispatch'

Optional: poll worker lag every few seconds during burst (run in a second terminal):

  while sleep 2; do
    docker compose --env-file .env.production -f docker-compose.prod.yml exec -T worker sh -c \
      'addr="${WORKER_METRICS_LISTEN:-127.0.0.1:9091}"; case "$addr" in :*) addr="127.0.0.1${addr}";; esac; \
       curl -fsS "http://${addr}/metrics"' | grep avf_telemetry_consumer_lag || true
  done

2) Generate burst (your tooling)
--------------------------------
Use a lab MQTT client (mosquitto_pub, custom script, or device simulator) authenticated like a device.
Publish valid telemetry JSON within TELEMETRY_MAX_PAYLOAD_BYTES / points / tags limits at a rate
that intentionally exceeds TELEMETRY_PER_MACHINE_MSGS_PER_SEC for a short window.

Observe:
- mqtt-ingest logs for rate limiting, drops, or publish errors
- avf_telemetry_consumer_lag and avf_telemetry_projection_backlog rising then draining
- avf_telemetry_projection_flush_seconds histogram
- Postgres: docker compose exec -T postgres psql -U "$POSTGRES_USER" -d avf_vending -c \
    "SELECT count(*) AS active FROM pg_stat_activity WHERE state = 'active';"

3) Stop conditions
------------------
Abort if JetStream disk fills, Postgres CPU is pegged with growing lag, or you see sustained handler errors
in worker logs. Roll back publish rate before tuning limits; see docs/runbooks/telemetry-production-rollout.md.

EOF

echo "telemetry_load_smoke: printed procedure (no load generated by this script)."
