import json
from pathlib import Path
root = Path(r"D:/admin/development/avf/avf-vending-system/avf-vending-api/scripts/e2e")
(root / "examples").mkdir(parents=True, exist_ok=True)
single = {"schema_version":1,"machine_id":"019e702c-11c6-7ab0-89c7-5eb32f0b12cb","hardware_profile":"TCN","payment_profile":{"mode":"cash_only"},"destructive_test_scope":{"cabinet":"A","slot_indexes":"1-10"},"catalog_defaults":{"category_slug":"tcn-e2e-beverages","brand_slug":"tcn-e2e","currency":"VND"},"cabinets":[{"code":"A","title":"Cabinet A","sort_order":1,"metadata":{}}],"layouts":[{"cabinet_code":"A","layout_key":"grid-4x6","revision":1,"layout_spec":{"rows":4,"cols":6},"status":"published"}],"slots":[]}
for i in range(1,11):
    single["slots"].append({"cabinet_code":"A","slot_code":f"A{i}","slot_index":i,"enabled":True,"sellable":True,"destructive_test":True,"product":{"sku":f"TCN-E2E-A{i}","name":f"TCN E2E Product A{i}","status":"active"},"price_minor":15000,"inventory_quantity":10,"media":{"policy":"placeholder"}})
(root/"examples"/"machine-layout-single-cabinet-a1-a10.json").write_text(json.dumps(single,indent=2)+"\n",encoding="utf-8")
two = {"schema_version":1,"machine_id":"00000000-0000-4000-8000-000000000099","hardware_profile":"TCN","payment_profile":{"mode":"cash_only"},"destructive_test_scope":{"cabinet":"A","slot_indexes":"1-2"},"catalog_defaults":{"category_slug":"e2e-two-cab","currency":"VND"},"cabinets":[{"code":"A","title":"Cabinet A","sort_order":1},{"code":"B","title":"Cabinet B","sort_order":2}],"layouts":[{"cabinet_code":"A","layout_key":"grid-2x3","revision":1,"layout_spec":{},"status":"published"},{"cabinet_code":"B","layout_key":"belt-8","revision":2,"layout_spec":{},"status":"published"}],"slots":[{"cabinet_code":"A","slot_code":"A1","slot_index":1,"enabled":True,"sellable":True,"destructive_test":True,"product":{"sku":"TWO-A1","name":"A1"},"price_minor":10000,"inventory_quantity":5,"media":{"policy":"placeholder"}},{"cabinet_code":"A","slot_code":"A2","slot_index":2,"enabled":True,"sellable":True,"destructive_test":True,"product":{"sku":"TWO-A2","name":"A2"},"price_minor":10000,"inventory_quantity":5,"media":{"policy":"placeholder"}},{"cabinet_code":"A","slot_code":"A3","slot_index":3,"enabled":False,"sellable":False,"destructive_test":False,"product":{"sku":"TWO-A3-DIS","name":"Disabled"},"price_minor":10000,"inventory_quantity":0,"media":{"policy":"placeholder"}},{"cabinet_code":"B","slot_code":"B1","slot_index":1,"enabled":True,"sellable":True,"destructive_test":False,"product":{"sku":"TWO-B1","name":"B1"},"price_minor":12000,"inventory_quantity":3,"media":{"policy":"placeholder"}},{"cabinet_code":"B","slot_code":"B2","slot_index":2,"enabled":True,"sellable":True,"destructive_test":False,"product":{"sku":"TWO-B2","name":"B2"},"price_minor":12000,"inventory_quantity":3,"media":{"policy":"placeholder"}}]}
(root/"examples"/"machine-layout-two-cabinets.json").write_text(json.dumps(two,indent=2)+"\n",encoding="utf-8")
print("ok")
