package compliance

// Canonical enterprise audit action identifiers (P1.4).
const (
	ActionAuthLoginSuccess = "auth.login.success"
	ActionAuthLoginFailed  = "auth.login.failed"
	// ActionAuthLoginFailure is the P0.8 taxonomy alias for failed interactive login attempts.
	ActionAuthLoginFailure                      = ActionAuthLoginFailed
	ActionAuthRefresh                           = "auth.refresh"
	ActionAuthLogout                            = "auth.logout"
	ActionAuthPasswordChange                    = "auth.password.change"
	ActionAuthPasswordResetRequest              = "auth.password.reset.request"
	ActionAuthPasswordResetConfirm              = "auth.password.reset.confirm"
	ActionAuthUserSessionsRevoked               = "user.sessions.revoked"
	ActionAuthUserCreated                       = "auth.user.created"
	ActionAuthUserUpdated                       = "auth.user.updated"
	ActionAuthUserDeactivated                   = "auth.user.deactivated"
	ActionAuthUserActivated                     = "auth.user.activated"
	ActionAuthPasswordReset                     = "auth.password.reset"
	ActionSecurityPermissionDenied              = "security.permission.denied"
	ActionRoleChanged                           = "role.changed"
	ActionMediaCreated                          = "media.created"
	ActionMediaUploaded                         = "media.uploaded"
	ActionMediaVariantGenerated                 = "media.variant_generated"
	ActionMediaProcessingFailed                 = "media.processing_failed"
	ActionMediaBound                            = "media.bound"
	ActionMediaBoundToProduct                   = "media.bound_to_product"
	ActionMediaUnbound                          = "media.unbound"
	ActionMediaUnboundFromProduct               = "media.unbound_from_product"
	ActionMediaDeleted                          = "media.deleted"
	ActionProductCreated                        = "product.created"
	ActionProductUpdated                        = "product.updated"
	ActionProductDeactivated                    = "product.deactivated"
	ActionBrandCreated                          = "brand.created"
	ActionBrandUpdated                          = "brand.updated"
	ActionCategoryCreated                       = "category.created"
	ActionCategoryUpdated                       = "category.updated"
	ActionTagCreated                            = "tag.created"
	ActionTagUpdated                            = "tag.updated"
	ActionPriceBookChanged                      = "pricebook.changed"
	ActionPriceBookCreated                      = "pricebook.created"
	ActionPriceBookDeactivated                  = "pricebook.deactivated"
	ActionPromotionChanged                      = "promotion.changed"
	ActionPromotionCreated                      = "promotion.created"
	ActionPromotionActivated                    = "promotion.activated"
	ActionPromotionPaused                       = "promotion.paused"
	ActionMachineCreated                        = "machine.created"
	ActionMachineUpdated                        = "machine.updated"
	ActionMachineDeactivated                    = "machine.deactivated"
	ActionMachineDisabled                       = "machine.disabled"
	ActionMachineEnabled                        = "machine.enabled"
	ActionMachineRetired                        = "machine.retired"
	ActionMachineSiteTransferred                = "machine.site.transferred"
	ActionMachineCredRotated                    = "machine.credential_rotated"
	ActionMachineCompromised                    = "machine.compromised"
	ActionMachineCredentialRevoked              = "machine.credential.revoked"
	ActionMachineSessionsRevoked                = "machine.sessions.revoked"
	ActionMachineDeviceCertRegistered           = "machine.device_cert.registered"
	ActionMachineDeviceCertRevoked              = "machine.device_cert.revoked"
	ActionMachineDeviceCertRotated              = "machine.device_cert.rotated"
	ActionSiteCreated                           = "site.created"
	ActionSiteUpdated                           = "site.updated"
	ActionSiteDeactivated                       = "site.deactivated"
	ActionSiteDisabled                          = "site.disabled"
	ActionTechnicianCreated                     = "technician.created"
	ActionTechnicianUpdated                     = "technician.updated"
	ActionTechnicianDisabled                    = "technician.disabled"
	ActionTechnicianEnabled                     = "technician.enabled"
	ActionTechnicianAssignmentCreated           = "technician_assignment.created"
	ActionTechnicianAssignmentUpdated           = "technician_assignment.updated"
	ActionTechnicianAssignmentReleased          = "technician_assignment.released"
	ActionTechnicianAssignmentCanceled          = "technician_assignment.canceled"
	ActionPriceBookActivated                    = "pricebook.activated"
	ActionPriceBookArchived                     = "pricebook.archived"
	ActionPromotionArchived                     = "promotion.archived"
	ActionOTACampaignPublished                  = "ota.campaign.published"
	ActionMachineActivationClaimed              = "machine.activation.claimed"
	ActionMachineActivationRejected             = "machine.activation.rejected"
	ActionMachineActivationCodeRevoked          = "machine.activation_code.revoked"
	ActionMachineTokenRefreshed                 = "machine.token.refreshed"
	ActionMachineAuthFailed                     = "machine.auth.failed"
	ActionMachineCredentialRotated              = "machine.credential.rotated"
	ActionMachineIdempotencyConflict            = "machine.idempotency.conflict"
	ActionMachineIdempotencyReplayed            = "machine.idempotency.replayed"
	ActionPlanogramPublished                    = "planogram.published"
	ActionInventoryAdjusted                     = "inventory.adjusted"
	ActionMachineInventoryRestock               = "machine.inventory.restock"
	ActionMachineInventoryAdjust                = "machine.inventory.adjustment"
	ActionOperatorSessionHeartbeat              = "operator.session.heartbeat"
	ActionRefundCreated                         = "refund.created"
	ActionCashCollectionClosed                  = "cash.collection.closed"
	ActionPaymentWebhookAccepted                = "payment.webhook.accepted"
	ActionPaymentWebhookRejected                = "payment.webhook.rejected"
	ActionPaymentWebhookReplayed                = "payment.webhook.replayed"
	ActionPaymentWebhookIdempotencyConflict     = "payment.webhook.idempotency_conflict"
	ActionPaymentSettlementImported             = "payment.settlement.imported"
	ActionPaymentDisputeResolved                = "payment.dispute.resolved"
	ActionCommerceReconciliationCaseCreated     = "commerce.reconciliation.case_created"
	ActionCommerceReconciliationCaseResolved    = "commerce.reconciliation.case_resolved"
	ActionCommerceReconciliationRefundRequested = "commerce.reconciliation.refund_requested"
	ActionRefundRequested                       = "refund.requested"
	ActionRefundApproved                        = "refund.approved"
	ActionRefundRejected                        = "refund.rejected"
	ActionRefundProcessed                       = "refund.processed"
	ActionOTACampaignStarted                    = "ota.campaign.started"
	ActionOTACampaignPaused                     = "ota.campaign.paused"
	ActionOTACampaignResumed                    = "ota.campaign.resumed"
	ActionOTACampaignCancelled                  = "ota.campaign.cancelled"
	ActionOTACampaignRollback                   = "ota.campaign.rollback"
	ActionFleetProvisioningBulkCreated          = "fleet.provisioning.bulk_created"
	ActionFleetRolloutCreated                   = "fleet.rollout.created"
	ActionFleetRolloutStarted                   = "fleet.rollout.started"
	ActionFleetRolloutPaused                    = "fleet.rollout.paused"
	ActionFleetRolloutResumed                   = "fleet.rollout.resumed"
	ActionFleetRolloutCancelled                 = "fleet.rollout.cancelled"
	ActionFleetRolloutRollbackDispatched        = "fleet.rollout.rollback_dispatched"
	ActionFinanceDailyCloseCreated              = "finance.daily_close.created"
	ActionMachineCommerceOrderCreated           = "machine.commerce.order_created"
	ActionMachineCommercePaymentSessionCreated  = "machine.commerce.payment_session_created"
	ActionMachineCommerceCashPaymentConfirmed   = "machine.commerce.cash_payment_confirmed"
	ActionMachineCommerceVendStarted            = "machine.commerce.vend_started"
	ActionMachineCommerceVendSuccess            = "machine.commerce.vend_success"
	ActionMachineCommerceVendFailure            = "machine.commerce.vend_failure"
	ActionMachineCommerceOrderCancelled         = "machine.commerce.order_cancelled"

	// Data retention (P2.2): admin-initiated telemetry/enterprise pruning and dry-run previews.
	ActionRetentionDryRun = "retention.dry_run"
	ActionRetentionRun    = "retention.run"

	// Platform transactional outbox (P1.3): operator replay / manual DLQ for JetStream publish pipeline.
	ActionAdminPlatformOutboxReplay  = "admin.platform.outbox.replay"
	ActionAdminPlatformOutboxMarkDLQ = "admin.platform.outbox.mark_dlq"
)

const (
	ActorUser    = "user"
	ActorMachine = "machine"
	ActorSystem  = "system"
	ActorWebhook = "webhook"
	// ActorPaymentProvider attributes automated payment provider / PSP webhook delivery (distinct from generic webhook).
	ActorPaymentProvider = "payment_provider"
	ActorService         = "service"
)

// Audit outcomes (audit_events.outcome).
const (
	OutcomeSuccess = "success"
	OutcomeFailure = "failure"
)
