// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avf/internal/v1/reporting_query.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSalesSummaryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	FromRfc3339    string                 `protobuf:"bytes,2,opt,name=from_rfc3339,json=fromRfc3339,proto3" json:"from_rfc3339,omitempty"`
	ToRfc3339      string                 `protobuf:"bytes,3,opt,name=to_rfc3339,json=toRfc3339,proto3" json:"to_rfc3339,omitempty"`
	// day | site | machine | payment_provider (matches listscope reporting).
	GroupBy       string `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesSummaryRequest) Reset() {
	*x = GetSalesSummaryRequest{}
	mi := &file_avf_internal_v1_reporting_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesSummaryRequest) ProtoMessage() {}

func (x *GetSalesSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_internal_v1_reporting_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSalesSummaryRequest) Descriptor() ([]byte, []int) {
	return file_avf_internal_v1_reporting_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetSalesSummaryRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetSalesSummaryRequest) GetFromRfc3339() string {
	if x != nil {
		return x.FromRfc3339
	}
	return ""
}

func (x *GetSalesSummaryRequest) GetToRfc3339() string {
	if x != nil {
		return x.ToRfc3339
	}
	return ""
}

func (x *GetSalesSummaryRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

type GetSalesSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SummaryJson   string                 `protobuf:"bytes,1,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesSummaryResponse) Reset() {
	*x = GetSalesSummaryResponse{}
	mi := &file_avf_internal_v1_reporting_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesSummaryResponse) ProtoMessage() {}

func (x *GetSalesSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_internal_v1_reporting_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSalesSummaryResponse) Descriptor() ([]byte, []int) {
	return file_avf_internal_v1_reporting_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetSalesSummaryResponse) GetSummaryJson() string {
	if x != nil {
		return x.SummaryJson
	}
	return ""
}

var File_avf_internal_v1_reporting_query_proto protoreflect.FileDescriptor

const file_avf_internal_v1_reporting_query_proto_rawDesc = "" +
	"\n" +
	"%avf/internal/v1/reporting_query.proto\x12\x0favf.internal.v1\"\x9e\x01\n" +
	"\x16GetSalesSummaryRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\ffrom_rfc3339\x18\x02 \x01(\tR\vfromRfc3339\x12\x1d\n" +
	"\n" +
	"to_rfc3339\x18\x03 \x01(\tR\ttoRfc3339\x12\x19\n" +
	"\bgroup_by\x18\x04 \x01(\tR\agroupBy\"<\n" +
	"\x17GetSalesSummaryResponse\x12!\n" +
	"\fsummary_json\x18\x01 \x01(\tR\vsummaryJson2\x85\x01\n" +
	"\x1dInternalReportingQueryService\x12d\n" +
	"\x0fGetSalesSummary\x12'.avf.internal.v1.GetSalesSummaryRequest\x1a(.avf.internal.v1.GetSalesSummaryResponseBFZDgithub.com/avf/avf-vending-api/internal/gen/avfinternalv1;internalv1b\x06proto3"

var (
	file_avf_internal_v1_reporting_query_proto_rawDescOnce sync.Once
	file_avf_internal_v1_reporting_query_proto_rawDescData []byte
)

func file_avf_internal_v1_reporting_query_proto_rawDescGZIP() []byte {
	file_avf_internal_v1_reporting_query_proto_rawDescOnce.Do(func() {
		file_avf_internal_v1_reporting_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_internal_v1_reporting_query_proto_rawDesc), len(file_avf_internal_v1_reporting_query_proto_rawDesc)))
	})
	return file_avf_internal_v1_reporting_query_proto_rawDescData
}

var file_avf_internal_v1_reporting_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avf_internal_v1_reporting_query_proto_goTypes = []any{
	(*GetSalesSummaryRequest)(nil),  // 0: avf.internal.v1.GetSalesSummaryRequest
	(*GetSalesSummaryResponse)(nil), // 1: avf.internal.v1.GetSalesSummaryResponse
}
var file_avf_internal_v1_reporting_query_proto_depIdxs = []int32{
	0, // 0: avf.internal.v1.InternalReportingQueryService.GetSalesSummary:input_type -> avf.internal.v1.GetSalesSummaryRequest
	1, // 1: avf.internal.v1.InternalReportingQueryService.GetSalesSummary:output_type -> avf.internal.v1.GetSalesSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avf_internal_v1_reporting_query_proto_init() }
func file_avf_internal_v1_reporting_query_proto_init() {
	if File_avf_internal_v1_reporting_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_internal_v1_reporting_query_proto_rawDesc), len(file_avf_internal_v1_reporting_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avf_internal_v1_reporting_query_proto_goTypes,
		DependencyIndexes: file_avf_internal_v1_reporting_query_proto_depIdxs,
		MessageInfos:      file_avf_internal_v1_reporting_query_proto_msgTypes,
	}.Build()
	File_avf_internal_v1_reporting_query_proto = out.File
	file_avf_internal_v1_reporting_query_proto_goTypes = nil
	file_avf_internal_v1_reporting_query_proto_depIdxs = nil
}
