#!/usr/bin/env python3
"""Postman REST suite variable / gate audit — emits POSTMAN_VARIABLE_AUDIT_REPORT.md."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import generate_full_postman_suite as gfs
from validate_generated_assets import (
    HTTP_VERBS,
    WRITE_METHODS,
    collect_all_request_items,
    openapi_operation_id_from_item,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
SWAGGER = REPO_ROOT / "docs" / "swagger" / "swagger.json"
DOC_TESTING = REPO_ROOT / "docs" / "testing"

POSTMAN_BUILTIN = frozenset(
    {
        "$guid",
        "$timestamp",
        "$randomInt",
        "$randomUUID",
        "$isoTimestamp",
        "$dummyEmail",
        "$randomPhoneNumber",
    }
)
FIXED_LITERAL_RISK = re.compile(
    r"\b(HQ-[0-9]+|REPLACE_ME|password\s*=\s*|password[\"']?\s*:\s*|eyJ[A-Za-z0-9_-]{15,})\b",
    re.I,
)
VAR_BRACE_RE = re.compile(r"\{\{([^}]+)\}\}")

OPENAPI_SEG_RE = re.compile(r"\{([^}]+)\}")


def openapi_path_placeholder_vars(swagger_path: str) -> set[str]:
    return {gfs.param_to_var(m.group(1)) for m in OPENAPI_SEG_RE.finditer(swagger_path or "")}


def openapi_operations_map(spec: dict) -> dict[str, dict]:
    out: dict[str, dict] = {}
    paths = spec.get("paths") or {}
    for pth, item in paths.items():
        for method, op in item.items():
            if method.lower() not in HTTP_VERBS or not isinstance(op, dict):
                continue
            oid = op.get("operationId")
            if isinstance(oid, str) and oid:
                out[oid] = {"path": pth, "method": method.upper(), "op": op}
    return out


def json_find_vars(obj: object, acc: set[str]) -> None:
    if isinstance(obj, str):
        for m in VAR_BRACE_RE.finditer(obj):
            acc.add(m.group(1).strip())
    elif isinstance(obj, dict):
        for k, v in obj.items():
            json_find_vars(k, acc)
            json_find_vars(v, acc)
    elif isinstance(obj, list):
        for x in obj:
            json_find_vars(x, acc)


def collect_item_postman_variables(item: dict) -> set[str]:
    from validate_generated_assets import request_url_raw

    vs: set[str] = set()
    req = item.get("request") or {}
    json_find_vars(request_url_raw(req), vs)
    u = req.get("url")
    if isinstance(u, dict):
        json_find_vars(u.get("host"), vs)
        for seg in u.get("path") or []:
            json_find_vars(seg, vs)
        for qp in u.get("query") or []:
            if isinstance(qp, dict):
                json_find_vars(qp.get("key"), vs)
                json_find_vars(qp.get("value"), vs)
        json_find_vars(u.get("variable"), vs)
    for h in req.get("header") or []:
        if isinstance(h, dict):
            json_find_vars(h.get("key"), vs)
            json_find_vars(h.get("value"), vs)
    body = req.get("body") or {}
    if isinstance(body, dict) and body.get("mode") == "raw":
        json_find_vars(body.get("raw"), vs)
    return vs


def test_script_text(item: dict) -> str:
    parts: list[str] = []
    for ev in item.get("event") or []:
        if ev.get("listen") != "test":
            continue
        ex = ((ev.get("script") or {}).get("exec")) or []
        if isinstance(ex, list):
            parts.append("\n".join(ex))
    return "\n".join(parts)


def prerequest_text(item: dict) -> str:
    parts: list[str] = []
    for ev in item.get("event") or []:
        if ev.get("listen") != "prerequest":
            continue
        ex = ((ev.get("script") or {}).get("exec")) or []
        if isinstance(ex, list):
            parts.append("\n".join(ex))
    return "\n".join(parts)


def build_report(spec: dict, coll: dict, env_keys: set[str]) -> str:
    op_map = openapi_operations_map(spec)
    coll_vars = {
        str(v.get("key"))
        for v in (coll.get("variable") or [])
        if isinstance(v, dict) and v.get("key")
    }
    allowed = env_keys | coll_vars | POSTMAN_BUILTIN | {"baseUrl"}

    lines: list[str] = [
        "# POSTMAN_VARIABLE_AUDIT_REPORT",
        "",
        "**Collection / environment files:** `%s` + `%s`."
        % (coll_path.relative_to(REPO_ROOT).as_posix(), env_path.relative_to(REPO_ROOT).as_posix()),
        "",
        "Auto-generated by `audit_postman_variables.py` (OpenAPI + generated collection + environment template).",
        "",
    ]

    template_missing: list[str] = []
    for k in (
        "allow_destructive",
        "canaryMode",
        "readiness",
        "idempotencyKey",
        "requestId",
        "correlationId",
    ):
        if k not in env_keys:
            template_missing.append(k)

    undefined_by_item: dict[str, list[str]] = {}
    gated_write_missing_throw: list[str] = []
    required_query_disabled: list[str] = []
    risky_body: list[str] = []
    auth_missing_header: list[str] = []
    dup_literal: list[str] = []

    capture_script = ""
    for ev in coll.get("event") or []:
        if ev.get("listen") == "test":
            exec_ = ((ev.get("script") or {}).get("exec")) or []
            if isinstance(exec_, list):
                capture_script = "\n".join(exec_)
    capture_ok = "gateCapture" in capture_script

    for it in collect_all_request_items(coll):
        oid = openapi_operation_id_from_item(it)
        req = it.get("request") or {}
        nm = it.get("name") or oid or "?"
        sm = (req.get("method") or "").strip().upper()

        vs = collect_item_postman_variables(it)
        item_allow = set(allowed)
        if oid and oid in op_map:
            ctx = op_map[oid]
            item_allow.update(openapi_path_placeholder_vars(ctx["path"]))
            for par in gfs.iter_resolved_parameters(spec, ctx["op"]):
                name = par.get("name") or ""
                if name and par.get("in") in ("path", "query", "header"):
                    hl = name.lower().replace("-", "_")
                    if hl in (
                        "authorization",
                        "x_request_id",
                        "x_correlation_id",
                        "accept",
                        "content_type",
                        "idempotency_key",
                        "x_idempotency_key",
                    ):
                        continue
                    item_allow.add(gfs.param_to_var(name))
        undefined = sorted(x for x in vs if x and x not in item_allow)
        if undefined:
            undefined_by_item[oid or nm] = undefined

        if not oid or oid not in op_map:
            continue

        meta = op_map[oid]
        dl, _tt = gfs.classify_destructive(meta["method"], meta["path"], meta["op"].get("tags") or [])
        pre = prerequest_text(it)

        if sm in WRITE_METHODS and dl not in ("READ_ONLY", "AUTH_PUBLIC_WRITE"):
            if "AUTH_PUBLIC_WRITE" not in pre and "[GATED]" not in pre:
                gated_write_missing_throw.append("%s — %s" % (oid, nm))

        for par in gfs.iter_resolved_parameters(spec, meta["op"]):
            if par.get("in") != "query" or not par.get("required"):
                continue
            name = par.get("name") or ""
            u = req.get("url")
            if not isinstance(u, dict):
                continue
            found = None
            for qp in u.get("query") or []:
                if isinstance(qp, dict) and qp.get("key") == name:
                    found = qp
                    break
            if found is None:
                required_query_disabled.append("%s missing query %s in url object" % (oid, name))
            elif found.get("disabled"):
                required_query_disabled.append("%s required query %s is disabled" % (oid, name))

        if dl == "DANGEROUS_PRODUCTION_DO_NOT_RUN" and sm in WRITE_METHODS:
            body = req.get("body") or {}
            raw = (body.get("raw") or "").strip() if isinstance(body, dict) else ""
            if raw and "{{$guid}}" not in raw and "canary-" not in raw.lower():
                risky_body.append("%s — %s" % (oid, nm))

        if gfs.requires_bearer(meta["op"]):
            authz = None
            for h in req.get("header") or []:
                if isinstance(h, dict) and (h.get("key") or "") == "Authorization":
                    authz = (h.get("value") or "").strip()
                    break
            if not authz or "Bearer" not in authz:
                auth_missing_header.append(oid)

        body = req.get("body") or {}
        raw = (body.get("raw") or "").strip() if isinstance(body, dict) else ""
        if raw and FIXED_LITERAL_RISK.search(raw):
            dup_literal.append("%s — %s" % (oid, nm))

    def section(title: str, rows: list[str]) -> None:
        lines.append("## %s" % title)
        lines.append("")
        if not rows:
            lines.append("- *(none)*")
        else:
            for r in rows[:400]:
                lines.append("- %s" % r)
            if len(rows) > 400:
                lines.append("- … (%s more)" % (len(rows) - 400))
        lines.append("")

    section("missing_environment_variables", ["key `%s` absent from env template" % k for k in template_missing])
    flat_undef: list[str] = []
    for k, vs in sorted(undefined_by_item.items()):
        flat_undef.append("%s → %s" % (k, ", ".join(vs)))
    section("undefined_postman_variables", flat_undef)
    section("gated_write_without_gate_env_vars", gated_write_missing_throw)
    section("required_query_param_disabled", required_query_disabled)
    section("dangerous_write_without_canary_body", risky_body)
    section(
        "after_response_missing_id_capture",
        [] if capture_ok else ["Collection test script missing `gateCapture` block (regression)."],
    )
    section("operation_doc_mismatch", ["Heuristic disabled — summaries differ from bilingual Postman descriptions."])
    section("auth_required_but_missing_bearer_header", sorted(set(auth_missing_header)))
    section("duplicate_fixed_code_likely_causing_409", dup_literal)

    lines.append("## Notes")
    lines.append("")
    lines.append(
        "- `undefined_postman_variables` excludes symbols declared as OpenAPI path/query/header parameters "
        "for that operation (via `param_to_var`). Remaining rows are literals you must wire manually."
    )
    lines.append(
        "- Manual operator inputs (real tokens, org UUIDs) are expected for many keys left empty in the template."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not SWAGGER.is_file():
        print("missing swagger", file=sys.stderr)
        return 1
    spec = json.loads(SWAGGER.read_text(encoding="utf-8"))
    coll_path = OUT / "AVF_FULL_100.postman_collection.json"
    env_path = OUT / "AVF_FULL_100.postman_environment.json"
    if not (coll_path.is_file() and env_path.is_file()):
        coll_path = OUT / "AVF_REST_365_FULL.postman_collection.json"
        env_path = OUT / "AVF_PRODUCTION.postman_environment.json"
    if not coll_path.is_file() or not env_path.is_file():
        print("run generate_full_postman_suite.py first", file=sys.stderr)
        return 1
    coll = json.loads(coll_path.read_text(encoding="utf-8"))
    env = json.loads(env_path.read_text(encoding="utf-8"))
    env_keys = {v.get("key") for v in (env.get("values") or []) if isinstance(v, dict)}
    report = build_report(spec, coll, env_keys)
    out_main = OUT / "POSTMAN_VARIABLE_AUDIT_REPORT.md"
    out_main.write_text(report, encoding="utf-8")
    DOC_TESTING.mkdir(parents=True, exist_ok=True)
    (DOC_TESTING / "POSTMAN_VARIABLE_AUDIT_REPORT.md").write_text(report, encoding="utf-8")
    print("Wrote %s" % out_main.relative_to(REPO_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
