// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: avf/machine/v1/auth.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineAuthService_ActivateMachine_FullMethodName     = "/avf.machine.v1.MachineAuthService/ActivateMachine"
	MachineAuthService_ClaimActivation_FullMethodName     = "/avf.machine.v1.MachineAuthService/ClaimActivation"
	MachineAuthService_RefreshMachineToken_FullMethodName = "/avf.machine.v1.MachineAuthService/RefreshMachineToken"
)

// MachineAuthServiceClient is the client API for MachineAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineAuthService groups public machine activation and token-refresh RPCs.
// ActivateMachine is the only unauthenticated machine app RPC. Token refresh and
// session revocation are protected by Machine JWT.
type MachineAuthServiceClient interface {
	ActivateMachine(ctx context.Context, in *ActivateMachineRequest, opts ...grpc.CallOption) (*ActivateMachineResponse, error)
	ClaimActivation(ctx context.Context, in *MachineAuthServiceClaimActivationRequest, opts ...grpc.CallOption) (*MachineAuthServiceClaimActivationResponse, error)
	RefreshMachineToken(ctx context.Context, in *MachineAuthServiceRefreshMachineTokenRequest, opts ...grpc.CallOption) (*MachineAuthServiceRefreshMachineTokenResponse, error)
}

type machineAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineAuthServiceClient(cc grpc.ClientConnInterface) MachineAuthServiceClient {
	return &machineAuthServiceClient{cc}
}

func (c *machineAuthServiceClient) ActivateMachine(ctx context.Context, in *ActivateMachineRequest, opts ...grpc.CallOption) (*ActivateMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateMachineResponse)
	err := c.cc.Invoke(ctx, MachineAuthService_ActivateMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineAuthServiceClient) ClaimActivation(ctx context.Context, in *MachineAuthServiceClaimActivationRequest, opts ...grpc.CallOption) (*MachineAuthServiceClaimActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineAuthServiceClaimActivationResponse)
	err := c.cc.Invoke(ctx, MachineAuthService_ClaimActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineAuthServiceClient) RefreshMachineToken(ctx context.Context, in *MachineAuthServiceRefreshMachineTokenRequest, opts ...grpc.CallOption) (*MachineAuthServiceRefreshMachineTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineAuthServiceRefreshMachineTokenResponse)
	err := c.cc.Invoke(ctx, MachineAuthService_RefreshMachineToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineAuthServiceServer is the server API for MachineAuthService service.
// All implementations must embed UnimplementedMachineAuthServiceServer
// for forward compatibility.
//
// MachineAuthService groups public machine activation and token-refresh RPCs.
// ActivateMachine is the only unauthenticated machine app RPC. Token refresh and
// session revocation are protected by Machine JWT.
type MachineAuthServiceServer interface {
	ActivateMachine(context.Context, *ActivateMachineRequest) (*ActivateMachineResponse, error)
	ClaimActivation(context.Context, *MachineAuthServiceClaimActivationRequest) (*MachineAuthServiceClaimActivationResponse, error)
	RefreshMachineToken(context.Context, *MachineAuthServiceRefreshMachineTokenRequest) (*MachineAuthServiceRefreshMachineTokenResponse, error)
	mustEmbedUnimplementedMachineAuthServiceServer()
}

// UnimplementedMachineAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineAuthServiceServer struct{}

func (UnimplementedMachineAuthServiceServer) ActivateMachine(context.Context, *ActivateMachineRequest) (*ActivateMachineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateMachine not implemented")
}
func (UnimplementedMachineAuthServiceServer) ClaimActivation(context.Context, *MachineAuthServiceClaimActivationRequest) (*MachineAuthServiceClaimActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimActivation not implemented")
}
func (UnimplementedMachineAuthServiceServer) RefreshMachineToken(context.Context, *MachineAuthServiceRefreshMachineTokenRequest) (*MachineAuthServiceRefreshMachineTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshMachineToken not implemented")
}
func (UnimplementedMachineAuthServiceServer) mustEmbedUnimplementedMachineAuthServiceServer() {}
func (UnimplementedMachineAuthServiceServer) testEmbeddedByValue()                            {}

// UnsafeMachineAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineAuthServiceServer will
// result in compilation errors.
type UnsafeMachineAuthServiceServer interface {
	mustEmbedUnimplementedMachineAuthServiceServer()
}

func RegisterMachineAuthServiceServer(s grpc.ServiceRegistrar, srv MachineAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineAuthService_ServiceDesc, srv)
}

func _MachineAuthService_ActivateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineAuthServiceServer).ActivateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineAuthService_ActivateMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineAuthServiceServer).ActivateMachine(ctx, req.(*ActivateMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineAuthService_ClaimActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineAuthServiceClaimActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineAuthServiceServer).ClaimActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineAuthService_ClaimActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineAuthServiceServer).ClaimActivation(ctx, req.(*MachineAuthServiceClaimActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineAuthService_RefreshMachineToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineAuthServiceRefreshMachineTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineAuthServiceServer).RefreshMachineToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineAuthService_RefreshMachineToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineAuthServiceServer).RefreshMachineToken(ctx, req.(*MachineAuthServiceRefreshMachineTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineAuthService_ServiceDesc is the grpc.ServiceDesc for MachineAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineAuthService",
	HandlerType: (*MachineAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateMachine",
			Handler:    _MachineAuthService_ActivateMachine_Handler,
		},
		{
			MethodName: "ClaimActivation",
			Handler:    _MachineAuthService_ClaimActivation_Handler,
		},
		{
			MethodName: "RefreshMachineToken",
			Handler:    _MachineAuthService_RefreshMachineToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/auth.proto",
}
