// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: avf/machine/v1/bootstrap.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineBootstrapService_GetBootstrap_FullMethodName              = "/avf.machine.v1.MachineBootstrapService/GetBootstrap"
	MachineBootstrapService_CheckIn_FullMethodName                   = "/avf.machine.v1.MachineBootstrapService/CheckIn"
	MachineBootstrapService_AckConfigVersion_FullMethodName          = "/avf.machine.v1.MachineBootstrapService/AckConfigVersion"
	MachineBootstrapService_CheckForUpdates_FullMethodName           = "/avf.machine.v1.MachineBootstrapService/CheckForUpdates"
	MachineBootstrapService_ReportLocalLayout_FullMethodName         = "/avf.machine.v1.MachineBootstrapService/ReportLocalLayout"
	MachineBootstrapService_GetMachineLayoutLibrary_FullMethodName   = "/avf.machine.v1.MachineBootstrapService/GetMachineLayoutLibrary"
	MachineBootstrapService_ReportLayoutSnapshot_FullMethodName      = "/avf.machine.v1.MachineBootstrapService/ReportLayoutSnapshot"
	MachineBootstrapService_ReportLayoutSnapshotBatch_FullMethodName = "/avf.machine.v1.MachineBootstrapService/ReportLayoutSnapshotBatch"
	MachineBootstrapService_AckLayoutActivation_FullMethodName       = "/avf.machine.v1.MachineBootstrapService/AckLayoutActivation"
)

// MachineBootstrapServiceClient is the client API for MachineBootstrapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineBootstrapService serves setup/bootstrap reads for an activated machine (requires machine access JWT).
type MachineBootstrapServiceClient interface {
	GetBootstrap(ctx context.Context, in *GetBootstrapRequest, opts ...grpc.CallOption) (*GetBootstrapResponse, error)
	CheckIn(ctx context.Context, in *MachineBootstrapServiceCheckInRequest, opts ...grpc.CallOption) (*MachineBootstrapServiceCheckInResponse, error)
	AckConfigVersion(ctx context.Context, in *AckConfigVersionRequest, opts ...grpc.CallOption) (*AckConfigVersionResponse, error)
	CheckForUpdates(ctx context.Context, in *CheckForUpdatesRequest, opts ...grpc.CallOption) (*CheckForUpdatesResponse, error)
	ReportLocalLayout(ctx context.Context, in *ReportLocalLayoutRequest, opts ...grpc.CallOption) (*ReportLocalLayoutResponse, error)
	GetMachineLayoutLibrary(ctx context.Context, in *GetMachineLayoutLibraryRequest, opts ...grpc.CallOption) (*GetMachineLayoutLibraryResponse, error)
	ReportLayoutSnapshot(ctx context.Context, in *ReportLayoutSnapshotRequest, opts ...grpc.CallOption) (*ReportLayoutSnapshotResponse, error)
	ReportLayoutSnapshotBatch(ctx context.Context, in *ReportLayoutSnapshotBatchRequest, opts ...grpc.CallOption) (*ReportLayoutSnapshotBatchResponse, error)
	AckLayoutActivation(ctx context.Context, in *AckLayoutActivationRequest, opts ...grpc.CallOption) (*AckLayoutActivationResponse, error)
}

type machineBootstrapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineBootstrapServiceClient(cc grpc.ClientConnInterface) MachineBootstrapServiceClient {
	return &machineBootstrapServiceClient{cc}
}

func (c *machineBootstrapServiceClient) GetBootstrap(ctx context.Context, in *GetBootstrapRequest, opts ...grpc.CallOption) (*GetBootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootstrapResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_GetBootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) CheckIn(ctx context.Context, in *MachineBootstrapServiceCheckInRequest, opts ...grpc.CallOption) (*MachineBootstrapServiceCheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineBootstrapServiceCheckInResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) AckConfigVersion(ctx context.Context, in *AckConfigVersionRequest, opts ...grpc.CallOption) (*AckConfigVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckConfigVersionResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_AckConfigVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) CheckForUpdates(ctx context.Context, in *CheckForUpdatesRequest, opts ...grpc.CallOption) (*CheckForUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckForUpdatesResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_CheckForUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) ReportLocalLayout(ctx context.Context, in *ReportLocalLayoutRequest, opts ...grpc.CallOption) (*ReportLocalLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLocalLayoutResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_ReportLocalLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) GetMachineLayoutLibrary(ctx context.Context, in *GetMachineLayoutLibraryRequest, opts ...grpc.CallOption) (*GetMachineLayoutLibraryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineLayoutLibraryResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_GetMachineLayoutLibrary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) ReportLayoutSnapshot(ctx context.Context, in *ReportLayoutSnapshotRequest, opts ...grpc.CallOption) (*ReportLayoutSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLayoutSnapshotResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_ReportLayoutSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) ReportLayoutSnapshotBatch(ctx context.Context, in *ReportLayoutSnapshotBatchRequest, opts ...grpc.CallOption) (*ReportLayoutSnapshotBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLayoutSnapshotBatchResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_ReportLayoutSnapshotBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineBootstrapServiceClient) AckLayoutActivation(ctx context.Context, in *AckLayoutActivationRequest, opts ...grpc.CallOption) (*AckLayoutActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckLayoutActivationResponse)
	err := c.cc.Invoke(ctx, MachineBootstrapService_AckLayoutActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineBootstrapServiceServer is the server API for MachineBootstrapService service.
// All implementations must embed UnimplementedMachineBootstrapServiceServer
// for forward compatibility.
//
// MachineBootstrapService serves setup/bootstrap reads for an activated machine (requires machine access JWT).
type MachineBootstrapServiceServer interface {
	GetBootstrap(context.Context, *GetBootstrapRequest) (*GetBootstrapResponse, error)
	CheckIn(context.Context, *MachineBootstrapServiceCheckInRequest) (*MachineBootstrapServiceCheckInResponse, error)
	AckConfigVersion(context.Context, *AckConfigVersionRequest) (*AckConfigVersionResponse, error)
	CheckForUpdates(context.Context, *CheckForUpdatesRequest) (*CheckForUpdatesResponse, error)
	ReportLocalLayout(context.Context, *ReportLocalLayoutRequest) (*ReportLocalLayoutResponse, error)
	GetMachineLayoutLibrary(context.Context, *GetMachineLayoutLibraryRequest) (*GetMachineLayoutLibraryResponse, error)
	ReportLayoutSnapshot(context.Context, *ReportLayoutSnapshotRequest) (*ReportLayoutSnapshotResponse, error)
	ReportLayoutSnapshotBatch(context.Context, *ReportLayoutSnapshotBatchRequest) (*ReportLayoutSnapshotBatchResponse, error)
	AckLayoutActivation(context.Context, *AckLayoutActivationRequest) (*AckLayoutActivationResponse, error)
	mustEmbedUnimplementedMachineBootstrapServiceServer()
}

// UnimplementedMachineBootstrapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineBootstrapServiceServer struct{}

func (UnimplementedMachineBootstrapServiceServer) GetBootstrap(context.Context, *GetBootstrapRequest) (*GetBootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBootstrap not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) CheckIn(context.Context, *MachineBootstrapServiceCheckInRequest) (*MachineBootstrapServiceCheckInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) AckConfigVersion(context.Context, *AckConfigVersionRequest) (*AckConfigVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckConfigVersion not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) CheckForUpdates(context.Context, *CheckForUpdatesRequest) (*CheckForUpdatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckForUpdates not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) ReportLocalLayout(context.Context, *ReportLocalLayoutRequest) (*ReportLocalLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLocalLayout not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) GetMachineLayoutLibrary(context.Context, *GetMachineLayoutLibraryRequest) (*GetMachineLayoutLibraryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineLayoutLibrary not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) ReportLayoutSnapshot(context.Context, *ReportLayoutSnapshotRequest) (*ReportLayoutSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLayoutSnapshot not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) ReportLayoutSnapshotBatch(context.Context, *ReportLayoutSnapshotBatchRequest) (*ReportLayoutSnapshotBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLayoutSnapshotBatch not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) AckLayoutActivation(context.Context, *AckLayoutActivationRequest) (*AckLayoutActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckLayoutActivation not implemented")
}
func (UnimplementedMachineBootstrapServiceServer) mustEmbedUnimplementedMachineBootstrapServiceServer() {
}
func (UnimplementedMachineBootstrapServiceServer) testEmbeddedByValue() {}

// UnsafeMachineBootstrapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineBootstrapServiceServer will
// result in compilation errors.
type UnsafeMachineBootstrapServiceServer interface {
	mustEmbedUnimplementedMachineBootstrapServiceServer()
}

func RegisterMachineBootstrapServiceServer(s grpc.ServiceRegistrar, srv MachineBootstrapServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineBootstrapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineBootstrapService_ServiceDesc, srv)
}

func _MachineBootstrapService_GetBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).GetBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_GetBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).GetBootstrap(ctx, req.(*GetBootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineBootstrapServiceCheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).CheckIn(ctx, req.(*MachineBootstrapServiceCheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_AckConfigVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckConfigVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).AckConfigVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_AckConfigVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).AckConfigVersion(ctx, req.(*AckConfigVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_CheckForUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckForUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).CheckForUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_CheckForUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).CheckForUpdates(ctx, req.(*CheckForUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_ReportLocalLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLocalLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).ReportLocalLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_ReportLocalLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).ReportLocalLayout(ctx, req.(*ReportLocalLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_GetMachineLayoutLibrary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineLayoutLibraryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).GetMachineLayoutLibrary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_GetMachineLayoutLibrary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).GetMachineLayoutLibrary(ctx, req.(*GetMachineLayoutLibraryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_ReportLayoutSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLayoutSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).ReportLayoutSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_ReportLayoutSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).ReportLayoutSnapshot(ctx, req.(*ReportLayoutSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_ReportLayoutSnapshotBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLayoutSnapshotBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).ReportLayoutSnapshotBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_ReportLayoutSnapshotBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).ReportLayoutSnapshotBatch(ctx, req.(*ReportLayoutSnapshotBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineBootstrapService_AckLayoutActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckLayoutActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineBootstrapServiceServer).AckLayoutActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineBootstrapService_AckLayoutActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineBootstrapServiceServer).AckLayoutActivation(ctx, req.(*AckLayoutActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineBootstrapService_ServiceDesc is the grpc.ServiceDesc for MachineBootstrapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineBootstrapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineBootstrapService",
	HandlerType: (*MachineBootstrapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBootstrap",
			Handler:    _MachineBootstrapService_GetBootstrap_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _MachineBootstrapService_CheckIn_Handler,
		},
		{
			MethodName: "AckConfigVersion",
			Handler:    _MachineBootstrapService_AckConfigVersion_Handler,
		},
		{
			MethodName: "CheckForUpdates",
			Handler:    _MachineBootstrapService_CheckForUpdates_Handler,
		},
		{
			MethodName: "ReportLocalLayout",
			Handler:    _MachineBootstrapService_ReportLocalLayout_Handler,
		},
		{
			MethodName: "GetMachineLayoutLibrary",
			Handler:    _MachineBootstrapService_GetMachineLayoutLibrary_Handler,
		},
		{
			MethodName: "ReportLayoutSnapshot",
			Handler:    _MachineBootstrapService_ReportLayoutSnapshot_Handler,
		},
		{
			MethodName: "ReportLayoutSnapshotBatch",
			Handler:    _MachineBootstrapService_ReportLayoutSnapshotBatch_Handler,
		},
		{
			MethodName: "AckLayoutActivation",
			Handler:    _MachineBootstrapService_AckLayoutActivation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/bootstrap.proto",
}
