// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: avf/machine/v1/command.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineCommandService_GetPendingCommands_FullMethodName           = "/avf.machine.v1.MachineCommandService/GetPendingCommands"
	MachineCommandService_AckCommand_FullMethodName                   = "/avf.machine.v1.MachineCommandService/AckCommand"
	MachineCommandService_RejectCommand_FullMethodName                = "/avf.machine.v1.MachineCommandService/RejectCommand"
	MachineCommandService_GetAssignedUpdate_FullMethodName            = "/avf.machine.v1.MachineCommandService/GetAssignedUpdate"
	MachineCommandService_ReportUpdateStatus_FullMethodName           = "/avf.machine.v1.MachineCommandService/ReportUpdateStatus"
	MachineCommandService_ReportDiagnosticBundleResult_FullMethodName = "/avf.machine.v1.MachineCommandService/ReportDiagnosticBundleResult"
)

// MachineCommandServiceClient is the client API for MachineCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineCommandService exposes the command ledger read/ack contract for the
// machine app. Realtime delivery remains MQTT TLS.
type MachineCommandServiceClient interface {
	// Deprecated: Do not use.
	// Deprecated: realtime backend→machine commands use MQTT TLS + ledger + ACK + expiry (see docs/api/mqtt-contract.md).
	// HTTP/gRPC polling is not the primary delivery plane.
	GetPendingCommands(ctx context.Context, in *GetPendingCommandsRequest, opts ...grpc.CallOption) (*GetPendingCommandsResponse, error)
	// Deprecated: Do not use.
	AckCommand(ctx context.Context, in *AckCommandRequest, opts ...grpc.CallOption) (*AckCommandResponse, error)
	// Deprecated: Do not use.
	RejectCommand(ctx context.Context, in *RejectCommandRequest, opts ...grpc.CallOption) (*RejectCommandResponse, error)
	GetAssignedUpdate(ctx context.Context, in *GetAssignedUpdateRequest, opts ...grpc.CallOption) (*GetAssignedUpdateResponse, error)
	ReportUpdateStatus(ctx context.Context, in *ReportUpdateStatusRequest, opts ...grpc.CallOption) (*ReportUpdateStatusResponse, error)
	ReportDiagnosticBundleResult(ctx context.Context, in *ReportDiagnosticBundleResultRequest, opts ...grpc.CallOption) (*ReportDiagnosticBundleResultResponse, error)
}

type machineCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineCommandServiceClient(cc grpc.ClientConnInterface) MachineCommandServiceClient {
	return &machineCommandServiceClient{cc}
}

// Deprecated: Do not use.
func (c *machineCommandServiceClient) GetPendingCommands(ctx context.Context, in *GetPendingCommandsRequest, opts ...grpc.CallOption) (*GetPendingCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingCommandsResponse)
	err := c.cc.Invoke(ctx, MachineCommandService_GetPendingCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *machineCommandServiceClient) AckCommand(ctx context.Context, in *AckCommandRequest, opts ...grpc.CallOption) (*AckCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckCommandResponse)
	err := c.cc.Invoke(ctx, MachineCommandService_AckCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *machineCommandServiceClient) RejectCommand(ctx context.Context, in *RejectCommandRequest, opts ...grpc.CallOption) (*RejectCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectCommandResponse)
	err := c.cc.Invoke(ctx, MachineCommandService_RejectCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommandServiceClient) GetAssignedUpdate(ctx context.Context, in *GetAssignedUpdateRequest, opts ...grpc.CallOption) (*GetAssignedUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssignedUpdateResponse)
	err := c.cc.Invoke(ctx, MachineCommandService_GetAssignedUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommandServiceClient) ReportUpdateStatus(ctx context.Context, in *ReportUpdateStatusRequest, opts ...grpc.CallOption) (*ReportUpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportUpdateStatusResponse)
	err := c.cc.Invoke(ctx, MachineCommandService_ReportUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommandServiceClient) ReportDiagnosticBundleResult(ctx context.Context, in *ReportDiagnosticBundleResultRequest, opts ...grpc.CallOption) (*ReportDiagnosticBundleResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDiagnosticBundleResultResponse)
	err := c.cc.Invoke(ctx, MachineCommandService_ReportDiagnosticBundleResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineCommandServiceServer is the server API for MachineCommandService service.
// All implementations must embed UnimplementedMachineCommandServiceServer
// for forward compatibility.
//
// MachineCommandService exposes the command ledger read/ack contract for the
// machine app. Realtime delivery remains MQTT TLS.
type MachineCommandServiceServer interface {
	// Deprecated: Do not use.
	// Deprecated: realtime backend→machine commands use MQTT TLS + ledger + ACK + expiry (see docs/api/mqtt-contract.md).
	// HTTP/gRPC polling is not the primary delivery plane.
	GetPendingCommands(context.Context, *GetPendingCommandsRequest) (*GetPendingCommandsResponse, error)
	// Deprecated: Do not use.
	AckCommand(context.Context, *AckCommandRequest) (*AckCommandResponse, error)
	// Deprecated: Do not use.
	RejectCommand(context.Context, *RejectCommandRequest) (*RejectCommandResponse, error)
	GetAssignedUpdate(context.Context, *GetAssignedUpdateRequest) (*GetAssignedUpdateResponse, error)
	ReportUpdateStatus(context.Context, *ReportUpdateStatusRequest) (*ReportUpdateStatusResponse, error)
	ReportDiagnosticBundleResult(context.Context, *ReportDiagnosticBundleResultRequest) (*ReportDiagnosticBundleResultResponse, error)
	mustEmbedUnimplementedMachineCommandServiceServer()
}

// UnimplementedMachineCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineCommandServiceServer struct{}

func (UnimplementedMachineCommandServiceServer) GetPendingCommands(context.Context, *GetPendingCommandsRequest) (*GetPendingCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingCommands not implemented")
}
func (UnimplementedMachineCommandServiceServer) AckCommand(context.Context, *AckCommandRequest) (*AckCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckCommand not implemented")
}
func (UnimplementedMachineCommandServiceServer) RejectCommand(context.Context, *RejectCommandRequest) (*RejectCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCommand not implemented")
}
func (UnimplementedMachineCommandServiceServer) GetAssignedUpdate(context.Context, *GetAssignedUpdateRequest) (*GetAssignedUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssignedUpdate not implemented")
}
func (UnimplementedMachineCommandServiceServer) ReportUpdateStatus(context.Context, *ReportUpdateStatusRequest) (*ReportUpdateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUpdateStatus not implemented")
}
func (UnimplementedMachineCommandServiceServer) ReportDiagnosticBundleResult(context.Context, *ReportDiagnosticBundleResultRequest) (*ReportDiagnosticBundleResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDiagnosticBundleResult not implemented")
}
func (UnimplementedMachineCommandServiceServer) mustEmbedUnimplementedMachineCommandServiceServer() {}
func (UnimplementedMachineCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafeMachineCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineCommandServiceServer will
// result in compilation errors.
type UnsafeMachineCommandServiceServer interface {
	mustEmbedUnimplementedMachineCommandServiceServer()
}

func RegisterMachineCommandServiceServer(s grpc.ServiceRegistrar, srv MachineCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineCommandService_ServiceDesc, srv)
}

func _MachineCommandService_GetPendingCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommandServiceServer).GetPendingCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommandService_GetPendingCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommandServiceServer).GetPendingCommands(ctx, req.(*GetPendingCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommandService_AckCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommandServiceServer).AckCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommandService_AckCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommandServiceServer).AckCommand(ctx, req.(*AckCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommandService_RejectCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommandServiceServer).RejectCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommandService_RejectCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommandServiceServer).RejectCommand(ctx, req.(*RejectCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommandService_GetAssignedUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignedUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommandServiceServer).GetAssignedUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommandService_GetAssignedUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommandServiceServer).GetAssignedUpdate(ctx, req.(*GetAssignedUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommandService_ReportUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommandServiceServer).ReportUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommandService_ReportUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommandServiceServer).ReportUpdateStatus(ctx, req.(*ReportUpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommandService_ReportDiagnosticBundleResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDiagnosticBundleResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommandServiceServer).ReportDiagnosticBundleResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommandService_ReportDiagnosticBundleResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommandServiceServer).ReportDiagnosticBundleResult(ctx, req.(*ReportDiagnosticBundleResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineCommandService_ServiceDesc is the grpc.ServiceDesc for MachineCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineCommandService",
	HandlerType: (*MachineCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingCommands",
			Handler:    _MachineCommandService_GetPendingCommands_Handler,
		},
		{
			MethodName: "AckCommand",
			Handler:    _MachineCommandService_AckCommand_Handler,
		},
		{
			MethodName: "RejectCommand",
			Handler:    _MachineCommandService_RejectCommand_Handler,
		},
		{
			MethodName: "GetAssignedUpdate",
			Handler:    _MachineCommandService_GetAssignedUpdate_Handler,
		},
		{
			MethodName: "ReportUpdateStatus",
			Handler:    _MachineCommandService_ReportUpdateStatus_Handler,
		},
		{
			MethodName: "ReportDiagnosticBundleResult",
			Handler:    _MachineCommandService_ReportDiagnosticBundleResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/command.proto",
}
