// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: avf/machine/v1/commerce.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineCommerceService_CreateOrder_FullMethodName          = "/avf.machine.v1.MachineCommerceService/CreateOrder"
	MachineCommerceService_CreatePaymentSession_FullMethodName = "/avf.machine.v1.MachineCommerceService/CreatePaymentSession"
	MachineCommerceService_AttachPaymentResult_FullMethodName  = "/avf.machine.v1.MachineCommerceService/AttachPaymentResult"
	MachineCommerceService_ConfirmCashPayment_FullMethodName   = "/avf.machine.v1.MachineCommerceService/ConfirmCashPayment"
	MachineCommerceService_CreateCashCheckout_FullMethodName   = "/avf.machine.v1.MachineCommerceService/CreateCashCheckout"
	MachineCommerceService_GetOrder_FullMethodName             = "/avf.machine.v1.MachineCommerceService/GetOrder"
	MachineCommerceService_GetOrderStatus_FullMethodName       = "/avf.machine.v1.MachineCommerceService/GetOrderStatus"
	MachineCommerceService_StartVend_FullMethodName            = "/avf.machine.v1.MachineCommerceService/StartVend"
	MachineCommerceService_ConfirmVendSuccess_FullMethodName   = "/avf.machine.v1.MachineCommerceService/ConfirmVendSuccess"
	MachineCommerceService_ReportVendSuccess_FullMethodName    = "/avf.machine.v1.MachineCommerceService/ReportVendSuccess"
	MachineCommerceService_ReportVendFailure_FullMethodName    = "/avf.machine.v1.MachineCommerceService/ReportVendFailure"
	MachineCommerceService_CancelOrder_FullMethodName          = "/avf.machine.v1.MachineCommerceService/CancelOrder"
)

// MachineCommerceServiceClient is the client API for MachineCommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineCommerceService is the kiosk sale API (Machine JWT). All order scope is the authenticated machine.
// Payment provider webhooks remain on REST; QR flows poll GetOrder / GetOrderStatus after PSP updates payment.
type MachineCommerceServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	CreatePaymentSession(ctx context.Context, in *CreatePaymentSessionRequest, opts ...grpc.CallOption) (*CreatePaymentSessionResponse, error)
	// AttachPaymentResult is an alias of CreatePaymentSession (spec-native name).
	AttachPaymentResult(ctx context.Context, in *CreatePaymentSessionRequest, opts ...grpc.CallOption) (*CreatePaymentSessionResponse, error)
	ConfirmCashPayment(ctx context.Context, in *ConfirmCashPaymentRequest, opts ...grpc.CallOption) (*ConfirmCashPaymentResponse, error)
	// CreateCashCheckout is an alias of ConfirmCashPayment (spec-native name for cash tenders).
	CreateCashCheckout(ctx context.Context, in *ConfirmCashPaymentRequest, opts ...grpc.CallOption) (*ConfirmCashPaymentResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	GetOrderStatus(ctx context.Context, in *GetOrderStatusRequest, opts ...grpc.CallOption) (*GetOrderStatusResponse, error)
	StartVend(ctx context.Context, in *StartVendRequest, opts ...grpc.CallOption) (*StartVendResponse, error)
	ConfirmVendSuccess(ctx context.Context, in *ConfirmVendSuccessRequest, opts ...grpc.CallOption) (*ConfirmVendSuccessResponse, error)
	ReportVendSuccess(ctx context.Context, in *ReportVendSuccessRequest, opts ...grpc.CallOption) (*ReportVendSuccessResponse, error)
	ReportVendFailure(ctx context.Context, in *ReportVendFailureRequest, opts ...grpc.CallOption) (*ReportVendFailureResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
}

type machineCommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineCommerceServiceClient(cc grpc.ClientConnInterface) MachineCommerceServiceClient {
	return &machineCommerceServiceClient{cc}
}

func (c *machineCommerceServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) CreatePaymentSession(ctx context.Context, in *CreatePaymentSessionRequest, opts ...grpc.CallOption) (*CreatePaymentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentSessionResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_CreatePaymentSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) AttachPaymentResult(ctx context.Context, in *CreatePaymentSessionRequest, opts ...grpc.CallOption) (*CreatePaymentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentSessionResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_AttachPaymentResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) ConfirmCashPayment(ctx context.Context, in *ConfirmCashPaymentRequest, opts ...grpc.CallOption) (*ConfirmCashPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmCashPaymentResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_ConfirmCashPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) CreateCashCheckout(ctx context.Context, in *ConfirmCashPaymentRequest, opts ...grpc.CallOption) (*ConfirmCashPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmCashPaymentResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_CreateCashCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) GetOrderStatus(ctx context.Context, in *GetOrderStatusRequest, opts ...grpc.CallOption) (*GetOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderStatusResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_GetOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) StartVend(ctx context.Context, in *StartVendRequest, opts ...grpc.CallOption) (*StartVendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVendResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_StartVend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) ConfirmVendSuccess(ctx context.Context, in *ConfirmVendSuccessRequest, opts ...grpc.CallOption) (*ConfirmVendSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmVendSuccessResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_ConfirmVendSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) ReportVendSuccess(ctx context.Context, in *ReportVendSuccessRequest, opts ...grpc.CallOption) (*ReportVendSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVendSuccessResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_ReportVendSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) ReportVendFailure(ctx context.Context, in *ReportVendFailureRequest, opts ...grpc.CallOption) (*ReportVendFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVendFailureResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_ReportVendFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineCommerceServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, MachineCommerceService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineCommerceServiceServer is the server API for MachineCommerceService service.
// All implementations must embed UnimplementedMachineCommerceServiceServer
// for forward compatibility.
//
// MachineCommerceService is the kiosk sale API (Machine JWT). All order scope is the authenticated machine.
// Payment provider webhooks remain on REST; QR flows poll GetOrder / GetOrderStatus after PSP updates payment.
type MachineCommerceServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	CreatePaymentSession(context.Context, *CreatePaymentSessionRequest) (*CreatePaymentSessionResponse, error)
	// AttachPaymentResult is an alias of CreatePaymentSession (spec-native name).
	AttachPaymentResult(context.Context, *CreatePaymentSessionRequest) (*CreatePaymentSessionResponse, error)
	ConfirmCashPayment(context.Context, *ConfirmCashPaymentRequest) (*ConfirmCashPaymentResponse, error)
	// CreateCashCheckout is an alias of ConfirmCashPayment (spec-native name for cash tenders).
	CreateCashCheckout(context.Context, *ConfirmCashPaymentRequest) (*ConfirmCashPaymentResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	GetOrderStatus(context.Context, *GetOrderStatusRequest) (*GetOrderStatusResponse, error)
	StartVend(context.Context, *StartVendRequest) (*StartVendResponse, error)
	ConfirmVendSuccess(context.Context, *ConfirmVendSuccessRequest) (*ConfirmVendSuccessResponse, error)
	ReportVendSuccess(context.Context, *ReportVendSuccessRequest) (*ReportVendSuccessResponse, error)
	ReportVendFailure(context.Context, *ReportVendFailureRequest) (*ReportVendFailureResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	mustEmbedUnimplementedMachineCommerceServiceServer()
}

// UnimplementedMachineCommerceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineCommerceServiceServer struct{}

func (UnimplementedMachineCommerceServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedMachineCommerceServiceServer) CreatePaymentSession(context.Context, *CreatePaymentSessionRequest) (*CreatePaymentSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentSession not implemented")
}
func (UnimplementedMachineCommerceServiceServer) AttachPaymentResult(context.Context, *CreatePaymentSessionRequest) (*CreatePaymentSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachPaymentResult not implemented")
}
func (UnimplementedMachineCommerceServiceServer) ConfirmCashPayment(context.Context, *ConfirmCashPaymentRequest) (*ConfirmCashPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmCashPayment not implemented")
}
func (UnimplementedMachineCommerceServiceServer) CreateCashCheckout(context.Context, *ConfirmCashPaymentRequest) (*ConfirmCashPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCashCheckout not implemented")
}
func (UnimplementedMachineCommerceServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedMachineCommerceServiceServer) GetOrderStatus(context.Context, *GetOrderStatusRequest) (*GetOrderStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderStatus not implemented")
}
func (UnimplementedMachineCommerceServiceServer) StartVend(context.Context, *StartVendRequest) (*StartVendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVend not implemented")
}
func (UnimplementedMachineCommerceServiceServer) ConfirmVendSuccess(context.Context, *ConfirmVendSuccessRequest) (*ConfirmVendSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmVendSuccess not implemented")
}
func (UnimplementedMachineCommerceServiceServer) ReportVendSuccess(context.Context, *ReportVendSuccessRequest) (*ReportVendSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportVendSuccess not implemented")
}
func (UnimplementedMachineCommerceServiceServer) ReportVendFailure(context.Context, *ReportVendFailureRequest) (*ReportVendFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportVendFailure not implemented")
}
func (UnimplementedMachineCommerceServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMachineCommerceServiceServer) mustEmbedUnimplementedMachineCommerceServiceServer() {
}
func (UnimplementedMachineCommerceServiceServer) testEmbeddedByValue() {}

// UnsafeMachineCommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineCommerceServiceServer will
// result in compilation errors.
type UnsafeMachineCommerceServiceServer interface {
	mustEmbedUnimplementedMachineCommerceServiceServer()
}

func RegisterMachineCommerceServiceServer(s grpc.ServiceRegistrar, srv MachineCommerceServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineCommerceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineCommerceService_ServiceDesc, srv)
}

func _MachineCommerceService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_CreatePaymentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).CreatePaymentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_CreatePaymentSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).CreatePaymentSession(ctx, req.(*CreatePaymentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_AttachPaymentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).AttachPaymentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_AttachPaymentResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).AttachPaymentResult(ctx, req.(*CreatePaymentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_ConfirmCashPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCashPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).ConfirmCashPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_ConfirmCashPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).ConfirmCashPayment(ctx, req.(*ConfirmCashPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_CreateCashCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCashPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).CreateCashCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_CreateCashCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).CreateCashCheckout(ctx, req.(*ConfirmCashPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_GetOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).GetOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_GetOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).GetOrderStatus(ctx, req.(*GetOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_StartVend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).StartVend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_StartVend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).StartVend(ctx, req.(*StartVendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_ConfirmVendSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmVendSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).ConfirmVendSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_ConfirmVendSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).ConfirmVendSuccess(ctx, req.(*ConfirmVendSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_ReportVendSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVendSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).ReportVendSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_ReportVendSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).ReportVendSuccess(ctx, req.(*ReportVendSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_ReportVendFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVendFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).ReportVendFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_ReportVendFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).ReportVendFailure(ctx, req.(*ReportVendFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineCommerceService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineCommerceServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineCommerceService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineCommerceServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineCommerceService_ServiceDesc is the grpc.ServiceDesc for MachineCommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineCommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineCommerceService",
	HandlerType: (*MachineCommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _MachineCommerceService_CreateOrder_Handler,
		},
		{
			MethodName: "CreatePaymentSession",
			Handler:    _MachineCommerceService_CreatePaymentSession_Handler,
		},
		{
			MethodName: "AttachPaymentResult",
			Handler:    _MachineCommerceService_AttachPaymentResult_Handler,
		},
		{
			MethodName: "ConfirmCashPayment",
			Handler:    _MachineCommerceService_ConfirmCashPayment_Handler,
		},
		{
			MethodName: "CreateCashCheckout",
			Handler:    _MachineCommerceService_CreateCashCheckout_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _MachineCommerceService_GetOrder_Handler,
		},
		{
			MethodName: "GetOrderStatus",
			Handler:    _MachineCommerceService_GetOrderStatus_Handler,
		},
		{
			MethodName: "StartVend",
			Handler:    _MachineCommerceService_StartVend_Handler,
		},
		{
			MethodName: "ConfirmVendSuccess",
			Handler:    _MachineCommerceService_ConfirmVendSuccess_Handler,
		},
		{
			MethodName: "ReportVendSuccess",
			Handler:    _MachineCommerceService_ReportVendSuccess_Handler,
		},
		{
			MethodName: "ReportVendFailure",
			Handler:    _MachineCommerceService_ReportVendFailure_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MachineCommerceService_CancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/commerce.proto",
}

const (
	MachineSaleService_CreateSale_FullMethodName          = "/avf.machine.v1.MachineSaleService/CreateSale"
	MachineSaleService_AttachPayment_FullMethodName       = "/avf.machine.v1.MachineSaleService/AttachPayment"
	MachineSaleService_ConfirmCashReceived_FullMethodName = "/avf.machine.v1.MachineSaleService/ConfirmCashReceived"
	MachineSaleService_StartVend_FullMethodName           = "/avf.machine.v1.MachineSaleService/StartVend"
	MachineSaleService_CompleteVend_FullMethodName        = "/avf.machine.v1.MachineSaleService/CompleteVend"
	MachineSaleService_FailVend_FullMethodName            = "/avf.machine.v1.MachineSaleService/FailVend"
	MachineSaleService_CancelSale_FullMethodName          = "/avf.machine.v1.MachineSaleService/CancelSale"
)

// MachineSaleServiceClient is the client API for MachineSaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineSaleService is the native vending machine runtime sale API (Machine JWT).
// Handlers delegate to the same commerce orchestration as MachineCommerceService / REST.
type MachineSaleServiceClient interface {
	CreateSale(ctx context.Context, in *CreateSaleRequest, opts ...grpc.CallOption) (*CreateSaleResponse, error)
	AttachPayment(ctx context.Context, in *AttachPaymentRequest, opts ...grpc.CallOption) (*AttachPaymentResponse, error)
	ConfirmCashReceived(ctx context.Context, in *ConfirmCashReceivedRequest, opts ...grpc.CallOption) (*ConfirmCashReceivedResponse, error)
	StartVend(ctx context.Context, in *StartVendRequest, opts ...grpc.CallOption) (*StartVendResponse, error)
	CompleteVend(ctx context.Context, in *ConfirmVendSuccessRequest, opts ...grpc.CallOption) (*ConfirmVendSuccessResponse, error)
	FailVend(ctx context.Context, in *ReportVendFailureRequest, opts ...grpc.CallOption) (*ReportVendFailureResponse, error)
	CancelSale(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
}

type machineSaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineSaleServiceClient(cc grpc.ClientConnInterface) MachineSaleServiceClient {
	return &machineSaleServiceClient{cc}
}

func (c *machineSaleServiceClient) CreateSale(ctx context.Context, in *CreateSaleRequest, opts ...grpc.CallOption) (*CreateSaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSaleResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_CreateSale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineSaleServiceClient) AttachPayment(ctx context.Context, in *AttachPaymentRequest, opts ...grpc.CallOption) (*AttachPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachPaymentResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_AttachPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineSaleServiceClient) ConfirmCashReceived(ctx context.Context, in *ConfirmCashReceivedRequest, opts ...grpc.CallOption) (*ConfirmCashReceivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmCashReceivedResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_ConfirmCashReceived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineSaleServiceClient) StartVend(ctx context.Context, in *StartVendRequest, opts ...grpc.CallOption) (*StartVendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVendResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_StartVend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineSaleServiceClient) CompleteVend(ctx context.Context, in *ConfirmVendSuccessRequest, opts ...grpc.CallOption) (*ConfirmVendSuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmVendSuccessResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_CompleteVend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineSaleServiceClient) FailVend(ctx context.Context, in *ReportVendFailureRequest, opts ...grpc.CallOption) (*ReportVendFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVendFailureResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_FailVend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineSaleServiceClient) CancelSale(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, MachineSaleService_CancelSale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineSaleServiceServer is the server API for MachineSaleService service.
// All implementations must embed UnimplementedMachineSaleServiceServer
// for forward compatibility.
//
// MachineSaleService is the native vending machine runtime sale API (Machine JWT).
// Handlers delegate to the same commerce orchestration as MachineCommerceService / REST.
type MachineSaleServiceServer interface {
	CreateSale(context.Context, *CreateSaleRequest) (*CreateSaleResponse, error)
	AttachPayment(context.Context, *AttachPaymentRequest) (*AttachPaymentResponse, error)
	ConfirmCashReceived(context.Context, *ConfirmCashReceivedRequest) (*ConfirmCashReceivedResponse, error)
	StartVend(context.Context, *StartVendRequest) (*StartVendResponse, error)
	CompleteVend(context.Context, *ConfirmVendSuccessRequest) (*ConfirmVendSuccessResponse, error)
	FailVend(context.Context, *ReportVendFailureRequest) (*ReportVendFailureResponse, error)
	CancelSale(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	mustEmbedUnimplementedMachineSaleServiceServer()
}

// UnimplementedMachineSaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineSaleServiceServer struct{}

func (UnimplementedMachineSaleServiceServer) CreateSale(context.Context, *CreateSaleRequest) (*CreateSaleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSale not implemented")
}
func (UnimplementedMachineSaleServiceServer) AttachPayment(context.Context, *AttachPaymentRequest) (*AttachPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachPayment not implemented")
}
func (UnimplementedMachineSaleServiceServer) ConfirmCashReceived(context.Context, *ConfirmCashReceivedRequest) (*ConfirmCashReceivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmCashReceived not implemented")
}
func (UnimplementedMachineSaleServiceServer) StartVend(context.Context, *StartVendRequest) (*StartVendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVend not implemented")
}
func (UnimplementedMachineSaleServiceServer) CompleteVend(context.Context, *ConfirmVendSuccessRequest) (*ConfirmVendSuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteVend not implemented")
}
func (UnimplementedMachineSaleServiceServer) FailVend(context.Context, *ReportVendFailureRequest) (*ReportVendFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailVend not implemented")
}
func (UnimplementedMachineSaleServiceServer) CancelSale(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSale not implemented")
}
func (UnimplementedMachineSaleServiceServer) mustEmbedUnimplementedMachineSaleServiceServer() {}
func (UnimplementedMachineSaleServiceServer) testEmbeddedByValue()                            {}

// UnsafeMachineSaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineSaleServiceServer will
// result in compilation errors.
type UnsafeMachineSaleServiceServer interface {
	mustEmbedUnimplementedMachineSaleServiceServer()
}

func RegisterMachineSaleServiceServer(s grpc.ServiceRegistrar, srv MachineSaleServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineSaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineSaleService_ServiceDesc, srv)
}

func _MachineSaleService_CreateSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).CreateSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_CreateSale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).CreateSale(ctx, req.(*CreateSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineSaleService_AttachPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).AttachPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_AttachPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).AttachPayment(ctx, req.(*AttachPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineSaleService_ConfirmCashReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCashReceivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).ConfirmCashReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_ConfirmCashReceived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).ConfirmCashReceived(ctx, req.(*ConfirmCashReceivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineSaleService_StartVend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).StartVend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_StartVend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).StartVend(ctx, req.(*StartVendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineSaleService_CompleteVend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmVendSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).CompleteVend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_CompleteVend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).CompleteVend(ctx, req.(*ConfirmVendSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineSaleService_FailVend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVendFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).FailVend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_FailVend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).FailVend(ctx, req.(*ReportVendFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineSaleService_CancelSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaleServiceServer).CancelSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineSaleService_CancelSale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaleServiceServer).CancelSale(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineSaleService_ServiceDesc is the grpc.ServiceDesc for MachineSaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineSaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineSaleService",
	HandlerType: (*MachineSaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSale",
			Handler:    _MachineSaleService_CreateSale_Handler,
		},
		{
			MethodName: "AttachPayment",
			Handler:    _MachineSaleService_AttachPayment_Handler,
		},
		{
			MethodName: "ConfirmCashReceived",
			Handler:    _MachineSaleService_ConfirmCashReceived_Handler,
		},
		{
			MethodName: "StartVend",
			Handler:    _MachineSaleService_StartVend_Handler,
		},
		{
			MethodName: "CompleteVend",
			Handler:    _MachineSaleService_CompleteVend_Handler,
		},
		{
			MethodName: "FailVend",
			Handler:    _MachineSaleService_FailVend_Handler,
		},
		{
			MethodName: "CancelSale",
			Handler:    _MachineSaleService_CancelSale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/commerce.proto",
}
