// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avf/machine/v1/command.proto

package machinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandSequence int64                  `protobuf:"varint,2,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	CommandType     string                 `protobuf:"bytes,3,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	MqttTopic       string                 `protobuf:"bytes,6,opt,name=mqtt_topic,json=mqttTopic,proto3" json:"mqtt_topic,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MachineCommand) Reset() {
	*x = MachineCommand{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCommand) ProtoMessage() {}

func (x *MachineCommand) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCommand.ProtoReflect.Descriptor instead.
func (*MachineCommand) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *MachineCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MachineCommand) GetCommandSequence() int64 {
	if x != nil {
		return x.CommandSequence
	}
	return 0
}

func (x *MachineCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *MachineCommand) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MachineCommand) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *MachineCommand) GetMqttTopic() string {
	if x != nil {
		return x.MqttTopic
	}
	return ""
}

type GetPendingCommandsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	AfterCommandSequence int64                  `protobuf:"varint,2,opt,name=after_command_sequence,json=afterCommandSequence,proto3" json:"after_command_sequence,omitempty"`
	Limit                int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPendingCommandsRequest) Reset() {
	*x = GetPendingCommandsRequest{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsRequest) ProtoMessage() {}

func (x *GetPendingCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *GetPendingCommandsRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetPendingCommandsRequest) GetAfterCommandSequence() int64 {
	if x != nil {
		return x.AfterCommandSequence
	}
	return 0
}

func (x *GetPendingCommandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPendingCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Commands      []*MachineCommand      `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsResponse) Reset() {
	*x = GetPendingCommandsResponse{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsResponse) ProtoMessage() {}

func (x *GetPendingCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *GetPendingCommandsResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetPendingCommandsResponse) GetCommands() []*MachineCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type AckCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CommandId       string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandSequence int64                  `protobuf:"varint,3,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	ReceiptId       string                 `protobuf:"bytes,4,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AckCommandRequest) Reset() {
	*x = AckCommandRequest{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommandRequest) ProtoMessage() {}

func (x *AckCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommandRequest.ProtoReflect.Descriptor instead.
func (*AckCommandRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *AckCommandRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AckCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AckCommandRequest) GetCommandSequence() int64 {
	if x != nil {
		return x.CommandSequence
	}
	return 0
}

func (x *AckCommandRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

type AckCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCommandResponse) Reset() {
	*x = AckCommandResponse{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommandResponse) ProtoMessage() {}

func (x *AckCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommandResponse.ProtoReflect.Descriptor instead.
func (*AckCommandResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *AckCommandResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RejectCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CommandId       string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandSequence int64                  `protobuf:"varint,3,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RejectCommandRequest) Reset() {
	*x = RejectCommandRequest{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectCommandRequest) ProtoMessage() {}

func (x *RejectCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectCommandRequest.ProtoReflect.Descriptor instead.
func (*RejectCommandRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *RejectCommandRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RejectCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RejectCommandRequest) GetCommandSequence() int64 {
	if x != nil {
		return x.CommandSequence
	}
	return 0
}

func (x *RejectCommandRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectCommandResponse) Reset() {
	*x = RejectCommandResponse{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectCommandResponse) ProtoMessage() {}

func (x *RejectCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectCommandResponse.ProtoReflect.Descriptor instead.
func (*RejectCommandResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{6}
}

func (x *RejectCommandResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AssignedUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CampaignId      string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ArtifactId      string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ArtifactVersion string                 `protobuf:"bytes,3,opt,name=artifact_version,json=artifactVersion,proto3" json:"artifact_version,omitempty"`
	CampaignType    string                 `protobuf:"bytes,4,opt,name=campaign_type,json=campaignType,proto3" json:"campaign_type,omitempty"`
	StorageKey      string                 `protobuf:"bytes,5,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	Sha256Hex       string                 `protobuf:"bytes,6,opt,name=sha256_hex,json=sha256Hex,proto3" json:"sha256_hex,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignedUpdate) Reset() {
	*x = AssignedUpdate{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedUpdate) ProtoMessage() {}

func (x *AssignedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedUpdate.ProtoReflect.Descriptor instead.
func (*AssignedUpdate) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{7}
}

func (x *AssignedUpdate) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *AssignedUpdate) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *AssignedUpdate) GetArtifactVersion() string {
	if x != nil {
		return x.ArtifactVersion
	}
	return ""
}

func (x *AssignedUpdate) GetCampaignType() string {
	if x != nil {
		return x.CampaignType
	}
	return ""
}

func (x *AssignedUpdate) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *AssignedUpdate) GetSha256Hex() string {
	if x != nil {
		return x.Sha256Hex
	}
	return ""
}

func (x *AssignedUpdate) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AssignedUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAssignedUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignedUpdateRequest) Reset() {
	*x = GetAssignedUpdateRequest{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignedUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignedUpdateRequest) ProtoMessage() {}

func (x *GetAssignedUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignedUpdateRequest.ProtoReflect.Descriptor instead.
func (*GetAssignedUpdateRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{8}
}

func (x *GetAssignedUpdateRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetAssignedUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Update        *AssignedUpdate        `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignedUpdateResponse) Reset() {
	*x = GetAssignedUpdateResponse{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignedUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignedUpdateResponse) ProtoMessage() {}

func (x *GetAssignedUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignedUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetAssignedUpdateResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{9}
}

func (x *GetAssignedUpdateResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAssignedUpdateResponse) GetUpdate() *AssignedUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type ReportUpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUpdateStatusRequest) Reset() {
	*x = ReportUpdateStatusRequest{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUpdateStatusRequest) ProtoMessage() {}

func (x *ReportUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{10}
}

func (x *ReportUpdateStatusRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReportUpdateStatusRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ReportUpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportUpdateStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportUpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUpdateStatusResponse) Reset() {
	*x = ReportUpdateStatusResponse{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUpdateStatusResponse) ProtoMessage() {}

func (x *ReportUpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportUpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{11}
}

func (x *ReportUpdateStatusResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ReportDiagnosticBundleResultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StorageKey      string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	StorageProvider string                 `protobuf:"bytes,4,opt,name=storage_provider,json=storageProvider,proto3" json:"storage_provider,omitempty"`
	ContentType     string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256Hex       string                 `protobuf:"bytes,7,opt,name=sha256_hex,json=sha256Hex,proto3" json:"sha256_hex,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportDiagnosticBundleResultRequest) Reset() {
	*x = ReportDiagnosticBundleResultRequest{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDiagnosticBundleResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDiagnosticBundleResultRequest) ProtoMessage() {}

func (x *ReportDiagnosticBundleResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDiagnosticBundleResultRequest.ProtoReflect.Descriptor instead.
func (*ReportDiagnosticBundleResultRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{12}
}

func (x *ReportDiagnosticBundleResultRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReportDiagnosticBundleResultRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReportDiagnosticBundleResultRequest) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *ReportDiagnosticBundleResultRequest) GetStorageProvider() string {
	if x != nil {
		return x.StorageProvider
	}
	return ""
}

func (x *ReportDiagnosticBundleResultRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ReportDiagnosticBundleResultRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ReportDiagnosticBundleResultRequest) GetSha256Hex() string {
	if x != nil {
		return x.Sha256Hex
	}
	return ""
}

func (x *ReportDiagnosticBundleResultRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReportDiagnosticBundleResultRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ReportDiagnosticBundleResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDiagnosticBundleResultResponse) Reset() {
	*x = ReportDiagnosticBundleResultResponse{}
	mi := &file_avf_machine_v1_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDiagnosticBundleResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDiagnosticBundleResultResponse) ProtoMessage() {}

func (x *ReportDiagnosticBundleResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDiagnosticBundleResultResponse.ProtoReflect.Descriptor instead.
func (*ReportDiagnosticBundleResultResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_command_proto_rawDescGZIP(), []int{13}
}

func (x *ReportDiagnosticBundleResultResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReportDiagnosticBundleResultResponse) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

var File_avf_machine_v1_command_proto protoreflect.FileDescriptor

const file_avf_machine_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x1cavf/machine/v1/command.proto\x12\x0eavf.machine.v1\x1a\x1bavf/machine/v1/common.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\x0eMachineCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12)\n" +
	"\x10command_sequence\x18\x02 \x01(\x03R\x0fcommandSequence\x12!\n" +
	"\fcommand_type\x18\x03 \x01(\tR\vcommandType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12\x1d\n" +
	"\n" +
	"mqtt_topic\x18\x06 \x01(\tR\tmqttTopic\"\x9f\x01\n" +
	"\x19GetPendingCommandsRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x124\n" +
	"\x16after_command_sequence\x18\x02 \x01(\x03R\x14afterCommandSequence\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\x1aGetPendingCommandsResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\x12:\n" +
	"\bcommands\x18\x02 \x03(\v2\x1e.avf.machine.v1.MachineCommandR\bcommands\"\xb4\x01\n" +
	"\x11AckCommandRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12)\n" +
	"\x10command_sequence\x18\x03 \x01(\x03R\x0fcommandSequence\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x04 \x01(\tR\treceiptId\"M\n" +
	"\x12AckCommandResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\"\xb0\x01\n" +
	"\x14RejectCommandRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12)\n" +
	"\x10command_sequence\x18\x03 \x01(\x03R\x0fcommandSequence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"P\n" +
	"\x15RejectCommandResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\"\x99\x02\n" +
	"\x0eAssignedUpdate\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12)\n" +
	"\x10artifact_version\x18\x03 \x01(\tR\x0fartifactVersion\x12#\n" +
	"\rcampaign_type\x18\x04 \x01(\tR\fcampaignType\x12\x1f\n" +
	"\vstorage_key\x18\x05 \x01(\tR\n" +
	"storageKey\x12\x1d\n" +
	"\n" +
	"sha256_hex\x18\x06 \x01(\tR\tsha256Hex\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"R\n" +
	"\x18GetAssignedUpdateRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\"\x8c\x01\n" +
	"\x19GetAssignedUpdateResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\x126\n" +
	"\x06update\x18\x02 \x01(\v2\x1e.avf.machine.v1.AssignedUpdateR\x06update\"\xb1\x01\n" +
	"\x19ReportUpdateStatusRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"U\n" +
	"\x1aReportUpdateStatusResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\"\x99\x03\n" +
	"#ReportDiagnosticBundleResultRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\x12)\n" +
	"\x10storage_provider\x18\x04 \x01(\tR\x0fstorageProvider\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"sha256_hex\x18\a \x01(\tR\tsha256Hex\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"|\n" +
	"$ReportDiagnosticBundleResultResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId2\xa9\x05\n" +
	"\x15MachineCommandService\x12p\n" +
	"\x12GetPendingCommands\x12).avf.machine.v1.GetPendingCommandsRequest\x1a*.avf.machine.v1.GetPendingCommandsResponse\"\x03\x88\x02\x01\x12X\n" +
	"\n" +
	"AckCommand\x12!.avf.machine.v1.AckCommandRequest\x1a\".avf.machine.v1.AckCommandResponse\"\x03\x88\x02\x01\x12a\n" +
	"\rRejectCommand\x12$.avf.machine.v1.RejectCommandRequest\x1a%.avf.machine.v1.RejectCommandResponse\"\x03\x88\x02\x01\x12h\n" +
	"\x11GetAssignedUpdate\x12(.avf.machine.v1.GetAssignedUpdateRequest\x1a).avf.machine.v1.GetAssignedUpdateResponse\x12k\n" +
	"\x12ReportUpdateStatus\x12).avf.machine.v1.ReportUpdateStatusRequest\x1a*.avf.machine.v1.ReportUpdateStatusResponse\x12\x89\x01\n" +
	"\x1cReportDiagnosticBundleResult\x123.avf.machine.v1.ReportDiagnosticBundleResultRequest\x1a4.avf.machine.v1.ReportDiagnosticBundleResultResponseB?Z=github.com/avf/avf-vending-api/proto/avf/machine/v1;machinev1b\x06proto3"

var (
	file_avf_machine_v1_command_proto_rawDescOnce sync.Once
	file_avf_machine_v1_command_proto_rawDescData []byte
)

func file_avf_machine_v1_command_proto_rawDescGZIP() []byte {
	file_avf_machine_v1_command_proto_rawDescOnce.Do(func() {
		file_avf_machine_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_machine_v1_command_proto_rawDesc), len(file_avf_machine_v1_command_proto_rawDesc)))
	})
	return file_avf_machine_v1_command_proto_rawDescData
}

var file_avf_machine_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_avf_machine_v1_command_proto_goTypes = []any{
	(*MachineCommand)(nil),                       // 0: avf.machine.v1.MachineCommand
	(*GetPendingCommandsRequest)(nil),            // 1: avf.machine.v1.GetPendingCommandsRequest
	(*GetPendingCommandsResponse)(nil),           // 2: avf.machine.v1.GetPendingCommandsResponse
	(*AckCommandRequest)(nil),                    // 3: avf.machine.v1.AckCommandRequest
	(*AckCommandResponse)(nil),                   // 4: avf.machine.v1.AckCommandResponse
	(*RejectCommandRequest)(nil),                 // 5: avf.machine.v1.RejectCommandRequest
	(*RejectCommandResponse)(nil),                // 6: avf.machine.v1.RejectCommandResponse
	(*AssignedUpdate)(nil),                       // 7: avf.machine.v1.AssignedUpdate
	(*GetAssignedUpdateRequest)(nil),             // 8: avf.machine.v1.GetAssignedUpdateRequest
	(*GetAssignedUpdateResponse)(nil),            // 9: avf.machine.v1.GetAssignedUpdateResponse
	(*ReportUpdateStatusRequest)(nil),            // 10: avf.machine.v1.ReportUpdateStatusRequest
	(*ReportUpdateStatusResponse)(nil),           // 11: avf.machine.v1.ReportUpdateStatusResponse
	(*ReportDiagnosticBundleResultRequest)(nil),  // 12: avf.machine.v1.ReportDiagnosticBundleResultRequest
	(*ReportDiagnosticBundleResultResponse)(nil), // 13: avf.machine.v1.ReportDiagnosticBundleResultResponse
	(*structpb.Struct)(nil),                      // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                // 15: google.protobuf.Timestamp
	(*MachineRequestMeta)(nil),                   // 16: avf.machine.v1.MachineRequestMeta
	(*MachineResponseMeta)(nil),                  // 17: avf.machine.v1.MachineResponseMeta
}
var file_avf_machine_v1_command_proto_depIdxs = []int32{
	14, // 0: avf.machine.v1.MachineCommand.payload:type_name -> google.protobuf.Struct
	15, // 1: avf.machine.v1.MachineCommand.issued_at:type_name -> google.protobuf.Timestamp
	16, // 2: avf.machine.v1.GetPendingCommandsRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	17, // 3: avf.machine.v1.GetPendingCommandsResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	0,  // 4: avf.machine.v1.GetPendingCommandsResponse.commands:type_name -> avf.machine.v1.MachineCommand
	16, // 5: avf.machine.v1.AckCommandRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	17, // 6: avf.machine.v1.AckCommandResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	16, // 7: avf.machine.v1.RejectCommandRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	17, // 8: avf.machine.v1.RejectCommandResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	16, // 9: avf.machine.v1.GetAssignedUpdateRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	17, // 10: avf.machine.v1.GetAssignedUpdateResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	7,  // 11: avf.machine.v1.GetAssignedUpdateResponse.update:type_name -> avf.machine.v1.AssignedUpdate
	16, // 12: avf.machine.v1.ReportUpdateStatusRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	17, // 13: avf.machine.v1.ReportUpdateStatusResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	16, // 14: avf.machine.v1.ReportDiagnosticBundleResultRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	14, // 15: avf.machine.v1.ReportDiagnosticBundleResultRequest.metadata:type_name -> google.protobuf.Struct
	15, // 16: avf.machine.v1.ReportDiagnosticBundleResultRequest.expires_at:type_name -> google.protobuf.Timestamp
	17, // 17: avf.machine.v1.ReportDiagnosticBundleResultResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	1,  // 18: avf.machine.v1.MachineCommandService.GetPendingCommands:input_type -> avf.machine.v1.GetPendingCommandsRequest
	3,  // 19: avf.machine.v1.MachineCommandService.AckCommand:input_type -> avf.machine.v1.AckCommandRequest
	5,  // 20: avf.machine.v1.MachineCommandService.RejectCommand:input_type -> avf.machine.v1.RejectCommandRequest
	8,  // 21: avf.machine.v1.MachineCommandService.GetAssignedUpdate:input_type -> avf.machine.v1.GetAssignedUpdateRequest
	10, // 22: avf.machine.v1.MachineCommandService.ReportUpdateStatus:input_type -> avf.machine.v1.ReportUpdateStatusRequest
	12, // 23: avf.machine.v1.MachineCommandService.ReportDiagnosticBundleResult:input_type -> avf.machine.v1.ReportDiagnosticBundleResultRequest
	2,  // 24: avf.machine.v1.MachineCommandService.GetPendingCommands:output_type -> avf.machine.v1.GetPendingCommandsResponse
	4,  // 25: avf.machine.v1.MachineCommandService.AckCommand:output_type -> avf.machine.v1.AckCommandResponse
	6,  // 26: avf.machine.v1.MachineCommandService.RejectCommand:output_type -> avf.machine.v1.RejectCommandResponse
	9,  // 27: avf.machine.v1.MachineCommandService.GetAssignedUpdate:output_type -> avf.machine.v1.GetAssignedUpdateResponse
	11, // 28: avf.machine.v1.MachineCommandService.ReportUpdateStatus:output_type -> avf.machine.v1.ReportUpdateStatusResponse
	13, // 29: avf.machine.v1.MachineCommandService.ReportDiagnosticBundleResult:output_type -> avf.machine.v1.ReportDiagnosticBundleResultResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_avf_machine_v1_command_proto_init() }
func file_avf_machine_v1_command_proto_init() {
	if File_avf_machine_v1_command_proto != nil {
		return
	}
	file_avf_machine_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_machine_v1_command_proto_rawDesc), len(file_avf_machine_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avf_machine_v1_command_proto_goTypes,
		DependencyIndexes: file_avf_machine_v1_command_proto_depIdxs,
		MessageInfos:      file_avf_machine_v1_command_proto_msgTypes,
	}.Build()
	File_avf_machine_v1_command_proto = out.File
	file_avf_machine_v1_command_proto_goTypes = nil
	file_avf_machine_v1_command_proto_depIdxs = nil
}
