// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avf/machine/v1/commerce.proto

package machinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *CreateOrderRequest    `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaleRequest) Reset() {
	*x = CreateSaleRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleRequest) ProtoMessage() {}

func (x *CreateSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleRequest.ProtoReflect.Descriptor instead.
func (*CreateSaleRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSaleRequest) GetOrder() *CreateOrderRequest {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateSaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *CreateOrderResponse   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaleResponse) Reset() {
	*x = CreateSaleResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleResponse) ProtoMessage() {}

func (x *CreateSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleResponse.ProtoReflect.Descriptor instead.
func (*CreateSaleResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSaleResponse) GetOrder() *CreateOrderResponse {
	if x != nil {
		return x.Order
	}
	return nil
}

type AttachPaymentRequest struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	PaymentSession *CreatePaymentSessionRequest `protobuf:"bytes,1,opt,name=payment_session,json=paymentSession,proto3" json:"payment_session,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttachPaymentRequest) Reset() {
	*x = AttachPaymentRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPaymentRequest) ProtoMessage() {}

func (x *AttachPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPaymentRequest.ProtoReflect.Descriptor instead.
func (*AttachPaymentRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{2}
}

func (x *AttachPaymentRequest) GetPaymentSession() *CreatePaymentSessionRequest {
	if x != nil {
		return x.PaymentSession
	}
	return nil
}

type AttachPaymentResponse struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	PaymentSession *CreatePaymentSessionResponse `protobuf:"bytes,1,opt,name=payment_session,json=paymentSession,proto3" json:"payment_session,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttachPaymentResponse) Reset() {
	*x = AttachPaymentResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPaymentResponse) ProtoMessage() {}

func (x *AttachPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPaymentResponse.ProtoReflect.Descriptor instead.
func (*AttachPaymentResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{3}
}

func (x *AttachPaymentResponse) GetPaymentSession() *CreatePaymentSessionResponse {
	if x != nil {
		return x.PaymentSession
	}
	return nil
}

type ConfirmCashReceivedRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Payment       *ConfirmCashPaymentRequest `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCashReceivedRequest) Reset() {
	*x = ConfirmCashReceivedRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCashReceivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCashReceivedRequest) ProtoMessage() {}

func (x *ConfirmCashReceivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCashReceivedRequest.ProtoReflect.Descriptor instead.
func (*ConfirmCashReceivedRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmCashReceivedRequest) GetPayment() *ConfirmCashPaymentRequest {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ConfirmCashReceivedResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Payment       *ConfirmCashPaymentResponse `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCashReceivedResponse) Reset() {
	*x = ConfirmCashReceivedResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCashReceivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCashReceivedResponse) ProtoMessage() {}

func (x *ConfirmCashReceivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCashReceivedResponse.ProtoReflect.Descriptor instead.
func (*ConfirmCashReceivedResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmCashReceivedResponse) GetPayment() *ConfirmCashPaymentResponse {
	if x != nil {
		return x.Payment
	}
	return nil
}

type SlotSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        *string                `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3,oneof" json:"slot_id,omitempty"`
	CabinetCode   string                 `protobuf:"bytes,2,opt,name=cabinet_code,json=cabinetCode,proto3" json:"cabinet_code,omitempty"`
	SlotCode      string                 `protobuf:"bytes,3,opt,name=slot_code,json=slotCode,proto3" json:"slot_code,omitempty"`
	SlotIndex     *int32                 `protobuf:"varint,4,opt,name=slot_index,json=slotIndex,proto3,oneof" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotSelection) Reset() {
	*x = SlotSelection{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotSelection) ProtoMessage() {}

func (x *SlotSelection) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotSelection.ProtoReflect.Descriptor instead.
func (*SlotSelection) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{6}
}

func (x *SlotSelection) GetSlotId() string {
	if x != nil && x.SlotId != nil {
		return *x.SlotId
	}
	return ""
}

func (x *SlotSelection) GetCabinetCode() string {
	if x != nil {
		return x.CabinetCode
	}
	return ""
}

func (x *SlotSelection) GetSlotCode() string {
	if x != nil {
		return x.SlotCode
	}
	return ""
}

func (x *SlotSelection) GetSlotIndex() int32 {
	if x != nil && x.SlotIndex != nil {
		return *x.SlotIndex
	}
	return 0
}

// SimulationContext tags enterprise HIL rows; excluded from real revenue when simulated=true.
type SimulationContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Simulated          bool                   `protobuf:"varint,1,opt,name=simulated,proto3" json:"simulated,omitempty"`
	SimulationRunId    string                 `protobuf:"bytes,2,opt,name=simulation_run_id,json=simulationRunId,proto3" json:"simulation_run_id,omitempty"`
	SimulationScenario string                 `protobuf:"bytes,3,opt,name=simulation_scenario,json=simulationScenario,proto3" json:"simulation_scenario,omitempty"`
	FakeBill           bool                   `protobuf:"varint,4,opt,name=fake_bill,json=fakeBill,proto3" json:"fake_bill,omitempty"`
	FakeBoard          bool                   `protobuf:"varint,5,opt,name=fake_board,json=fakeBoard,proto3" json:"fake_board,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SimulationContext) Reset() {
	*x = SimulationContext{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationContext) ProtoMessage() {}

func (x *SimulationContext) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationContext.ProtoReflect.Descriptor instead.
func (*SimulationContext) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{7}
}

func (x *SimulationContext) GetSimulated() bool {
	if x != nil {
		return x.Simulated
	}
	return false
}

func (x *SimulationContext) GetSimulationRunId() string {
	if x != nil {
		return x.SimulationRunId
	}
	return ""
}

func (x *SimulationContext) GetSimulationScenario() string {
	if x != nil {
		return x.SimulationScenario
	}
	return ""
}

func (x *SimulationContext) GetFakeBill() bool {
	if x != nil {
		return x.FakeBill
	}
	return false
}

func (x *SimulationContext) GetFakeBoard() bool {
	if x != nil {
		return x.FakeBoard
	}
	return false
}

type CreateOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Optional echo of machine_id; must equal the Machine JWT machine when set.
	MachineId     *string             `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3,oneof" json:"machine_id,omitempty"`
	ProductId     string              `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Slot          *SlotSelection      `protobuf:"bytes,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Currency      string              `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Meta          *MachineRequestMeta `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Simulation    *SimulationContext  `protobuf:"bytes,7,opt,name=simulation,proto3,oneof" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrderRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateOrderRequest) GetMachineId() string {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return ""
}

func (x *CreateOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderRequest) GetSlot() *SlotSelection {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateOrderRequest) GetSimulation() *SimulationContext {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	VendSessionId string                 `protobuf:"bytes,3,opt,name=vend_session_id,json=vendSessionId,proto3" json:"vend_session_id,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	VendState     string                 `protobuf:"bytes,5,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	SlotId        string                 `protobuf:"bytes,6,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	CabinetCode   string                 `protobuf:"bytes,7,opt,name=cabinet_code,json=cabinetCode,proto3" json:"cabinet_code,omitempty"`
	SlotCode      string                 `protobuf:"bytes,8,opt,name=slot_code,json=slotCode,proto3" json:"slot_code,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,9,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	SubtotalMinor int64                  `protobuf:"varint,10,opt,name=subtotal_minor,json=subtotalMinor,proto3" json:"subtotal_minor,omitempty"`
	TaxMinor      int64                  `protobuf:"varint,11,opt,name=tax_minor,json=taxMinor,proto3" json:"tax_minor,omitempty"`
	TotalMinor    int64                  `protobuf:"varint,12,opt,name=total_minor,json=totalMinor,proto3" json:"total_minor,omitempty"`
	PriceMinor    int64                  `protobuf:"varint,13,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,14,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetVendSessionId() string {
	if x != nil {
		return x.VendSessionId
	}
	return ""
}

func (x *CreateOrderResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *CreateOrderResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

func (x *CreateOrderResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *CreateOrderResponse) GetCabinetCode() string {
	if x != nil {
		return x.CabinetCode
	}
	return ""
}

func (x *CreateOrderResponse) GetSlotCode() string {
	if x != nil {
		return x.SlotCode
	}
	return ""
}

func (x *CreateOrderResponse) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *CreateOrderResponse) GetSubtotalMinor() int64 {
	if x != nil {
		return x.SubtotalMinor
	}
	return 0
}

func (x *CreateOrderResponse) GetTaxMinor() int64 {
	if x != nil {
		return x.TaxMinor
	}
	return 0
}

func (x *CreateOrderResponse) GetTotalMinor() int64 {
	if x != nil {
		return x.TotalMinor
	}
	return 0
}

func (x *CreateOrderResponse) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *CreateOrderResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreatePaymentSessionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Context  *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId  string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Provider string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// Defaults to "created" when empty (QR / PSP session).
	PaymentState string `protobuf:"bytes,4,opt,name=payment_state,json=paymentState,proto3" json:"payment_state,omitempty"`
	AmountMinor  int64  `protobuf:"varint,5,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency     string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	// JSON payload for outbox fan-out (e.g. PSP hints). Must be valid JSON when non-empty.
	OutboxPayloadJson string             `protobuf:"bytes,7,opt,name=outbox_payload_json,json=outboxPayloadJson,proto3" json:"outbox_payload_json,omitempty"`
	Simulation        *SimulationContext `protobuf:"bytes,8,opt,name=simulation,proto3,oneof" json:"simulation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentSessionRequest) Reset() {
	*x = CreatePaymentSessionRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionRequest) ProtoMessage() {}

func (x *CreatePaymentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePaymentSessionRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreatePaymentSessionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetPaymentState() string {
	if x != nil {
		return x.PaymentState
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *CreatePaymentSessionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetOutboxPayloadJson() string {
	if x != nil {
		return x.OutboxPayloadJson
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetSimulation() *SimulationContext {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type CreatePaymentSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentState  string                 `protobuf:"bytes,3,opt,name=payment_state,json=paymentState,proto3" json:"payment_state,omitempty"`
	OutboxEventId int64                  `protobuf:"varint,4,opt,name=outbox_event_id,json=outboxEventId,proto3" json:"outbox_event_id,omitempty"`
	// Opaque provider payload or HTTPS URL for QR presentation (never raw image bytes).
	QrPayloadOrUrl string `protobuf:"bytes,5,opt,name=qr_payload_or_url,json=qrPayloadOrUrl,proto3" json:"qr_payload_or_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentSessionResponse) Reset() {
	*x = CreatePaymentSessionResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionResponse) ProtoMessage() {}

func (x *CreatePaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePaymentSessionResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *CreatePaymentSessionResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetPaymentState() string {
	if x != nil {
		return x.PaymentState
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetOutboxEventId() int64 {
	if x != nil {
		return x.OutboxEventId
	}
	return 0
}

func (x *CreatePaymentSessionResponse) GetQrPayloadOrUrl() string {
	if x != nil {
		return x.QrPayloadOrUrl
	}
	return ""
}

type ConfirmCashPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Simulation    *SimulationContext     `protobuf:"bytes,3,opt,name=simulation,proto3,oneof" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCashPaymentRequest) Reset() {
	*x = ConfirmCashPaymentRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCashPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCashPaymentRequest) ProtoMessage() {}

func (x *ConfirmCashPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCashPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmCashPaymentRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmCashPaymentRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConfirmCashPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmCashPaymentRequest) GetSimulation() *SimulationContext {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type ConfirmCashPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentState  string                 `protobuf:"bytes,4,opt,name=payment_state,json=paymentState,proto3" json:"payment_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmCashPaymentResponse) Reset() {
	*x = ConfirmCashPaymentResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmCashPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCashPaymentResponse) ProtoMessage() {}

func (x *ConfirmCashPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCashPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmCashPaymentResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmCashPaymentResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *ConfirmCashPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmCashPaymentResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ConfirmCashPaymentResponse) GetPaymentState() string {
	if x != nil {
		return x.PaymentState
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type GetOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus     string                 `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Currency        string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	SubtotalMinor   int64                  `protobuf:"varint,4,opt,name=subtotal_minor,json=subtotalMinor,proto3" json:"subtotal_minor,omitempty"`
	TaxMinor        int64                  `protobuf:"varint,5,opt,name=tax_minor,json=taxMinor,proto3" json:"tax_minor,omitempty"`
	TotalMinor      int64                  `protobuf:"varint,6,opt,name=total_minor,json=totalMinor,proto3" json:"total_minor,omitempty"`
	OrderCreatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=order_created_at,json=orderCreatedAt,proto3" json:"order_created_at,omitempty"`
	VendState       string                 `protobuf:"bytes,8,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	VendSlotIndex   int32                  `protobuf:"varint,9,opt,name=vend_slot_index,json=vendSlotIndex,proto3" json:"vend_slot_index,omitempty"`
	ProductId       string                 `protobuf:"bytes,10,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PaymentPresent  bool                   `protobuf:"varint,11,opt,name=payment_present,json=paymentPresent,proto3" json:"payment_present,omitempty"`
	PaymentId       string                 `protobuf:"bytes,12,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentProvider string                 `protobuf:"bytes,13,opt,name=payment_provider,json=paymentProvider,proto3" json:"payment_provider,omitempty"`
	PaymentState    string                 `protobuf:"bytes,14,opt,name=payment_state,json=paymentState,proto3" json:"payment_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *GetOrderResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetOrderResponse) GetSubtotalMinor() int64 {
	if x != nil {
		return x.SubtotalMinor
	}
	return 0
}

func (x *GetOrderResponse) GetTaxMinor() int64 {
	if x != nil {
		return x.TaxMinor
	}
	return 0
}

func (x *GetOrderResponse) GetTotalMinor() int64 {
	if x != nil {
		return x.TotalMinor
	}
	return 0
}

func (x *GetOrderResponse) GetOrderCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderCreatedAt
	}
	return nil
}

func (x *GetOrderResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

func (x *GetOrderResponse) GetVendSlotIndex() int32 {
	if x != nil {
		return x.VendSlotIndex
	}
	return 0
}

func (x *GetOrderResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetOrderResponse) GetPaymentPresent() bool {
	if x != nil {
		return x.PaymentPresent
	}
	return false
}

func (x *GetOrderResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetOrderResponse) GetPaymentProvider() string {
	if x != nil {
		return x.PaymentProvider
	}
	return ""
}

func (x *GetOrderResponse) GetPaymentState() string {
	if x != nil {
		return x.PaymentState
	}
	return ""
}

type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type GetOrderStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus    string                 `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	VendState      string                 `protobuf:"bytes,3,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	PaymentPresent bool                   `protobuf:"varint,4,opt,name=payment_present,json=paymentPresent,proto3" json:"payment_present,omitempty"`
	PaymentState   string                 `protobuf:"bytes,5,opt,name=payment_state,json=paymentState,proto3" json:"payment_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{17}
}

func (x *GetOrderStatusResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *GetOrderStatusResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

func (x *GetOrderStatusResponse) GetPaymentPresent() bool {
	if x != nil {
		return x.PaymentPresent
	}
	return false
}

func (x *GetOrderStatusResponse) GetPaymentState() string {
	if x != nil {
		return x.PaymentState
	}
	return ""
}

// HardwareCommandRef links a vend outcome to a command_ledger / machine_command_attempts row.
type HardwareCommandRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// SHA-256 hex digest of canonical TX/RX wire bytes (preferred over raw_ref for payload size).
	TxRxDigest string `protobuf:"bytes,2,opt,name=tx_rx_digest,json=txRxDigest,proto3" json:"tx_rx_digest,omitempty"`
	// Opaque reference to stored raw frame artifact when digest alone is insufficient.
	RawRef        string `protobuf:"bytes,3,opt,name=raw_ref,json=rawRef,proto3" json:"raw_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareCommandRef) Reset() {
	*x = HardwareCommandRef{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareCommandRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareCommandRef) ProtoMessage() {}

func (x *HardwareCommandRef) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareCommandRef.ProtoReflect.Descriptor instead.
func (*HardwareCommandRef) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{18}
}

func (x *HardwareCommandRef) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *HardwareCommandRef) GetTxRxDigest() string {
	if x != nil {
		return x.TxRxDigest
	}
	return ""
}

func (x *HardwareCommandRef) GetRawRef() string {
	if x != nil {
		return x.RawRef
	}
	return ""
}

// BillFinalRecord is the BILL acceptor final credit event for cash-only checkout.
type BillFinalRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,2,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	RawRef        *string                `protobuf:"bytes,4,opt,name=raw_ref,json=rawRef,proto3,oneof" json:"raw_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillFinalRecord) Reset() {
	*x = BillFinalRecord{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillFinalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillFinalRecord) ProtoMessage() {}

func (x *BillFinalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillFinalRecord.ProtoReflect.Descriptor instead.
func (*BillFinalRecord) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{19}
}

func (x *BillFinalRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BillFinalRecord) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *BillFinalRecord) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BillFinalRecord) GetRawRef() string {
	if x != nil && x.RawRef != nil {
		return *x.RawRef
	}
	return ""
}

// TcnDispenseRecord is the TCN board terminal dispense/drop outcome.
type TcnDispenseRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Dropped       bool                   `protobuf:"varint,3,opt,name=dropped,proto3" json:"dropped,omitempty"`
	Digest        *string                `protobuf:"bytes,4,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	RawRef        *string                `protobuf:"bytes,5,opt,name=raw_ref,json=rawRef,proto3,oneof" json:"raw_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcnDispenseRecord) Reset() {
	*x = TcnDispenseRecord{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcnDispenseRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcnDispenseRecord) ProtoMessage() {}

func (x *TcnDispenseRecord) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcnDispenseRecord.ProtoReflect.Descriptor instead.
func (*TcnDispenseRecord) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{20}
}

func (x *TcnDispenseRecord) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *TcnDispenseRecord) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TcnDispenseRecord) GetDropped() bool {
	if x != nil {
		return x.Dropped
	}
	return false
}

func (x *TcnDispenseRecord) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *TcnDispenseRecord) GetRawRef() string {
	if x != nil && x.RawRef != nil {
		return *x.RawRef
	}
	return ""
}

// VendHardwareEvidence correlates order, vend attempt, BILL final, TCN dispense, and command trace.
type VendHardwareEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendAttemptId string                 `protobuf:"bytes,1,opt,name=vend_attempt_id,json=vendAttemptId,proto3" json:"vend_attempt_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Command       *HardwareCommandRef    `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	BillFinal     *BillFinalRecord       `protobuf:"bytes,4,opt,name=bill_final,json=billFinal,proto3" json:"bill_final,omitempty"`
	TcnDispense   *TcnDispenseRecord     `protobuf:"bytes,5,opt,name=tcn_dispense,json=tcnDispense,proto3" json:"tcn_dispense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendHardwareEvidence) Reset() {
	*x = VendHardwareEvidence{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendHardwareEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendHardwareEvidence) ProtoMessage() {}

func (x *VendHardwareEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendHardwareEvidence.ProtoReflect.Descriptor instead.
func (*VendHardwareEvidence) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{21}
}

func (x *VendHardwareEvidence) GetVendAttemptId() string {
	if x != nil {
		return x.VendAttemptId
	}
	return ""
}

func (x *VendHardwareEvidence) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *VendHardwareEvidence) GetCommand() *HardwareCommandRef {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *VendHardwareEvidence) GetBillFinal() *BillFinalRecord {
	if x != nil {
		return x.BillFinal
	}
	return nil
}

func (x *VendHardwareEvidence) GetTcnDispense() *TcnDispenseRecord {
	if x != nil {
		return x.TcnDispense
	}
	return nil
}

type StartVendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVendRequest) Reset() {
	*x = StartVendRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVendRequest) ProtoMessage() {}

func (x *StartVendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVendRequest.ProtoReflect.Descriptor instead.
func (*StartVendRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{22}
}

func (x *StartVendRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StartVendRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StartVendRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type StartVendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	VendState     string                 `protobuf:"bytes,2,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVendResponse) Reset() {
	*x = StartVendResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVendResponse) ProtoMessage() {}

func (x *StartVendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVendResponse.ProtoReflect.Descriptor instead.
func (*StartVendResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{23}
}

func (x *StartVendResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *StartVendResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

func (x *StartVendResponse) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type ConfirmVendSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	CorrelationId *string                `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	Evidence      *VendHardwareEvidence  `protobuf:"bytes,5,opt,name=evidence,proto3,oneof" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmVendSuccessRequest) Reset() {
	*x = ConfirmVendSuccessRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmVendSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmVendSuccessRequest) ProtoMessage() {}

func (x *ConfirmVendSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmVendSuccessRequest.ProtoReflect.Descriptor instead.
func (*ConfirmVendSuccessRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{24}
}

func (x *ConfirmVendSuccessRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConfirmVendSuccessRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmVendSuccessRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ConfirmVendSuccessRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *ConfirmVendSuccessRequest) GetEvidence() *VendHardwareEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ConfirmVendSuccessResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Replay          bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	InventoryReplay bool                   `protobuf:"varint,2,opt,name=inventory_replay,json=inventoryReplay,proto3" json:"inventory_replay,omitempty"`
	OrderId         string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus     string                 `protobuf:"bytes,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	VendState       string                 `protobuf:"bytes,5,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmVendSuccessResponse) Reset() {
	*x = ConfirmVendSuccessResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmVendSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmVendSuccessResponse) ProtoMessage() {}

func (x *ConfirmVendSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmVendSuccessResponse.ProtoReflect.Descriptor instead.
func (*ConfirmVendSuccessResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{25}
}

func (x *ConfirmVendSuccessResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *ConfirmVendSuccessResponse) GetInventoryReplay() bool {
	if x != nil {
		return x.InventoryReplay
	}
	return false
}

func (x *ConfirmVendSuccessResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmVendSuccessResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ConfirmVendSuccessResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

type ReportVendSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	CorrelationId *string                `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	Evidence      *VendHardwareEvidence  `protobuf:"bytes,5,opt,name=evidence,proto3,oneof" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVendSuccessRequest) Reset() {
	*x = ReportVendSuccessRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVendSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVendSuccessRequest) ProtoMessage() {}

func (x *ReportVendSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVendSuccessRequest.ProtoReflect.Descriptor instead.
func (*ReportVendSuccessRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{26}
}

func (x *ReportVendSuccessRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReportVendSuccessRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReportVendSuccessRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ReportVendSuccessRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *ReportVendSuccessRequest) GetEvidence() *VendHardwareEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ReportVendSuccessResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Replay          bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	InventoryReplay bool                   `protobuf:"varint,2,opt,name=inventory_replay,json=inventoryReplay,proto3" json:"inventory_replay,omitempty"`
	OrderId         string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus     string                 `protobuf:"bytes,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	VendState       string                 `protobuf:"bytes,5,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportVendSuccessResponse) Reset() {
	*x = ReportVendSuccessResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVendSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVendSuccessResponse) ProtoMessage() {}

func (x *ReportVendSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVendSuccessResponse.ProtoReflect.Descriptor instead.
func (*ReportVendSuccessResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{27}
}

func (x *ReportVendSuccessResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *ReportVendSuccessResponse) GetInventoryReplay() bool {
	if x != nil {
		return x.InventoryReplay
	}
	return false
}

func (x *ReportVendSuccessResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReportVendSuccessResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ReportVendSuccessResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

type ReportVendFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CorrelationId *string                `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	Evidence      *VendHardwareEvidence  `protobuf:"bytes,6,opt,name=evidence,proto3,oneof" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportVendFailureRequest) Reset() {
	*x = ReportVendFailureRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVendFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVendFailureRequest) ProtoMessage() {}

func (x *ReportVendFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVendFailureRequest.ProtoReflect.Descriptor instead.
func (*ReportVendFailureRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{28}
}

func (x *ReportVendFailureRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReportVendFailureRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReportVendFailureRequest) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ReportVendFailureRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *ReportVendFailureRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *ReportVendFailureRequest) GetEvidence() *VendHardwareEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ReportVendFailureResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Replay                  bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	OrderId                 string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus             string                 `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	VendState               string                 `protobuf:"bytes,4,opt,name=vend_state,json=vendState,proto3" json:"vend_state,omitempty"`
	LocalCashRefundRequired bool                   `protobuf:"varint,5,opt,name=local_cash_refund_required,json=localCashRefundRequired,proto3" json:"local_cash_refund_required,omitempty"`
	RefundRequired          bool                   `protobuf:"varint,6,opt,name=refund_required,json=refundRequired,proto3" json:"refund_required,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReportVendFailureResponse) Reset() {
	*x = ReportVendFailureResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVendFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVendFailureResponse) ProtoMessage() {}

func (x *ReportVendFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVendFailureResponse.ProtoReflect.Descriptor instead.
func (*ReportVendFailureResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{29}
}

func (x *ReportVendFailureResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *ReportVendFailureResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReportVendFailureResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ReportVendFailureResponse) GetVendState() string {
	if x != nil {
		return x.VendState
	}
	return ""
}

func (x *ReportVendFailureResponse) GetLocalCashRefundRequired() bool {
	if x != nil {
		return x.LocalCashRefundRequired
	}
	return false
}

func (x *ReportVendFailureResponse) GetRefundRequired() bool {
	if x != nil {
		return x.RefundRequired
	}
	return false
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{30}
}

func (x *CancelOrderRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_commerce_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_commerce_proto_rawDescGZIP(), []int{31}
}

func (x *CancelOrderResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *CancelOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

var File_avf_machine_v1_commerce_proto protoreflect.FileDescriptor

const file_avf_machine_v1_commerce_proto_rawDesc = "" +
	"\n" +
	"\x1davf/machine/v1/commerce.proto\x12\x0eavf.machine.v1\x1a\x1bavf/machine/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\x11CreateSaleRequest\x128\n" +
	"\x05order\x18\x01 \x01(\v2\".avf.machine.v1.CreateOrderRequestR\x05order\"O\n" +
	"\x12CreateSaleResponse\x129\n" +
	"\x05order\x18\x01 \x01(\v2#.avf.machine.v1.CreateOrderResponseR\x05order\"l\n" +
	"\x14AttachPaymentRequest\x12T\n" +
	"\x0fpayment_session\x18\x01 \x01(\v2+.avf.machine.v1.CreatePaymentSessionRequestR\x0epaymentSession\"n\n" +
	"\x15AttachPaymentResponse\x12U\n" +
	"\x0fpayment_session\x18\x01 \x01(\v2,.avf.machine.v1.CreatePaymentSessionResponseR\x0epaymentSession\"a\n" +
	"\x1aConfirmCashReceivedRequest\x12C\n" +
	"\apayment\x18\x01 \x01(\v2).avf.machine.v1.ConfirmCashPaymentRequestR\apayment\"c\n" +
	"\x1bConfirmCashReceivedResponse\x12D\n" +
	"\apayment\x18\x01 \x01(\v2*.avf.machine.v1.ConfirmCashPaymentResponseR\apayment\"\xac\x01\n" +
	"\rSlotSelection\x12\x1c\n" +
	"\aslot_id\x18\x01 \x01(\tH\x00R\x06slotId\x88\x01\x01\x12!\n" +
	"\fcabinet_code\x18\x02 \x01(\tR\vcabinetCode\x12\x1b\n" +
	"\tslot_code\x18\x03 \x01(\tR\bslotCode\x12\"\n" +
	"\n" +
	"slot_index\x18\x04 \x01(\x05H\x01R\tslotIndex\x88\x01\x01B\n" +
	"\n" +
	"\b_slot_idB\r\n" +
	"\v_slot_index\"\xca\x01\n" +
	"\x11SimulationContext\x12\x1c\n" +
	"\tsimulated\x18\x01 \x01(\bR\tsimulated\x12*\n" +
	"\x11simulation_run_id\x18\x02 \x01(\tR\x0fsimulationRunId\x12/\n" +
	"\x13simulation_scenario\x18\x03 \x01(\tR\x12simulationScenario\x12\x1b\n" +
	"\tfake_bill\x18\x04 \x01(\bR\bfakeBill\x12\x1d\n" +
	"\n" +
	"fake_board\x18\x05 \x01(\bR\tfakeBoard\"\x82\x03\n" +
	"\x12CreateOrderRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\"\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tH\x00R\tmachineId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x121\n" +
	"\x04slot\x18\x04 \x01(\v2\x1d.avf.machine.v1.SlotSelectionR\x04slot\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x126\n" +
	"\x04meta\x18\x06 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12F\n" +
	"\n" +
	"simulation\x18\a \x01(\v2!.avf.machine.v1.SimulationContextH\x01R\n" +
	"simulation\x88\x01\x01B\r\n" +
	"\v_machine_idB\r\n" +
	"\v_simulation\"\xe9\x03\n" +
	"\x13CreateOrderResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12&\n" +
	"\x0fvend_session_id\x18\x03 \x01(\tR\rvendSessionId\x12!\n" +
	"\forder_status\x18\x04 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"vend_state\x18\x05 \x01(\tR\tvendState\x12\x17\n" +
	"\aslot_id\x18\x06 \x01(\tR\x06slotId\x12!\n" +
	"\fcabinet_code\x18\a \x01(\tR\vcabinetCode\x12\x1b\n" +
	"\tslot_code\x18\b \x01(\tR\bslotCode\x12\x1d\n" +
	"\n" +
	"slot_index\x18\t \x01(\x05R\tslotIndex\x12%\n" +
	"\x0esubtotal_minor\x18\n" +
	" \x01(\x03R\rsubtotalMinor\x12\x1b\n" +
	"\ttax_minor\x18\v \x01(\x03R\btaxMinor\x12\x1f\n" +
	"\vtotal_minor\x18\f \x01(\x03R\n" +
	"totalMinor\x12\x1f\n" +
	"\vprice_minor\x18\r \x01(\x03R\n" +
	"priceMinor\x127\n" +
	"\x04meta\x18\x0e \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\"\xfd\x02\n" +
	"\x1bCreatePaymentSessionRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12#\n" +
	"\rpayment_state\x18\x04 \x01(\tR\fpaymentState\x12!\n" +
	"\famount_minor\x18\x05 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12.\n" +
	"\x13outbox_payload_json\x18\a \x01(\tR\x11outboxPayloadJson\x12F\n" +
	"\n" +
	"simulation\x18\b \x01(\v2!.avf.machine.v1.SimulationContextH\x00R\n" +
	"simulation\x88\x01\x01B\r\n" +
	"\v_simulation\"\xcd\x01\n" +
	"\x1cCreatePaymentSessionResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12#\n" +
	"\rpayment_state\x18\x03 \x01(\tR\fpaymentState\x12&\n" +
	"\x0foutbox_event_id\x18\x04 \x01(\x03R\routboxEventId\x12)\n" +
	"\x11qr_payload_or_url\x18\x05 \x01(\tR\x0eqrPayloadOrUrl\"\xcb\x01\n" +
	"\x19ConfirmCashPaymentRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12F\n" +
	"\n" +
	"simulation\x18\x03 \x01(\v2!.avf.machine.v1.SimulationContextH\x00R\n" +
	"simulation\x88\x01\x01B\r\n" +
	"\v_simulation\"\x9b\x01\n" +
	"\x1aConfirmCashPaymentResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12!\n" +
	"\forder_status\x18\x03 \x01(\tR\vorderStatus\x12#\n" +
	"\rpayment_state\x18\x04 \x01(\tR\fpaymentState\"K\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\"\x95\x04\n" +
	"\x10GetOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0esubtotal_minor\x18\x04 \x01(\x03R\rsubtotalMinor\x12\x1b\n" +
	"\ttax_minor\x18\x05 \x01(\x03R\btaxMinor\x12\x1f\n" +
	"\vtotal_minor\x18\x06 \x01(\x03R\n" +
	"totalMinor\x12D\n" +
	"\x10order_created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eorderCreatedAt\x12\x1d\n" +
	"\n" +
	"vend_state\x18\b \x01(\tR\tvendState\x12&\n" +
	"\x0fvend_slot_index\x18\t \x01(\x05R\rvendSlotIndex\x12\x1d\n" +
	"\n" +
	"product_id\x18\n" +
	" \x01(\tR\tproductId\x12'\n" +
	"\x0fpayment_present\x18\v \x01(\bR\x0epaymentPresent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\f \x01(\tR\tpaymentId\x12)\n" +
	"\x10payment_provider\x18\r \x01(\tR\x0fpaymentProvider\x12#\n" +
	"\rpayment_state\x18\x0e \x01(\tR\fpaymentState\"Q\n" +
	"\x15GetOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\"\xc3\x01\n" +
	"\x16GetOrderStatusResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"vend_state\x18\x03 \x01(\tR\tvendState\x12'\n" +
	"\x0fpayment_present\x18\x04 \x01(\bR\x0epaymentPresent\x12#\n" +
	"\rpayment_state\x18\x05 \x01(\tR\fpaymentState\"n\n" +
	"\x12HardwareCommandRef\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12 \n" +
	"\ftx_rx_digest\x18\x02 \x01(\tR\n" +
	"txRxDigest\x12\x17\n" +
	"\araw_ref\x18\x03 \x01(\tR\x06rawRef\"\x95\x01\n" +
	"\x0fBillFinalRecord\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\famount_minor\x18\x02 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1c\n" +
	"\araw_ref\x18\x04 \x01(\tH\x00R\x06rawRef\x88\x01\x01B\n" +
	"\n" +
	"\b_raw_ref\"\xab\x01\n" +
	"\x11TcnDispenseRecord\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x18\n" +
	"\adropped\x18\x03 \x01(\bR\adropped\x12\x1b\n" +
	"\x06digest\x18\x04 \x01(\tH\x00R\x06digest\x88\x01\x01\x12\x1c\n" +
	"\araw_ref\x18\x05 \x01(\tH\x01R\x06rawRef\x88\x01\x01B\t\n" +
	"\a_digestB\n" +
	"\n" +
	"\b_raw_ref\"\xa9\x02\n" +
	"\x14VendHardwareEvidence\x12&\n" +
	"\x0fvend_attempt_id\x18\x01 \x01(\tR\rvendAttemptId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12<\n" +
	"\acommand\x18\x03 \x01(\v2\".avf.machine.v1.HardwareCommandRefR\acommand\x12>\n" +
	"\n" +
	"bill_final\x18\x04 \x01(\v2\x1f.avf.machine.v1.BillFinalRecordR\tbillFinal\x12D\n" +
	"\ftcn_dispense\x18\x05 \x01(\v2!.avf.machine.v1.TcnDispenseRecordR\vtcnDispense\"\x8a\x01\n" +
	"\x10StartVendRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\"i\n" +
	"\x11StartVendResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1d\n" +
	"\n" +
	"vend_state\x18\x02 \x01(\tR\tvendState\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\"\xa6\x02\n" +
	"\x19ConfirmVendSuccessRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\x12*\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tH\x00R\rcorrelationId\x88\x01\x01\x12E\n" +
	"\bevidence\x18\x05 \x01(\v2$.avf.machine.v1.VendHardwareEvidenceH\x01R\bevidence\x88\x01\x01B\x11\n" +
	"\x0f_correlation_idB\v\n" +
	"\t_evidence\"\xbc\x01\n" +
	"\x1aConfirmVendSuccessResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12)\n" +
	"\x10inventory_replay\x18\x02 \x01(\bR\x0finventoryReplay\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x04 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"vend_state\x18\x05 \x01(\tR\tvendState\"\xa5\x02\n" +
	"\x18ReportVendSuccessRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\x12*\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tH\x00R\rcorrelationId\x88\x01\x01\x12E\n" +
	"\bevidence\x18\x05 \x01(\v2$.avf.machine.v1.VendHardwareEvidenceH\x01R\bevidence\x88\x01\x01B\x11\n" +
	"\x0f_correlation_idB\v\n" +
	"\t_evidence\"\xbb\x01\n" +
	"\x19ReportVendSuccessResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12)\n" +
	"\x10inventory_replay\x18\x02 \x01(\bR\x0finventoryReplay\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x04 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"vend_state\x18\x05 \x01(\tR\tvendState\"\xcc\x02\n" +
	"\x18ReportVendFailureRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12*\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tH\x00R\rcorrelationId\x88\x01\x01\x12E\n" +
	"\bevidence\x18\x06 \x01(\v2$.avf.machine.v1.VendHardwareEvidenceH\x01R\bevidence\x88\x01\x01B\x11\n" +
	"\x0f_correlation_idB\v\n" +
	"\t_evidence\"\xf6\x01\n" +
	"\x19ReportVendFailureResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"vend_state\x18\x04 \x01(\tR\tvendState\x12;\n" +
	"\x1alocal_cash_refund_required\x18\x05 \x01(\bR\x17localCashRefundRequired\x12'\n" +
	"\x0frefund_required\x18\x06 \x01(\bR\x0erefundRequired\"\x85\x01\n" +
	"\x12CancelOrderRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"k\n" +
	"\x13CancelOrderResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\tR\vorderStatus2\xca\t\n" +
	"\x16MachineCommerceService\x12V\n" +
	"\vCreateOrder\x12\".avf.machine.v1.CreateOrderRequest\x1a#.avf.machine.v1.CreateOrderResponse\x12q\n" +
	"\x14CreatePaymentSession\x12+.avf.machine.v1.CreatePaymentSessionRequest\x1a,.avf.machine.v1.CreatePaymentSessionResponse\x12p\n" +
	"\x13AttachPaymentResult\x12+.avf.machine.v1.CreatePaymentSessionRequest\x1a,.avf.machine.v1.CreatePaymentSessionResponse\x12k\n" +
	"\x12ConfirmCashPayment\x12).avf.machine.v1.ConfirmCashPaymentRequest\x1a*.avf.machine.v1.ConfirmCashPaymentResponse\x12k\n" +
	"\x12CreateCashCheckout\x12).avf.machine.v1.ConfirmCashPaymentRequest\x1a*.avf.machine.v1.ConfirmCashPaymentResponse\x12M\n" +
	"\bGetOrder\x12\x1f.avf.machine.v1.GetOrderRequest\x1a .avf.machine.v1.GetOrderResponse\x12_\n" +
	"\x0eGetOrderStatus\x12%.avf.machine.v1.GetOrderStatusRequest\x1a&.avf.machine.v1.GetOrderStatusResponse\x12P\n" +
	"\tStartVend\x12 .avf.machine.v1.StartVendRequest\x1a!.avf.machine.v1.StartVendResponse\x12k\n" +
	"\x12ConfirmVendSuccess\x12).avf.machine.v1.ConfirmVendSuccessRequest\x1a*.avf.machine.v1.ConfirmVendSuccessResponse\x12h\n" +
	"\x11ReportVendSuccess\x12(.avf.machine.v1.ReportVendSuccessRequest\x1a).avf.machine.v1.ReportVendSuccessResponse\x12h\n" +
	"\x11ReportVendFailure\x12(.avf.machine.v1.ReportVendFailureRequest\x1a).avf.machine.v1.ReportVendFailureResponse\x12V\n" +
	"\vCancelOrder\x12\".avf.machine.v1.CancelOrderRequest\x1a#.avf.machine.v1.CancelOrderResponse2\xa8\x05\n" +
	"\x12MachineSaleService\x12S\n" +
	"\n" +
	"CreateSale\x12!.avf.machine.v1.CreateSaleRequest\x1a\".avf.machine.v1.CreateSaleResponse\x12\\\n" +
	"\rAttachPayment\x12$.avf.machine.v1.AttachPaymentRequest\x1a%.avf.machine.v1.AttachPaymentResponse\x12n\n" +
	"\x13ConfirmCashReceived\x12*.avf.machine.v1.ConfirmCashReceivedRequest\x1a+.avf.machine.v1.ConfirmCashReceivedResponse\x12P\n" +
	"\tStartVend\x12 .avf.machine.v1.StartVendRequest\x1a!.avf.machine.v1.StartVendResponse\x12e\n" +
	"\fCompleteVend\x12).avf.machine.v1.ConfirmVendSuccessRequest\x1a*.avf.machine.v1.ConfirmVendSuccessResponse\x12_\n" +
	"\bFailVend\x12(.avf.machine.v1.ReportVendFailureRequest\x1a).avf.machine.v1.ReportVendFailureResponse\x12U\n" +
	"\n" +
	"CancelSale\x12\".avf.machine.v1.CancelOrderRequest\x1a#.avf.machine.v1.CancelOrderResponseB?Z=github.com/avf/avf-vending-api/proto/avf/machine/v1;machinev1b\x06proto3"

var (
	file_avf_machine_v1_commerce_proto_rawDescOnce sync.Once
	file_avf_machine_v1_commerce_proto_rawDescData []byte
)

func file_avf_machine_v1_commerce_proto_rawDescGZIP() []byte {
	file_avf_machine_v1_commerce_proto_rawDescOnce.Do(func() {
		file_avf_machine_v1_commerce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_machine_v1_commerce_proto_rawDesc), len(file_avf_machine_v1_commerce_proto_rawDesc)))
	})
	return file_avf_machine_v1_commerce_proto_rawDescData
}

var file_avf_machine_v1_commerce_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_avf_machine_v1_commerce_proto_goTypes = []any{
	(*CreateSaleRequest)(nil),            // 0: avf.machine.v1.CreateSaleRequest
	(*CreateSaleResponse)(nil),           // 1: avf.machine.v1.CreateSaleResponse
	(*AttachPaymentRequest)(nil),         // 2: avf.machine.v1.AttachPaymentRequest
	(*AttachPaymentResponse)(nil),        // 3: avf.machine.v1.AttachPaymentResponse
	(*ConfirmCashReceivedRequest)(nil),   // 4: avf.machine.v1.ConfirmCashReceivedRequest
	(*ConfirmCashReceivedResponse)(nil),  // 5: avf.machine.v1.ConfirmCashReceivedResponse
	(*SlotSelection)(nil),                // 6: avf.machine.v1.SlotSelection
	(*SimulationContext)(nil),            // 7: avf.machine.v1.SimulationContext
	(*CreateOrderRequest)(nil),           // 8: avf.machine.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),          // 9: avf.machine.v1.CreateOrderResponse
	(*CreatePaymentSessionRequest)(nil),  // 10: avf.machine.v1.CreatePaymentSessionRequest
	(*CreatePaymentSessionResponse)(nil), // 11: avf.machine.v1.CreatePaymentSessionResponse
	(*ConfirmCashPaymentRequest)(nil),    // 12: avf.machine.v1.ConfirmCashPaymentRequest
	(*ConfirmCashPaymentResponse)(nil),   // 13: avf.machine.v1.ConfirmCashPaymentResponse
	(*GetOrderRequest)(nil),              // 14: avf.machine.v1.GetOrderRequest
	(*GetOrderResponse)(nil),             // 15: avf.machine.v1.GetOrderResponse
	(*GetOrderStatusRequest)(nil),        // 16: avf.machine.v1.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil),       // 17: avf.machine.v1.GetOrderStatusResponse
	(*HardwareCommandRef)(nil),           // 18: avf.machine.v1.HardwareCommandRef
	(*BillFinalRecord)(nil),              // 19: avf.machine.v1.BillFinalRecord
	(*TcnDispenseRecord)(nil),            // 20: avf.machine.v1.TcnDispenseRecord
	(*VendHardwareEvidence)(nil),         // 21: avf.machine.v1.VendHardwareEvidence
	(*StartVendRequest)(nil),             // 22: avf.machine.v1.StartVendRequest
	(*StartVendResponse)(nil),            // 23: avf.machine.v1.StartVendResponse
	(*ConfirmVendSuccessRequest)(nil),    // 24: avf.machine.v1.ConfirmVendSuccessRequest
	(*ConfirmVendSuccessResponse)(nil),   // 25: avf.machine.v1.ConfirmVendSuccessResponse
	(*ReportVendSuccessRequest)(nil),     // 26: avf.machine.v1.ReportVendSuccessRequest
	(*ReportVendSuccessResponse)(nil),    // 27: avf.machine.v1.ReportVendSuccessResponse
	(*ReportVendFailureRequest)(nil),     // 28: avf.machine.v1.ReportVendFailureRequest
	(*ReportVendFailureResponse)(nil),    // 29: avf.machine.v1.ReportVendFailureResponse
	(*CancelOrderRequest)(nil),           // 30: avf.machine.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),          // 31: avf.machine.v1.CancelOrderResponse
	(*IdempotencyContext)(nil),           // 32: avf.machine.v1.IdempotencyContext
	(*MachineRequestMeta)(nil),           // 33: avf.machine.v1.MachineRequestMeta
	(*MachineResponseMeta)(nil),          // 34: avf.machine.v1.MachineResponseMeta
	(*timestamppb.Timestamp)(nil),        // 35: google.protobuf.Timestamp
}
var file_avf_machine_v1_commerce_proto_depIdxs = []int32{
	8,  // 0: avf.machine.v1.CreateSaleRequest.order:type_name -> avf.machine.v1.CreateOrderRequest
	9,  // 1: avf.machine.v1.CreateSaleResponse.order:type_name -> avf.machine.v1.CreateOrderResponse
	10, // 2: avf.machine.v1.AttachPaymentRequest.payment_session:type_name -> avf.machine.v1.CreatePaymentSessionRequest
	11, // 3: avf.machine.v1.AttachPaymentResponse.payment_session:type_name -> avf.machine.v1.CreatePaymentSessionResponse
	12, // 4: avf.machine.v1.ConfirmCashReceivedRequest.payment:type_name -> avf.machine.v1.ConfirmCashPaymentRequest
	13, // 5: avf.machine.v1.ConfirmCashReceivedResponse.payment:type_name -> avf.machine.v1.ConfirmCashPaymentResponse
	32, // 6: avf.machine.v1.CreateOrderRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	6,  // 7: avf.machine.v1.CreateOrderRequest.slot:type_name -> avf.machine.v1.SlotSelection
	33, // 8: avf.machine.v1.CreateOrderRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	7,  // 9: avf.machine.v1.CreateOrderRequest.simulation:type_name -> avf.machine.v1.SimulationContext
	34, // 10: avf.machine.v1.CreateOrderResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	32, // 11: avf.machine.v1.CreatePaymentSessionRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	7,  // 12: avf.machine.v1.CreatePaymentSessionRequest.simulation:type_name -> avf.machine.v1.SimulationContext
	32, // 13: avf.machine.v1.ConfirmCashPaymentRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	7,  // 14: avf.machine.v1.ConfirmCashPaymentRequest.simulation:type_name -> avf.machine.v1.SimulationContext
	35, // 15: avf.machine.v1.GetOrderResponse.order_created_at:type_name -> google.protobuf.Timestamp
	18, // 16: avf.machine.v1.VendHardwareEvidence.command:type_name -> avf.machine.v1.HardwareCommandRef
	19, // 17: avf.machine.v1.VendHardwareEvidence.bill_final:type_name -> avf.machine.v1.BillFinalRecord
	20, // 18: avf.machine.v1.VendHardwareEvidence.tcn_dispense:type_name -> avf.machine.v1.TcnDispenseRecord
	32, // 19: avf.machine.v1.StartVendRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	32, // 20: avf.machine.v1.ConfirmVendSuccessRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	21, // 21: avf.machine.v1.ConfirmVendSuccessRequest.evidence:type_name -> avf.machine.v1.VendHardwareEvidence
	32, // 22: avf.machine.v1.ReportVendSuccessRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	21, // 23: avf.machine.v1.ReportVendSuccessRequest.evidence:type_name -> avf.machine.v1.VendHardwareEvidence
	32, // 24: avf.machine.v1.ReportVendFailureRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	21, // 25: avf.machine.v1.ReportVendFailureRequest.evidence:type_name -> avf.machine.v1.VendHardwareEvidence
	32, // 26: avf.machine.v1.CancelOrderRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	8,  // 27: avf.machine.v1.MachineCommerceService.CreateOrder:input_type -> avf.machine.v1.CreateOrderRequest
	10, // 28: avf.machine.v1.MachineCommerceService.CreatePaymentSession:input_type -> avf.machine.v1.CreatePaymentSessionRequest
	10, // 29: avf.machine.v1.MachineCommerceService.AttachPaymentResult:input_type -> avf.machine.v1.CreatePaymentSessionRequest
	12, // 30: avf.machine.v1.MachineCommerceService.ConfirmCashPayment:input_type -> avf.machine.v1.ConfirmCashPaymentRequest
	12, // 31: avf.machine.v1.MachineCommerceService.CreateCashCheckout:input_type -> avf.machine.v1.ConfirmCashPaymentRequest
	14, // 32: avf.machine.v1.MachineCommerceService.GetOrder:input_type -> avf.machine.v1.GetOrderRequest
	16, // 33: avf.machine.v1.MachineCommerceService.GetOrderStatus:input_type -> avf.machine.v1.GetOrderStatusRequest
	22, // 34: avf.machine.v1.MachineCommerceService.StartVend:input_type -> avf.machine.v1.StartVendRequest
	24, // 35: avf.machine.v1.MachineCommerceService.ConfirmVendSuccess:input_type -> avf.machine.v1.ConfirmVendSuccessRequest
	26, // 36: avf.machine.v1.MachineCommerceService.ReportVendSuccess:input_type -> avf.machine.v1.ReportVendSuccessRequest
	28, // 37: avf.machine.v1.MachineCommerceService.ReportVendFailure:input_type -> avf.machine.v1.ReportVendFailureRequest
	30, // 38: avf.machine.v1.MachineCommerceService.CancelOrder:input_type -> avf.machine.v1.CancelOrderRequest
	0,  // 39: avf.machine.v1.MachineSaleService.CreateSale:input_type -> avf.machine.v1.CreateSaleRequest
	2,  // 40: avf.machine.v1.MachineSaleService.AttachPayment:input_type -> avf.machine.v1.AttachPaymentRequest
	4,  // 41: avf.machine.v1.MachineSaleService.ConfirmCashReceived:input_type -> avf.machine.v1.ConfirmCashReceivedRequest
	22, // 42: avf.machine.v1.MachineSaleService.StartVend:input_type -> avf.machine.v1.StartVendRequest
	24, // 43: avf.machine.v1.MachineSaleService.CompleteVend:input_type -> avf.machine.v1.ConfirmVendSuccessRequest
	28, // 44: avf.machine.v1.MachineSaleService.FailVend:input_type -> avf.machine.v1.ReportVendFailureRequest
	30, // 45: avf.machine.v1.MachineSaleService.CancelSale:input_type -> avf.machine.v1.CancelOrderRequest
	9,  // 46: avf.machine.v1.MachineCommerceService.CreateOrder:output_type -> avf.machine.v1.CreateOrderResponse
	11, // 47: avf.machine.v1.MachineCommerceService.CreatePaymentSession:output_type -> avf.machine.v1.CreatePaymentSessionResponse
	11, // 48: avf.machine.v1.MachineCommerceService.AttachPaymentResult:output_type -> avf.machine.v1.CreatePaymentSessionResponse
	13, // 49: avf.machine.v1.MachineCommerceService.ConfirmCashPayment:output_type -> avf.machine.v1.ConfirmCashPaymentResponse
	13, // 50: avf.machine.v1.MachineCommerceService.CreateCashCheckout:output_type -> avf.machine.v1.ConfirmCashPaymentResponse
	15, // 51: avf.machine.v1.MachineCommerceService.GetOrder:output_type -> avf.machine.v1.GetOrderResponse
	17, // 52: avf.machine.v1.MachineCommerceService.GetOrderStatus:output_type -> avf.machine.v1.GetOrderStatusResponse
	23, // 53: avf.machine.v1.MachineCommerceService.StartVend:output_type -> avf.machine.v1.StartVendResponse
	25, // 54: avf.machine.v1.MachineCommerceService.ConfirmVendSuccess:output_type -> avf.machine.v1.ConfirmVendSuccessResponse
	27, // 55: avf.machine.v1.MachineCommerceService.ReportVendSuccess:output_type -> avf.machine.v1.ReportVendSuccessResponse
	29, // 56: avf.machine.v1.MachineCommerceService.ReportVendFailure:output_type -> avf.machine.v1.ReportVendFailureResponse
	31, // 57: avf.machine.v1.MachineCommerceService.CancelOrder:output_type -> avf.machine.v1.CancelOrderResponse
	1,  // 58: avf.machine.v1.MachineSaleService.CreateSale:output_type -> avf.machine.v1.CreateSaleResponse
	3,  // 59: avf.machine.v1.MachineSaleService.AttachPayment:output_type -> avf.machine.v1.AttachPaymentResponse
	5,  // 60: avf.machine.v1.MachineSaleService.ConfirmCashReceived:output_type -> avf.machine.v1.ConfirmCashReceivedResponse
	23, // 61: avf.machine.v1.MachineSaleService.StartVend:output_type -> avf.machine.v1.StartVendResponse
	25, // 62: avf.machine.v1.MachineSaleService.CompleteVend:output_type -> avf.machine.v1.ConfirmVendSuccessResponse
	29, // 63: avf.machine.v1.MachineSaleService.FailVend:output_type -> avf.machine.v1.ReportVendFailureResponse
	31, // 64: avf.machine.v1.MachineSaleService.CancelSale:output_type -> avf.machine.v1.CancelOrderResponse
	46, // [46:65] is the sub-list for method output_type
	27, // [27:46] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_avf_machine_v1_commerce_proto_init() }
func file_avf_machine_v1_commerce_proto_init() {
	if File_avf_machine_v1_commerce_proto != nil {
		return
	}
	file_avf_machine_v1_common_proto_init()
	file_avf_machine_v1_commerce_proto_msgTypes[6].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[8].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[10].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[12].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[19].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[20].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[24].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[26].OneofWrappers = []any{}
	file_avf_machine_v1_commerce_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_machine_v1_commerce_proto_rawDesc), len(file_avf_machine_v1_commerce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_avf_machine_v1_commerce_proto_goTypes,
		DependencyIndexes: file_avf_machine_v1_commerce_proto_depIdxs,
		MessageInfos:      file_avf_machine_v1_commerce_proto_msgTypes,
	}.Build()
	File_avf_machine_v1_commerce_proto = out.File
	file_avf_machine_v1_commerce_proto_goTypes = nil
	file_avf_machine_v1_commerce_proto_depIdxs = nil
}
