// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avf/machine/v1/common.proto

package machinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineResponseStatus int32

const (
	MachineResponseStatus_MACHINE_RESPONSE_STATUS_UNSPECIFIED  MachineResponseStatus = 0
	MachineResponseStatus_MACHINE_RESPONSE_STATUS_ACCEPTED     MachineResponseStatus = 1
	MachineResponseStatus_MACHINE_RESPONSE_STATUS_REPLAYED     MachineResponseStatus = 2
	MachineResponseStatus_MACHINE_RESPONSE_STATUS_REJECTED     MachineResponseStatus = 3
	MachineResponseStatus_MACHINE_RESPONSE_STATUS_NOT_MODIFIED MachineResponseStatus = 4
)

// Enum value maps for MachineResponseStatus.
var (
	MachineResponseStatus_name = map[int32]string{
		0: "MACHINE_RESPONSE_STATUS_UNSPECIFIED",
		1: "MACHINE_RESPONSE_STATUS_ACCEPTED",
		2: "MACHINE_RESPONSE_STATUS_REPLAYED",
		3: "MACHINE_RESPONSE_STATUS_REJECTED",
		4: "MACHINE_RESPONSE_STATUS_NOT_MODIFIED",
	}
	MachineResponseStatus_value = map[string]int32{
		"MACHINE_RESPONSE_STATUS_UNSPECIFIED":  0,
		"MACHINE_RESPONSE_STATUS_ACCEPTED":     1,
		"MACHINE_RESPONSE_STATUS_REPLAYED":     2,
		"MACHINE_RESPONSE_STATUS_REJECTED":     3,
		"MACHINE_RESPONSE_STATUS_NOT_MODIFIED": 4,
	}
)

func (x MachineResponseStatus) Enum() *MachineResponseStatus {
	p := new(MachineResponseStatus)
	*p = x
	return p
}

func (x MachineResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_avf_machine_v1_common_proto_enumTypes[0].Descriptor()
}

func (MachineResponseStatus) Type() protoreflect.EnumType {
	return &file_avf_machine_v1_common_proto_enumTypes[0]
}

func (x MachineResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineResponseStatus.Descriptor instead.
func (MachineResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{0}
}

// MachineRequestMeta is the common envelope for machine app RPCs. Machine JWT
// claims remain authoritative for organization_id and machine_id on protected RPCs.
type MachineRequestMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	MachineId       string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ClientSequence  int64                  `protobuf:"varint,6,opt,name=client_sequence,json=clientSequence,proto3" json:"client_sequence,omitempty"`
	OfflineSequence int64                  `protobuf:"varint,7,opt,name=offline_sequence,json=offlineSequence,proto3" json:"offline_sequence,omitempty"`
	AppVersion      string                 `protobuf:"bytes,8,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	ConfigVersion   int64                  `protobuf:"varint,9,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	CatalogVersion  string                 `protobuf:"bytes,10,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	// Optional echo for offline correlation (also carried on IdempotencyContext.client_event_id for mutations).
	ClientEventId string `protobuf:"bytes,11,opt,name=client_event_id,json=clientEventId,proto3" json:"client_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineRequestMeta) Reset() {
	*x = MachineRequestMeta{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineRequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRequestMeta) ProtoMessage() {}

func (x *MachineRequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRequestMeta.ProtoReflect.Descriptor instead.
func (*MachineRequestMeta) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *MachineRequestMeta) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *MachineRequestMeta) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineRequestMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MachineRequestMeta) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MachineRequestMeta) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *MachineRequestMeta) GetClientSequence() int64 {
	if x != nil {
		return x.ClientSequence
	}
	return 0
}

func (x *MachineRequestMeta) GetOfflineSequence() int64 {
	if x != nil {
		return x.OfflineSequence
	}
	return 0
}

func (x *MachineRequestMeta) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *MachineRequestMeta) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *MachineRequestMeta) GetCatalogVersion() string {
	if x != nil {
		return x.CatalogVersion
	}
	return ""
}

func (x *MachineRequestMeta) GetClientEventId() string {
	if x != nil {
		return x.ClientEventId
	}
	return ""
}

type MachineResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        MachineResponseStatus  `protobuf:"varint,4,opt,name=status,proto3,enum=avf.machine.v1.MachineResponseStatus" json:"status,omitempty"`
	Retryable     bool                   `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineResponseMeta) Reset() {
	*x = MachineResponseMeta{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineResponseMeta) ProtoMessage() {}

func (x *MachineResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineResponseMeta.ProtoReflect.Descriptor instead.
func (*MachineResponseMeta) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *MachineResponseMeta) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *MachineResponseMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MachineResponseMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MachineResponseMeta) GetStatus() MachineResponseStatus {
	if x != nil {
		return x.Status
	}
	return MachineResponseStatus_MACHINE_RESPONSE_STATUS_UNSPECIFIED
}

func (x *MachineResponseMeta) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *MachineResponseMeta) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// Money is a currency amount in minor units (e.g. cents).
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	MinorUnits    int64                  `protobuf:"varint,2,opt,name=minor_units,json=minorUnits,proto3" json:"minor_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetMinorUnits() int64 {
	if x != nil {
		return x.MinorUnits
	}
	return 0
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int32                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// MachineContext carries machine-scoped identity for RPCs (mirrors HTTP path scope).
type MachineContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MachineId      string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	SiteId         string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineContext) Reset() {
	*x = MachineContext{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContext) ProtoMessage() {}

func (x *MachineContext) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContext.ProtoReflect.Descriptor instead.
func (*MachineContext) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *MachineContext) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineContext) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *MachineContext) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

type IdempotencyContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey    string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ClientEventId     string                 `protobuf:"bytes,2,opt,name=client_event_id,json=clientEventId,proto3" json:"client_event_id,omitempty"`
	ClientCreatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=client_created_at,json=clientCreatedAt,proto3" json:"client_created_at,omitempty"`
	OperatorSessionId *string                `protobuf:"bytes,4,opt,name=operator_session_id,json=operatorSessionId,proto3,oneof" json:"operator_session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IdempotencyContext) Reset() {
	*x = IdempotencyContext{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyContext) ProtoMessage() {}

func (x *IdempotencyContext) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyContext.ProtoReflect.Descriptor instead.
func (*IdempotencyContext) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *IdempotencyContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *IdempotencyContext) GetClientEventId() string {
	if x != nil {
		return x.ClientEventId
	}
	return ""
}

func (x *IdempotencyContext) GetClientCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientCreatedAt
	}
	return nil
}

func (x *IdempotencyContext) GetOperatorSessionId() string {
	if x != nil && x.OperatorSessionId != nil {
		return *x.OperatorSessionId
	}
	return ""
}

type ClientEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *ClientEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ClientEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ClientEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// MediaAssetRef references binary media via HTTPS; bytes are never sent on gRPC.
type MediaAssetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ByteLength    int64                  `protobuf:"varint,4,opt,name=byte_length,json=byteLength,proto3" json:"byte_length,omitempty"`
	CacheHints    map[string]string      `protobuf:"bytes,5,rep,name=cache_hints,json=cacheHints,proto3" json:"cache_hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAssetRef) Reset() {
	*x = MediaAssetRef{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAssetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAssetRef) ProtoMessage() {}

func (x *MediaAssetRef) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAssetRef.ProtoReflect.Descriptor instead.
func (*MediaAssetRef) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *MediaAssetRef) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *MediaAssetRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAssetRef) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaAssetRef) GetByteLength() int64 {
	if x != nil {
		return x.ByteLength
	}
	return 0
}

func (x *MediaAssetRef) GetCacheHints() map[string]string {
	if x != nil {
		return x.CacheHints
	}
	return nil
}

// GrpcErrorDetail is a structured detail compatible with google.rpc-style consumers
// without importing googleapis protos into this module.
type GrpcErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcErrorDetail) Reset() {
	*x = GrpcErrorDetail{}
	mi := &file_avf_machine_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcErrorDetail) ProtoMessage() {}

func (x *GrpcErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcErrorDetail.ProtoReflect.Descriptor instead.
func (*GrpcErrorDetail) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *GrpcErrorDetail) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GrpcErrorDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GrpcErrorDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_avf_machine_v1_common_proto protoreflect.FileDescriptor

const file_avf_machine_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bavf/machine/v1/common.proto\x12\x0eavf.machine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x03\n" +
	"\x12MachineRequestMeta\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12'\n" +
	"\x0fclient_sequence\x18\x06 \x01(\x03R\x0eclientSequence\x12)\n" +
	"\x10offline_sequence\x18\a \x01(\x03R\x0fofflineSequence\x12\x1f\n" +
	"\vapp_version\x18\b \x01(\tR\n" +
	"appVersion\x12%\n" +
	"\x0econfig_version\x18\t \x01(\x03R\rconfigVersion\x12'\n" +
	"\x0fcatalog_version\x18\n" +
	" \x01(\tR\x0ecatalogVersion\x12&\n" +
	"\x0fclient_event_id\x18\v \x01(\tR\rclientEventId\"\x88\x02\n" +
	"\x13MachineResponseMeta\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2%.avf.machine.v1.MachineResponseStatusR\x06status\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\"M\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x1f\n" +
	"\vminor_units\x18\x02 \x01(\x03R\n" +
	"minorUnits\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"U\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\"q\n" +
	"\x0eMachineContext\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\"\xfa\x01\n" +
	"\x12IdempotencyContext\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x0fclient_event_id\x18\x02 \x01(\tR\rclientEventId\x12F\n" +
	"\x11client_created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientCreatedAt\x123\n" +
	"\x13operator_session_id\x18\x04 \x01(\tH\x00R\x11operatorSessionId\x88\x01\x01B\x16\n" +
	"\x14_operator_session_id\"\xf5\x01\n" +
	"\vClientEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12K\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2+.avf.machine.v1.ClientEvent.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\rMediaAssetRef\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vbyte_length\x18\x04 \x01(\x03R\n" +
	"byteLength\x12N\n" +
	"\vcache_hints\x18\x05 \x03(\v2-.avf.machine.v1.MediaAssetRef.CacheHintsEntryR\n" +
	"cacheHints\x1a=\n" +
	"\x0fCacheHintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x0fGrpcErrorDetail\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.avf.machine.v1.GrpcErrorDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xdc\x01\n" +
	"\x15MachineResponseStatus\x12'\n" +
	"#MACHINE_RESPONSE_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" MACHINE_RESPONSE_STATUS_ACCEPTED\x10\x01\x12$\n" +
	" MACHINE_RESPONSE_STATUS_REPLAYED\x10\x02\x12$\n" +
	" MACHINE_RESPONSE_STATUS_REJECTED\x10\x03\x12(\n" +
	"$MACHINE_RESPONSE_STATUS_NOT_MODIFIED\x10\x04B?Z=github.com/avf/avf-vending-api/proto/avf/machine/v1;machinev1b\x06proto3"

var (
	file_avf_machine_v1_common_proto_rawDescOnce sync.Once
	file_avf_machine_v1_common_proto_rawDescData []byte
)

func file_avf_machine_v1_common_proto_rawDescGZIP() []byte {
	file_avf_machine_v1_common_proto_rawDescOnce.Do(func() {
		file_avf_machine_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_machine_v1_common_proto_rawDesc), len(file_avf_machine_v1_common_proto_rawDesc)))
	})
	return file_avf_machine_v1_common_proto_rawDescData
}

var file_avf_machine_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_avf_machine_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_avf_machine_v1_common_proto_goTypes = []any{
	(MachineResponseStatus)(0),    // 0: avf.machine.v1.MachineResponseStatus
	(*MachineRequestMeta)(nil),    // 1: avf.machine.v1.MachineRequestMeta
	(*MachineResponseMeta)(nil),   // 2: avf.machine.v1.MachineResponseMeta
	(*Money)(nil),                 // 3: avf.machine.v1.Money
	(*PageRequest)(nil),           // 4: avf.machine.v1.PageRequest
	(*PageResponse)(nil),          // 5: avf.machine.v1.PageResponse
	(*MachineContext)(nil),        // 6: avf.machine.v1.MachineContext
	(*IdempotencyContext)(nil),    // 7: avf.machine.v1.IdempotencyContext
	(*ClientEvent)(nil),           // 8: avf.machine.v1.ClientEvent
	(*MediaAssetRef)(nil),         // 9: avf.machine.v1.MediaAssetRef
	(*GrpcErrorDetail)(nil),       // 10: avf.machine.v1.GrpcErrorDetail
	nil,                           // 11: avf.machine.v1.ClientEvent.AttributesEntry
	nil,                           // 12: avf.machine.v1.MediaAssetRef.CacheHintsEntry
	nil,                           // 13: avf.machine.v1.GrpcErrorDetail.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_avf_machine_v1_common_proto_depIdxs = []int32{
	14, // 0: avf.machine.v1.MachineRequestMeta.occurred_at:type_name -> google.protobuf.Timestamp
	14, // 1: avf.machine.v1.MachineResponseMeta.server_time:type_name -> google.protobuf.Timestamp
	0,  // 2: avf.machine.v1.MachineResponseMeta.status:type_name -> avf.machine.v1.MachineResponseStatus
	14, // 3: avf.machine.v1.IdempotencyContext.client_created_at:type_name -> google.protobuf.Timestamp
	14, // 4: avf.machine.v1.ClientEvent.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 5: avf.machine.v1.ClientEvent.attributes:type_name -> avf.machine.v1.ClientEvent.AttributesEntry
	12, // 6: avf.machine.v1.MediaAssetRef.cache_hints:type_name -> avf.machine.v1.MediaAssetRef.CacheHintsEntry
	13, // 7: avf.machine.v1.GrpcErrorDetail.metadata:type_name -> avf.machine.v1.GrpcErrorDetail.MetadataEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_avf_machine_v1_common_proto_init() }
func file_avf_machine_v1_common_proto_init() {
	if File_avf_machine_v1_common_proto != nil {
		return
	}
	file_avf_machine_v1_common_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_machine_v1_common_proto_rawDesc), len(file_avf_machine_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avf_machine_v1_common_proto_goTypes,
		DependencyIndexes: file_avf_machine_v1_common_proto_depIdxs,
		EnumInfos:         file_avf_machine_v1_common_proto_enumTypes,
		MessageInfos:      file_avf_machine_v1_common_proto_msgTypes,
	}.Build()
	File_avf_machine_v1_common_proto = out.File
	file_avf_machine_v1_common_proto_goTypes = nil
	file_avf_machine_v1_common_proto_depIdxs = nil
}
