// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avf/machine/v1/inventory.proto

package machinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInventorySnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventorySnapshotRequest) Reset() {
	*x = GetInventorySnapshotRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventorySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventorySnapshotRequest) ProtoMessage() {}

func (x *GetInventorySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventorySnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetInventorySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetInventorySnapshotRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type InventorySlotRow struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PlanogramId              string                 `protobuf:"bytes,1,opt,name=planogram_id,json=planogramId,proto3" json:"planogram_id,omitempty"`
	PlanogramName            string                 `protobuf:"bytes,2,opt,name=planogram_name,json=planogramName,proto3" json:"planogram_name,omitempty"`
	SlotIndex                int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	CurrentQuantity          int32                  `protobuf:"varint,4,opt,name=current_quantity,json=currentQuantity,proto3" json:"current_quantity,omitempty"`
	MaxQuantity              int32                  `protobuf:"varint,5,opt,name=max_quantity,json=maxQuantity,proto3" json:"max_quantity,omitempty"`
	PriceMinor               int64                  `protobuf:"varint,6,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	PlanogramRevisionApplied int32                  `protobuf:"varint,7,opt,name=planogram_revision_applied,json=planogramRevisionApplied,proto3" json:"planogram_revision_applied,omitempty"`
	CabinetCode              string                 `protobuf:"bytes,8,opt,name=cabinet_code,json=cabinetCode,proto3" json:"cabinet_code,omitempty"`
	CabinetIndex             int32                  `protobuf:"varint,9,opt,name=cabinet_index,json=cabinetIndex,proto3" json:"cabinet_index,omitempty"`
	ProductId                string                 `protobuf:"bytes,10,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductSku               string                 `protobuf:"bytes,11,opt,name=product_sku,json=productSku,proto3" json:"product_sku,omitempty"`
	ProductName              string                 `protobuf:"bytes,12,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	IsEmpty                  bool                   `protobuf:"varint,13,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InventorySlotRow) Reset() {
	*x = InventorySlotRow{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySlotRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySlotRow) ProtoMessage() {}

func (x *InventorySlotRow) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySlotRow.ProtoReflect.Descriptor instead.
func (*InventorySlotRow) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventorySlotRow) GetPlanogramId() string {
	if x != nil {
		return x.PlanogramId
	}
	return ""
}

func (x *InventorySlotRow) GetPlanogramName() string {
	if x != nil {
		return x.PlanogramName
	}
	return ""
}

func (x *InventorySlotRow) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *InventorySlotRow) GetCurrentQuantity() int32 {
	if x != nil {
		return x.CurrentQuantity
	}
	return 0
}

func (x *InventorySlotRow) GetMaxQuantity() int32 {
	if x != nil {
		return x.MaxQuantity
	}
	return 0
}

func (x *InventorySlotRow) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *InventorySlotRow) GetPlanogramRevisionApplied() int32 {
	if x != nil {
		return x.PlanogramRevisionApplied
	}
	return 0
}

func (x *InventorySlotRow) GetCabinetCode() string {
	if x != nil {
		return x.CabinetCode
	}
	return ""
}

func (x *InventorySlotRow) GetCabinetIndex() int32 {
	if x != nil {
		return x.CabinetIndex
	}
	return 0
}

func (x *InventorySlotRow) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InventorySlotRow) GetProductSku() string {
	if x != nil {
		return x.ProductSku
	}
	return ""
}

func (x *InventorySlotRow) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *InventorySlotRow) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

type GetInventorySnapshotResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MachineId      string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ServerTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Slots          []*InventorySlotRow    `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
	Meta           *MachineResponseMeta   `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInventorySnapshotResponse) Reset() {
	*x = GetInventorySnapshotResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventorySnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventorySnapshotResponse) ProtoMessage() {}

func (x *GetInventorySnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventorySnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetInventorySnapshotResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventorySnapshotResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *GetInventorySnapshotResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetInventorySnapshotResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *GetInventorySnapshotResponse) GetSlots() []*InventorySlotRow {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *GetInventorySnapshotResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetPlanogramRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional override; must equal the authenticated machine or the call is rejected.
	MachineId     string `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanogramRequest) Reset() {
	*x = GetPlanogramRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanogramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanogramRequest) ProtoMessage() {}

func (x *GetPlanogramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanogramRequest.ProtoReflect.Descriptor instead.
func (*GetPlanogramRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlanogramRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type GetPlanogramResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MachineId      string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ServerTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Slots          []*InventorySlotRow    `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPlanogramResponse) Reset() {
	*x = GetPlanogramResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanogramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanogramResponse) ProtoMessage() {}

func (x *GetPlanogramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanogramResponse.ProtoReflect.Descriptor instead.
func (*GetPlanogramResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlanogramResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *GetPlanogramResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetPlanogramResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *GetPlanogramResponse) GetSlots() []*InventorySlotRow {
	if x != nil {
		return x.Slots
	}
	return nil
}

type RestockLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlanogramId    string                 `protobuf:"bytes,1,opt,name=planogram_id,json=planogramId,proto3" json:"planogram_id,omitempty"`
	SlotIndex      int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	QuantityBefore int32                  `protobuf:"varint,3,opt,name=quantity_before,json=quantityBefore,proto3" json:"quantity_before,omitempty"`
	QuantityAfter  int32                  `protobuf:"varint,4,opt,name=quantity_after,json=quantityAfter,proto3" json:"quantity_after,omitempty"`
	CabinetCode    string                 `protobuf:"bytes,5,opt,name=cabinet_code,json=cabinetCode,proto3" json:"cabinet_code,omitempty"`
	SlotCode       string                 `protobuf:"bytes,6,opt,name=slot_code,json=slotCode,proto3" json:"slot_code,omitempty"`
	ProductId      *string                `protobuf:"bytes,7,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestockLine) Reset() {
	*x = RestockLine{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockLine) ProtoMessage() {}

func (x *RestockLine) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockLine.ProtoReflect.Descriptor instead.
func (*RestockLine) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *RestockLine) GetPlanogramId() string {
	if x != nil {
		return x.PlanogramId
	}
	return ""
}

func (x *RestockLine) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *RestockLine) GetQuantityBefore() int32 {
	if x != nil {
		return x.QuantityBefore
	}
	return 0
}

func (x *RestockLine) GetQuantityAfter() int32 {
	if x != nil {
		return x.QuantityAfter
	}
	return 0
}

func (x *RestockLine) GetCabinetCode() string {
	if x != nil {
		return x.CabinetCode
	}
	return ""
}

func (x *RestockLine) GetSlotCode() string {
	if x != nil {
		return x.SlotCode
	}
	return ""
}

func (x *RestockLine) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

type SubmitRestockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Lines         []*RestockLine         `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRestockRequest) Reset() {
	*x = SubmitRestockRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRestockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRestockRequest) ProtoMessage() {}

func (x *SubmitRestockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRestockRequest.ProtoReflect.Descriptor instead.
func (*SubmitRestockRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitRestockRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitRestockRequest) GetLines() []*RestockLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SubmitRestockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	EventIds      []int64                `protobuf:"varint,2,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRestockResponse) Reset() {
	*x = SubmitRestockResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRestockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRestockResponse) ProtoMessage() {}

func (x *SubmitRestockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRestockResponse.ProtoReflect.Descriptor instead.
func (*SubmitRestockResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitRestockResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *SubmitRestockResponse) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type SubmitFillResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Lines         []*RestockLine         `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFillResultRequest) Reset() {
	*x = SubmitFillResultRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFillResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFillResultRequest) ProtoMessage() {}

func (x *SubmitFillResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFillResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitFillResultRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitFillResultRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitFillResultRequest) GetLines() []*RestockLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SubmitFillResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	EventIds      []int64                `protobuf:"varint,2,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFillResultResponse) Reset() {
	*x = SubmitFillResultResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFillResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFillResultResponse) ProtoMessage() {}

func (x *SubmitFillResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFillResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitFillResultResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitFillResultResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *SubmitFillResultResponse) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type AdjustmentLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlanogramId    string                 `protobuf:"bytes,1,opt,name=planogram_id,json=planogramId,proto3" json:"planogram_id,omitempty"`
	SlotIndex      int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	QuantityBefore int32                  `protobuf:"varint,3,opt,name=quantity_before,json=quantityBefore,proto3" json:"quantity_before,omitempty"`
	QuantityAfter  int32                  `protobuf:"varint,4,opt,name=quantity_after,json=quantityAfter,proto3" json:"quantity_after,omitempty"`
	ReasonCode     string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	CabinetCode    string                 `protobuf:"bytes,6,opt,name=cabinet_code,json=cabinetCode,proto3" json:"cabinet_code,omitempty"`
	SlotCode       string                 `protobuf:"bytes,7,opt,name=slot_code,json=slotCode,proto3" json:"slot_code,omitempty"`
	ProductId      *string                `protobuf:"bytes,8,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdjustmentLine) Reset() {
	*x = AdjustmentLine{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustmentLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustmentLine) ProtoMessage() {}

func (x *AdjustmentLine) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustmentLine.ProtoReflect.Descriptor instead.
func (*AdjustmentLine) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *AdjustmentLine) GetPlanogramId() string {
	if x != nil {
		return x.PlanogramId
	}
	return ""
}

func (x *AdjustmentLine) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *AdjustmentLine) GetQuantityBefore() int32 {
	if x != nil {
		return x.QuantityBefore
	}
	return 0
}

func (x *AdjustmentLine) GetQuantityAfter() int32 {
	if x != nil {
		return x.QuantityAfter
	}
	return 0
}

func (x *AdjustmentLine) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *AdjustmentLine) GetCabinetCode() string {
	if x != nil {
		return x.CabinetCode
	}
	return ""
}

func (x *AdjustmentLine) GetSlotCode() string {
	if x != nil {
		return x.SlotCode
	}
	return ""
}

func (x *AdjustmentLine) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

// reason must be one of: cycle_count, manual_adjustment, machine_reconcile (restock uses SubmitRestock).
type SubmitInventoryAdjustmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Lines         []*AdjustmentLine      `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInventoryAdjustmentRequest) Reset() {
	*x = SubmitInventoryAdjustmentRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInventoryAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInventoryAdjustmentRequest) ProtoMessage() {}

func (x *SubmitInventoryAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInventoryAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*SubmitInventoryAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitInventoryAdjustmentRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitInventoryAdjustmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SubmitInventoryAdjustmentRequest) GetLines() []*AdjustmentLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SubmitInventoryAdjustmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	EventIds      []int64                `protobuf:"varint,2,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInventoryAdjustmentResponse) Reset() {
	*x = SubmitInventoryAdjustmentResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInventoryAdjustmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInventoryAdjustmentResponse) ProtoMessage() {}

func (x *SubmitInventoryAdjustmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInventoryAdjustmentResponse.ProtoReflect.Descriptor instead.
func (*SubmitInventoryAdjustmentResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitInventoryAdjustmentResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *SubmitInventoryAdjustmentResponse) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type SubmitStockSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Lines         []*AdjustmentLine      `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitStockSnapshotRequest) Reset() {
	*x = SubmitStockSnapshotRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitStockSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitStockSnapshotRequest) ProtoMessage() {}

func (x *SubmitStockSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitStockSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SubmitStockSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitStockSnapshotRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitStockSnapshotRequest) GetLines() []*AdjustmentLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SubmitStockSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	EventIds      []int64                `protobuf:"varint,2,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitStockSnapshotResponse) Reset() {
	*x = SubmitStockSnapshotResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitStockSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitStockSnapshotResponse) ProtoMessage() {}

func (x *SubmitStockSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitStockSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SubmitStockSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitStockSnapshotResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *SubmitStockSnapshotResponse) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type ReportInventoryDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdempotencyContext    `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Meta          *MachineRequestMeta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Lines         []*AdjustmentLine      `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInventoryDeltaRequest) Reset() {
	*x = ReportInventoryDeltaRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInventoryDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInventoryDeltaRequest) ProtoMessage() {}

func (x *ReportInventoryDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInventoryDeltaRequest.ProtoReflect.Descriptor instead.
func (*ReportInventoryDeltaRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *ReportInventoryDeltaRequest) GetContext() *IdempotencyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReportInventoryDeltaRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReportInventoryDeltaRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportInventoryDeltaRequest) GetLines() []*AdjustmentLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ReportInventoryDeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replay        bool                   `protobuf:"varint,1,opt,name=replay,proto3" json:"replay,omitempty"`
	EventIds      []int64                `protobuf:"varint,2,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInventoryDeltaResponse) Reset() {
	*x = ReportInventoryDeltaResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInventoryDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInventoryDeltaResponse) ProtoMessage() {}

func (x *ReportInventoryDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInventoryDeltaResponse.ProtoReflect.Descriptor instead.
func (*ReportInventoryDeltaResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *ReportInventoryDeltaResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

func (x *ReportInventoryDeltaResponse) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *ReportInventoryDeltaResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AckInventorySyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineRequestMeta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SyncCursor    string                 `protobuf:"bytes,2,opt,name=sync_cursor,json=syncCursor,proto3" json:"sync_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckInventorySyncRequest) Reset() {
	*x = AckInventorySyncRequest{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckInventorySyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckInventorySyncRequest) ProtoMessage() {}

func (x *AckInventorySyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckInventorySyncRequest.ProtoReflect.Descriptor instead.
func (*AckInventorySyncRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *AckInventorySyncRequest) GetMeta() *MachineRequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AckInventorySyncRequest) GetSyncCursor() string {
	if x != nil {
		return x.SyncCursor
	}
	return ""
}

type AckInventorySyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MachineResponseMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckInventorySyncResponse) Reset() {
	*x = AckInventorySyncResponse{}
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckInventorySyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckInventorySyncResponse) ProtoMessage() {}

func (x *AckInventorySyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckInventorySyncResponse.ProtoReflect.Descriptor instead.
func (*AckInventorySyncResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *AckInventorySyncResponse) GetMeta() *MachineResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_avf_machine_v1_inventory_proto protoreflect.FileDescriptor

const file_avf_machine_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1eavf/machine/v1/inventory.proto\x12\x0eavf.machine.v1\x1a\x1bavf/machine/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x1bGetInventorySnapshotRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\"\xee\x03\n" +
	"\x10InventorySlotRow\x12!\n" +
	"\fplanogram_id\x18\x01 \x01(\tR\vplanogramId\x12%\n" +
	"\x0eplanogram_name\x18\x02 \x01(\tR\rplanogramName\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\x12)\n" +
	"\x10current_quantity\x18\x04 \x01(\x05R\x0fcurrentQuantity\x12!\n" +
	"\fmax_quantity\x18\x05 \x01(\x05R\vmaxQuantity\x12\x1f\n" +
	"\vprice_minor\x18\x06 \x01(\x03R\n" +
	"priceMinor\x12<\n" +
	"\x1aplanogram_revision_applied\x18\a \x01(\x05R\x18planogramRevisionApplied\x12!\n" +
	"\fcabinet_code\x18\b \x01(\tR\vcabinetCode\x12#\n" +
	"\rcabinet_index\x18\t \x01(\x05R\fcabinetIndex\x12\x1d\n" +
	"\n" +
	"product_id\x18\n" +
	" \x01(\tR\tproductId\x12\x1f\n" +
	"\vproduct_sku\x18\v \x01(\tR\n" +
	"productSku\x12!\n" +
	"\fproduct_name\x18\f \x01(\tR\vproductName\x12\x19\n" +
	"\bis_empty\x18\r \x01(\bR\aisEmpty\"\x94\x02\n" +
	"\x1cGetInventorySnapshotResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x126\n" +
	"\x05slots\x18\x04 \x03(\v2 .avf.machine.v1.InventorySlotRowR\x05slots\x127\n" +
	"\x04meta\x18\x05 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\"4\n" +
	"\x13GetPlanogramRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"\xd3\x01\n" +
	"\x14GetPlanogramResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x126\n" +
	"\x05slots\x18\x04 \x03(\v2 .avf.machine.v1.InventorySlotRowR\x05slots\"\x92\x02\n" +
	"\vRestockLine\x12!\n" +
	"\fplanogram_id\x18\x01 \x01(\tR\vplanogramId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\x12'\n" +
	"\x0fquantity_before\x18\x03 \x01(\x05R\x0equantityBefore\x12%\n" +
	"\x0equantity_after\x18\x04 \x01(\x05R\rquantityAfter\x12!\n" +
	"\fcabinet_code\x18\x05 \x01(\tR\vcabinetCode\x12\x1b\n" +
	"\tslot_code\x18\x06 \x01(\tR\bslotCode\x12\"\n" +
	"\n" +
	"product_id\x18\a \x01(\tH\x00R\tproductId\x88\x01\x01B\r\n" +
	"\v_product_id\"\x87\x01\n" +
	"\x14SubmitRestockRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x121\n" +
	"\x05lines\x18\x02 \x03(\v2\x1b.avf.machine.v1.RestockLineR\x05lines\"L\n" +
	"\x15SubmitRestockResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\x03R\beventIds\"\x8a\x01\n" +
	"\x17SubmitFillResultRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x121\n" +
	"\x05lines\x18\x02 \x03(\v2\x1b.avf.machine.v1.RestockLineR\x05lines\"O\n" +
	"\x18SubmitFillResultResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\x03R\beventIds\"\xb6\x02\n" +
	"\x0eAdjustmentLine\x12!\n" +
	"\fplanogram_id\x18\x01 \x01(\tR\vplanogramId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\x12'\n" +
	"\x0fquantity_before\x18\x03 \x01(\x05R\x0equantityBefore\x12%\n" +
	"\x0equantity_after\x18\x04 \x01(\x05R\rquantityAfter\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12!\n" +
	"\fcabinet_code\x18\x06 \x01(\tR\vcabinetCode\x12\x1b\n" +
	"\tslot_code\x18\a \x01(\tR\bslotCode\x12\"\n" +
	"\n" +
	"product_id\x18\b \x01(\tH\x00R\tproductId\x88\x01\x01B\r\n" +
	"\v_product_id\"\xae\x01\n" +
	" SubmitInventoryAdjustmentRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x124\n" +
	"\x05lines\x18\x03 \x03(\v2\x1e.avf.machine.v1.AdjustmentLineR\x05lines\"X\n" +
	"!SubmitInventoryAdjustmentResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\x03R\beventIds\"\x90\x01\n" +
	"\x1aSubmitStockSnapshotRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x124\n" +
	"\x05lines\x18\x02 \x03(\v2\x1e.avf.machine.v1.AdjustmentLineR\x05lines\"R\n" +
	"\x1bSubmitStockSnapshotResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\x03R\beventIds\"\xe1\x01\n" +
	"\x1bReportInventoryDeltaRequest\x12<\n" +
	"\acontext\x18\x01 \x01(\v2\".avf.machine.v1.IdempotencyContextR\acontext\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x124\n" +
	"\x05lines\x18\x04 \x03(\v2\x1e.avf.machine.v1.AdjustmentLineR\x05lines\"\x8c\x01\n" +
	"\x1cReportInventoryDeltaResponse\x12\x16\n" +
	"\x06replay\x18\x01 \x01(\bR\x06replay\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\x03R\beventIds\x127\n" +
	"\x04meta\x18\x03 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta\"r\n" +
	"\x17AckInventorySyncRequest\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".avf.machine.v1.MachineRequestMetaR\x04meta\x12\x1f\n" +
	"\vsync_cursor\x18\x02 \x01(\tR\n" +
	"syncCursor\"S\n" +
	"\x18AckInventorySyncResponse\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.avf.machine.v1.MachineResponseMetaR\x04meta2\xdc\b\n" +
	"\x17MachineInventoryService\x12o\n" +
	"\x12PushInventoryDelta\x12+.avf.machine.v1.ReportInventoryDeltaRequest\x1a,.avf.machine.v1.ReportInventoryDeltaResponse\x12q\n" +
	"\x14GetInventorySnapshot\x12+.avf.machine.v1.GetInventorySnapshotRequest\x1a,.avf.machine.v1.GetInventorySnapshotResponse\x12e\n" +
	"\x10AckInventorySync\x12'.avf.machine.v1.AckInventorySyncRequest\x1a(.avf.machine.v1.AckInventorySyncResponse\x12Y\n" +
	"\fGetPlanogram\x12#.avf.machine.v1.GetPlanogramRequest\x1a$.avf.machine.v1.GetPlanogramResponse\x12n\n" +
	"\x13SubmitStockSnapshot\x12*.avf.machine.v1.SubmitStockSnapshotRequest\x1a+.avf.machine.v1.SubmitStockSnapshotResponse\x12e\n" +
	"\x10SubmitFillResult\x12'.avf.machine.v1.SubmitFillResultRequest\x1a(.avf.machine.v1.SubmitFillResultResponse\x12e\n" +
	"\x10SubmitFillReport\x12'.avf.machine.v1.SubmitFillResultRequest\x1a(.avf.machine.v1.SubmitFillResultResponse\x12\\\n" +
	"\rSubmitRestock\x12$.avf.machine.v1.SubmitRestockRequest\x1a%.avf.machine.v1.SubmitRestockResponse\x12\x80\x01\n" +
	"\x19SubmitInventoryAdjustment\x120.avf.machine.v1.SubmitInventoryAdjustmentRequest\x1a1.avf.machine.v1.SubmitInventoryAdjustmentResponse\x12|\n" +
	"\x15SubmitStockAdjustment\x120.avf.machine.v1.SubmitInventoryAdjustmentRequest\x1a1.avf.machine.v1.SubmitInventoryAdjustmentResponseB?Z=github.com/avf/avf-vending-api/proto/avf/machine/v1;machinev1b\x06proto3"

var (
	file_avf_machine_v1_inventory_proto_rawDescOnce sync.Once
	file_avf_machine_v1_inventory_proto_rawDescData []byte
)

func file_avf_machine_v1_inventory_proto_rawDescGZIP() []byte {
	file_avf_machine_v1_inventory_proto_rawDescOnce.Do(func() {
		file_avf_machine_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_machine_v1_inventory_proto_rawDesc), len(file_avf_machine_v1_inventory_proto_rawDesc)))
	})
	return file_avf_machine_v1_inventory_proto_rawDescData
}

var file_avf_machine_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_avf_machine_v1_inventory_proto_goTypes = []any{
	(*GetInventorySnapshotRequest)(nil),       // 0: avf.machine.v1.GetInventorySnapshotRequest
	(*InventorySlotRow)(nil),                  // 1: avf.machine.v1.InventorySlotRow
	(*GetInventorySnapshotResponse)(nil),      // 2: avf.machine.v1.GetInventorySnapshotResponse
	(*GetPlanogramRequest)(nil),               // 3: avf.machine.v1.GetPlanogramRequest
	(*GetPlanogramResponse)(nil),              // 4: avf.machine.v1.GetPlanogramResponse
	(*RestockLine)(nil),                       // 5: avf.machine.v1.RestockLine
	(*SubmitRestockRequest)(nil),              // 6: avf.machine.v1.SubmitRestockRequest
	(*SubmitRestockResponse)(nil),             // 7: avf.machine.v1.SubmitRestockResponse
	(*SubmitFillResultRequest)(nil),           // 8: avf.machine.v1.SubmitFillResultRequest
	(*SubmitFillResultResponse)(nil),          // 9: avf.machine.v1.SubmitFillResultResponse
	(*AdjustmentLine)(nil),                    // 10: avf.machine.v1.AdjustmentLine
	(*SubmitInventoryAdjustmentRequest)(nil),  // 11: avf.machine.v1.SubmitInventoryAdjustmentRequest
	(*SubmitInventoryAdjustmentResponse)(nil), // 12: avf.machine.v1.SubmitInventoryAdjustmentResponse
	(*SubmitStockSnapshotRequest)(nil),        // 13: avf.machine.v1.SubmitStockSnapshotRequest
	(*SubmitStockSnapshotResponse)(nil),       // 14: avf.machine.v1.SubmitStockSnapshotResponse
	(*ReportInventoryDeltaRequest)(nil),       // 15: avf.machine.v1.ReportInventoryDeltaRequest
	(*ReportInventoryDeltaResponse)(nil),      // 16: avf.machine.v1.ReportInventoryDeltaResponse
	(*AckInventorySyncRequest)(nil),           // 17: avf.machine.v1.AckInventorySyncRequest
	(*AckInventorySyncResponse)(nil),          // 18: avf.machine.v1.AckInventorySyncResponse
	(*MachineRequestMeta)(nil),                // 19: avf.machine.v1.MachineRequestMeta
	(*timestamppb.Timestamp)(nil),             // 20: google.protobuf.Timestamp
	(*MachineResponseMeta)(nil),               // 21: avf.machine.v1.MachineResponseMeta
	(*IdempotencyContext)(nil),                // 22: avf.machine.v1.IdempotencyContext
}
var file_avf_machine_v1_inventory_proto_depIdxs = []int32{
	19, // 0: avf.machine.v1.GetInventorySnapshotRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	20, // 1: avf.machine.v1.GetInventorySnapshotResponse.server_time:type_name -> google.protobuf.Timestamp
	1,  // 2: avf.machine.v1.GetInventorySnapshotResponse.slots:type_name -> avf.machine.v1.InventorySlotRow
	21, // 3: avf.machine.v1.GetInventorySnapshotResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	20, // 4: avf.machine.v1.GetPlanogramResponse.server_time:type_name -> google.protobuf.Timestamp
	1,  // 5: avf.machine.v1.GetPlanogramResponse.slots:type_name -> avf.machine.v1.InventorySlotRow
	22, // 6: avf.machine.v1.SubmitRestockRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	5,  // 7: avf.machine.v1.SubmitRestockRequest.lines:type_name -> avf.machine.v1.RestockLine
	22, // 8: avf.machine.v1.SubmitFillResultRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	5,  // 9: avf.machine.v1.SubmitFillResultRequest.lines:type_name -> avf.machine.v1.RestockLine
	22, // 10: avf.machine.v1.SubmitInventoryAdjustmentRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	10, // 11: avf.machine.v1.SubmitInventoryAdjustmentRequest.lines:type_name -> avf.machine.v1.AdjustmentLine
	22, // 12: avf.machine.v1.SubmitStockSnapshotRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	10, // 13: avf.machine.v1.SubmitStockSnapshotRequest.lines:type_name -> avf.machine.v1.AdjustmentLine
	22, // 14: avf.machine.v1.ReportInventoryDeltaRequest.context:type_name -> avf.machine.v1.IdempotencyContext
	19, // 15: avf.machine.v1.ReportInventoryDeltaRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	10, // 16: avf.machine.v1.ReportInventoryDeltaRequest.lines:type_name -> avf.machine.v1.AdjustmentLine
	21, // 17: avf.machine.v1.ReportInventoryDeltaResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	19, // 18: avf.machine.v1.AckInventorySyncRequest.meta:type_name -> avf.machine.v1.MachineRequestMeta
	21, // 19: avf.machine.v1.AckInventorySyncResponse.meta:type_name -> avf.machine.v1.MachineResponseMeta
	15, // 20: avf.machine.v1.MachineInventoryService.PushInventoryDelta:input_type -> avf.machine.v1.ReportInventoryDeltaRequest
	0,  // 21: avf.machine.v1.MachineInventoryService.GetInventorySnapshot:input_type -> avf.machine.v1.GetInventorySnapshotRequest
	17, // 22: avf.machine.v1.MachineInventoryService.AckInventorySync:input_type -> avf.machine.v1.AckInventorySyncRequest
	3,  // 23: avf.machine.v1.MachineInventoryService.GetPlanogram:input_type -> avf.machine.v1.GetPlanogramRequest
	13, // 24: avf.machine.v1.MachineInventoryService.SubmitStockSnapshot:input_type -> avf.machine.v1.SubmitStockSnapshotRequest
	8,  // 25: avf.machine.v1.MachineInventoryService.SubmitFillResult:input_type -> avf.machine.v1.SubmitFillResultRequest
	8,  // 26: avf.machine.v1.MachineInventoryService.SubmitFillReport:input_type -> avf.machine.v1.SubmitFillResultRequest
	6,  // 27: avf.machine.v1.MachineInventoryService.SubmitRestock:input_type -> avf.machine.v1.SubmitRestockRequest
	11, // 28: avf.machine.v1.MachineInventoryService.SubmitInventoryAdjustment:input_type -> avf.machine.v1.SubmitInventoryAdjustmentRequest
	11, // 29: avf.machine.v1.MachineInventoryService.SubmitStockAdjustment:input_type -> avf.machine.v1.SubmitInventoryAdjustmentRequest
	16, // 30: avf.machine.v1.MachineInventoryService.PushInventoryDelta:output_type -> avf.machine.v1.ReportInventoryDeltaResponse
	2,  // 31: avf.machine.v1.MachineInventoryService.GetInventorySnapshot:output_type -> avf.machine.v1.GetInventorySnapshotResponse
	18, // 32: avf.machine.v1.MachineInventoryService.AckInventorySync:output_type -> avf.machine.v1.AckInventorySyncResponse
	4,  // 33: avf.machine.v1.MachineInventoryService.GetPlanogram:output_type -> avf.machine.v1.GetPlanogramResponse
	14, // 34: avf.machine.v1.MachineInventoryService.SubmitStockSnapshot:output_type -> avf.machine.v1.SubmitStockSnapshotResponse
	9,  // 35: avf.machine.v1.MachineInventoryService.SubmitFillResult:output_type -> avf.machine.v1.SubmitFillResultResponse
	9,  // 36: avf.machine.v1.MachineInventoryService.SubmitFillReport:output_type -> avf.machine.v1.SubmitFillResultResponse
	7,  // 37: avf.machine.v1.MachineInventoryService.SubmitRestock:output_type -> avf.machine.v1.SubmitRestockResponse
	12, // 38: avf.machine.v1.MachineInventoryService.SubmitInventoryAdjustment:output_type -> avf.machine.v1.SubmitInventoryAdjustmentResponse
	12, // 39: avf.machine.v1.MachineInventoryService.SubmitStockAdjustment:output_type -> avf.machine.v1.SubmitInventoryAdjustmentResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_avf_machine_v1_inventory_proto_init() }
func file_avf_machine_v1_inventory_proto_init() {
	if File_avf_machine_v1_inventory_proto != nil {
		return
	}
	file_avf_machine_v1_common_proto_init()
	file_avf_machine_v1_inventory_proto_msgTypes[5].OneofWrappers = []any{}
	file_avf_machine_v1_inventory_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_machine_v1_inventory_proto_rawDesc), len(file_avf_machine_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avf_machine_v1_inventory_proto_goTypes,
		DependencyIndexes: file_avf_machine_v1_inventory_proto_depIdxs,
		MessageInfos:      file_avf_machine_v1_inventory_proto_msgTypes,
	}.Build()
	File_avf_machine_v1_inventory_proto = out.File
	file_avf_machine_v1_inventory_proto_goTypes = nil
	file_avf_machine_v1_inventory_proto_depIdxs = nil
}
