// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: avf/machine/v1/inventory.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineInventoryService_PushInventoryDelta_FullMethodName        = "/avf.machine.v1.MachineInventoryService/PushInventoryDelta"
	MachineInventoryService_GetInventorySnapshot_FullMethodName      = "/avf.machine.v1.MachineInventoryService/GetInventorySnapshot"
	MachineInventoryService_AckInventorySync_FullMethodName          = "/avf.machine.v1.MachineInventoryService/AckInventorySync"
	MachineInventoryService_GetPlanogram_FullMethodName              = "/avf.machine.v1.MachineInventoryService/GetPlanogram"
	MachineInventoryService_SubmitStockSnapshot_FullMethodName       = "/avf.machine.v1.MachineInventoryService/SubmitStockSnapshot"
	MachineInventoryService_SubmitFillResult_FullMethodName          = "/avf.machine.v1.MachineInventoryService/SubmitFillResult"
	MachineInventoryService_SubmitFillReport_FullMethodName          = "/avf.machine.v1.MachineInventoryService/SubmitFillReport"
	MachineInventoryService_SubmitRestock_FullMethodName             = "/avf.machine.v1.MachineInventoryService/SubmitRestock"
	MachineInventoryService_SubmitInventoryAdjustment_FullMethodName = "/avf.machine.v1.MachineInventoryService/SubmitInventoryAdjustment"
	MachineInventoryService_SubmitStockAdjustment_FullMethodName     = "/avf.machine.v1.MachineInventoryService/SubmitStockAdjustment"
)

// MachineInventoryServiceClient is the client API for MachineInventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineInventoryService is the kiosk inventory API (Machine JWT). machine_id is always the authenticated principal.
type MachineInventoryServiceClient interface {
	PushInventoryDelta(ctx context.Context, in *ReportInventoryDeltaRequest, opts ...grpc.CallOption) (*ReportInventoryDeltaResponse, error)
	GetInventorySnapshot(ctx context.Context, in *GetInventorySnapshotRequest, opts ...grpc.CallOption) (*GetInventorySnapshotResponse, error)
	AckInventorySync(ctx context.Context, in *AckInventorySyncRequest, opts ...grpc.CallOption) (*AckInventorySyncResponse, error)
	GetPlanogram(ctx context.Context, in *GetPlanogramRequest, opts ...grpc.CallOption) (*GetPlanogramResponse, error)
	SubmitStockSnapshot(ctx context.Context, in *SubmitStockSnapshotRequest, opts ...grpc.CallOption) (*SubmitStockSnapshotResponse, error)
	SubmitFillResult(ctx context.Context, in *SubmitFillResultRequest, opts ...grpc.CallOption) (*SubmitFillResultResponse, error)
	// SubmitFillReport is an alias of SubmitFillResult (direct request/response; spec-native name).
	SubmitFillReport(ctx context.Context, in *SubmitFillResultRequest, opts ...grpc.CallOption) (*SubmitFillResultResponse, error)
	SubmitRestock(ctx context.Context, in *SubmitRestockRequest, opts ...grpc.CallOption) (*SubmitRestockResponse, error)
	SubmitInventoryAdjustment(ctx context.Context, in *SubmitInventoryAdjustmentRequest, opts ...grpc.CallOption) (*SubmitInventoryAdjustmentResponse, error)
	// SubmitStockAdjustment is an alias of SubmitInventoryAdjustment (spec-native name).
	SubmitStockAdjustment(ctx context.Context, in *SubmitInventoryAdjustmentRequest, opts ...grpc.CallOption) (*SubmitInventoryAdjustmentResponse, error)
}

type machineInventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineInventoryServiceClient(cc grpc.ClientConnInterface) MachineInventoryServiceClient {
	return &machineInventoryServiceClient{cc}
}

func (c *machineInventoryServiceClient) PushInventoryDelta(ctx context.Context, in *ReportInventoryDeltaRequest, opts ...grpc.CallOption) (*ReportInventoryDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportInventoryDeltaResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_PushInventoryDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) GetInventorySnapshot(ctx context.Context, in *GetInventorySnapshotRequest, opts ...grpc.CallOption) (*GetInventorySnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventorySnapshotResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_GetInventorySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) AckInventorySync(ctx context.Context, in *AckInventorySyncRequest, opts ...grpc.CallOption) (*AckInventorySyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckInventorySyncResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_AckInventorySync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) GetPlanogram(ctx context.Context, in *GetPlanogramRequest, opts ...grpc.CallOption) (*GetPlanogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanogramResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_GetPlanogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) SubmitStockSnapshot(ctx context.Context, in *SubmitStockSnapshotRequest, opts ...grpc.CallOption) (*SubmitStockSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitStockSnapshotResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_SubmitStockSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) SubmitFillResult(ctx context.Context, in *SubmitFillResultRequest, opts ...grpc.CallOption) (*SubmitFillResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFillResultResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_SubmitFillResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) SubmitFillReport(ctx context.Context, in *SubmitFillResultRequest, opts ...grpc.CallOption) (*SubmitFillResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFillResultResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_SubmitFillReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) SubmitRestock(ctx context.Context, in *SubmitRestockRequest, opts ...grpc.CallOption) (*SubmitRestockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRestockResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_SubmitRestock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) SubmitInventoryAdjustment(ctx context.Context, in *SubmitInventoryAdjustmentRequest, opts ...grpc.CallOption) (*SubmitInventoryAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInventoryAdjustmentResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_SubmitInventoryAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInventoryServiceClient) SubmitStockAdjustment(ctx context.Context, in *SubmitInventoryAdjustmentRequest, opts ...grpc.CallOption) (*SubmitInventoryAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInventoryAdjustmentResponse)
	err := c.cc.Invoke(ctx, MachineInventoryService_SubmitStockAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineInventoryServiceServer is the server API for MachineInventoryService service.
// All implementations must embed UnimplementedMachineInventoryServiceServer
// for forward compatibility.
//
// MachineInventoryService is the kiosk inventory API (Machine JWT). machine_id is always the authenticated principal.
type MachineInventoryServiceServer interface {
	PushInventoryDelta(context.Context, *ReportInventoryDeltaRequest) (*ReportInventoryDeltaResponse, error)
	GetInventorySnapshot(context.Context, *GetInventorySnapshotRequest) (*GetInventorySnapshotResponse, error)
	AckInventorySync(context.Context, *AckInventorySyncRequest) (*AckInventorySyncResponse, error)
	GetPlanogram(context.Context, *GetPlanogramRequest) (*GetPlanogramResponse, error)
	SubmitStockSnapshot(context.Context, *SubmitStockSnapshotRequest) (*SubmitStockSnapshotResponse, error)
	SubmitFillResult(context.Context, *SubmitFillResultRequest) (*SubmitFillResultResponse, error)
	// SubmitFillReport is an alias of SubmitFillResult (direct request/response; spec-native name).
	SubmitFillReport(context.Context, *SubmitFillResultRequest) (*SubmitFillResultResponse, error)
	SubmitRestock(context.Context, *SubmitRestockRequest) (*SubmitRestockResponse, error)
	SubmitInventoryAdjustment(context.Context, *SubmitInventoryAdjustmentRequest) (*SubmitInventoryAdjustmentResponse, error)
	// SubmitStockAdjustment is an alias of SubmitInventoryAdjustment (spec-native name).
	SubmitStockAdjustment(context.Context, *SubmitInventoryAdjustmentRequest) (*SubmitInventoryAdjustmentResponse, error)
	mustEmbedUnimplementedMachineInventoryServiceServer()
}

// UnimplementedMachineInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineInventoryServiceServer struct{}

func (UnimplementedMachineInventoryServiceServer) PushInventoryDelta(context.Context, *ReportInventoryDeltaRequest) (*ReportInventoryDeltaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushInventoryDelta not implemented")
}
func (UnimplementedMachineInventoryServiceServer) GetInventorySnapshot(context.Context, *GetInventorySnapshotRequest) (*GetInventorySnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventorySnapshot not implemented")
}
func (UnimplementedMachineInventoryServiceServer) AckInventorySync(context.Context, *AckInventorySyncRequest) (*AckInventorySyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckInventorySync not implemented")
}
func (UnimplementedMachineInventoryServiceServer) GetPlanogram(context.Context, *GetPlanogramRequest) (*GetPlanogramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanogram not implemented")
}
func (UnimplementedMachineInventoryServiceServer) SubmitStockSnapshot(context.Context, *SubmitStockSnapshotRequest) (*SubmitStockSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitStockSnapshot not implemented")
}
func (UnimplementedMachineInventoryServiceServer) SubmitFillResult(context.Context, *SubmitFillResultRequest) (*SubmitFillResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFillResult not implemented")
}
func (UnimplementedMachineInventoryServiceServer) SubmitFillReport(context.Context, *SubmitFillResultRequest) (*SubmitFillResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFillReport not implemented")
}
func (UnimplementedMachineInventoryServiceServer) SubmitRestock(context.Context, *SubmitRestockRequest) (*SubmitRestockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRestock not implemented")
}
func (UnimplementedMachineInventoryServiceServer) SubmitInventoryAdjustment(context.Context, *SubmitInventoryAdjustmentRequest) (*SubmitInventoryAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInventoryAdjustment not implemented")
}
func (UnimplementedMachineInventoryServiceServer) SubmitStockAdjustment(context.Context, *SubmitInventoryAdjustmentRequest) (*SubmitInventoryAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitStockAdjustment not implemented")
}
func (UnimplementedMachineInventoryServiceServer) mustEmbedUnimplementedMachineInventoryServiceServer() {
}
func (UnimplementedMachineInventoryServiceServer) testEmbeddedByValue() {}

// UnsafeMachineInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineInventoryServiceServer will
// result in compilation errors.
type UnsafeMachineInventoryServiceServer interface {
	mustEmbedUnimplementedMachineInventoryServiceServer()
}

func RegisterMachineInventoryServiceServer(s grpc.ServiceRegistrar, srv MachineInventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineInventoryService_ServiceDesc, srv)
}

func _MachineInventoryService_PushInventoryDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInventoryDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).PushInventoryDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_PushInventoryDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).PushInventoryDelta(ctx, req.(*ReportInventoryDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_GetInventorySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventorySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).GetInventorySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_GetInventorySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).GetInventorySnapshot(ctx, req.(*GetInventorySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_AckInventorySync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckInventorySyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).AckInventorySync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_AckInventorySync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).AckInventorySync(ctx, req.(*AckInventorySyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_GetPlanogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).GetPlanogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_GetPlanogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).GetPlanogram(ctx, req.(*GetPlanogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_SubmitStockSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitStockSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).SubmitStockSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_SubmitStockSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).SubmitStockSnapshot(ctx, req.(*SubmitStockSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_SubmitFillResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFillResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).SubmitFillResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_SubmitFillResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).SubmitFillResult(ctx, req.(*SubmitFillResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_SubmitFillReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFillResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).SubmitFillReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_SubmitFillReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).SubmitFillReport(ctx, req.(*SubmitFillResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_SubmitRestock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRestockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).SubmitRestock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_SubmitRestock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).SubmitRestock(ctx, req.(*SubmitRestockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_SubmitInventoryAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInventoryAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).SubmitInventoryAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_SubmitInventoryAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).SubmitInventoryAdjustment(ctx, req.(*SubmitInventoryAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInventoryService_SubmitStockAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInventoryAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInventoryServiceServer).SubmitStockAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInventoryService_SubmitStockAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInventoryServiceServer).SubmitStockAdjustment(ctx, req.(*SubmitInventoryAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineInventoryService_ServiceDesc is the grpc.ServiceDesc for MachineInventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineInventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineInventoryService",
	HandlerType: (*MachineInventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushInventoryDelta",
			Handler:    _MachineInventoryService_PushInventoryDelta_Handler,
		},
		{
			MethodName: "GetInventorySnapshot",
			Handler:    _MachineInventoryService_GetInventorySnapshot_Handler,
		},
		{
			MethodName: "AckInventorySync",
			Handler:    _MachineInventoryService_AckInventorySync_Handler,
		},
		{
			MethodName: "GetPlanogram",
			Handler:    _MachineInventoryService_GetPlanogram_Handler,
		},
		{
			MethodName: "SubmitStockSnapshot",
			Handler:    _MachineInventoryService_SubmitStockSnapshot_Handler,
		},
		{
			MethodName: "SubmitFillResult",
			Handler:    _MachineInventoryService_SubmitFillResult_Handler,
		},
		{
			MethodName: "SubmitFillReport",
			Handler:    _MachineInventoryService_SubmitFillReport_Handler,
		},
		{
			MethodName: "SubmitRestock",
			Handler:    _MachineInventoryService_SubmitRestock_Handler,
		},
		{
			MethodName: "SubmitInventoryAdjustment",
			Handler:    _MachineInventoryService_SubmitInventoryAdjustment_Handler,
		},
		{
			MethodName: "SubmitStockAdjustment",
			Handler:    _MachineInventoryService_SubmitStockAdjustment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/inventory.proto",
}
