// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avf/machine/v1/machine_activation.proto

package machinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceFingerprint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AndroidId      string                 `protobuf:"bytes,1,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	SerialNumber   string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Manufacturer   string                 `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	PackageName    string                 `protobuf:"bytes,5,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	VersionName    string                 `protobuf:"bytes,6,opt,name=version_name,json=versionName,proto3" json:"version_name,omitempty"`
	VersionCode    int32                  `protobuf:"varint,7,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	AndroidSerial  string                 `protobuf:"bytes,8,opt,name=android_serial,json=androidSerial,proto3" json:"android_serial,omitempty"`
	BoardSerial    string                 `protobuf:"bytes,9,opt,name=board_serial,json=boardSerial,proto3" json:"board_serial,omitempty"`
	DeviceSerial   string                 `protobuf:"bytes,10,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	SimSerial      string                 `protobuf:"bytes,11,opt,name=sim_serial,json=simSerial,proto3" json:"sim_serial,omitempty"`
	SimIccid       string                 `protobuf:"bytes,12,opt,name=sim_iccid,json=simIccid,proto3" json:"sim_iccid,omitempty"`
	SimOperator    string                 `protobuf:"bytes,13,opt,name=sim_operator,json=simOperator,proto3" json:"sim_operator,omitempty"`
	SimCountryIso  string                 `protobuf:"bytes,14,opt,name=sim_country_iso,json=simCountryIso,proto3" json:"sim_country_iso,omitempty"`
	Brand          string                 `protobuf:"bytes,15,opt,name=brand,proto3" json:"brand,omitempty"`
	DeviceModel    string                 `protobuf:"bytes,16,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	Hardware       string                 `protobuf:"bytes,17,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Product        string                 `protobuf:"bytes,18,opt,name=product,proto3" json:"product,omitempty"`
	AndroidRelease string                 `protobuf:"bytes,19,opt,name=android_release,json=androidRelease,proto3" json:"android_release,omitempty"`
	SdkInt         int32                  `protobuf:"varint,20,opt,name=sdk_int,json=sdkInt,proto3" json:"sdk_int,omitempty"`
	AppBuildSha    string                 `protobuf:"bytes,21,opt,name=app_build_sha,json=appBuildSha,proto3" json:"app_build_sha,omitempty"`
	BootId         string                 `protobuf:"bytes,22,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	NetworkType    string                 `protobuf:"bytes,23,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	NetworkState   string                 `protobuf:"bytes,24,opt,name=network_state,json=networkState,proto3" json:"network_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceFingerprint) Reset() {
	*x = DeviceFingerprint{}
	mi := &file_avf_machine_v1_machine_activation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFingerprint) ProtoMessage() {}

func (x *DeviceFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_machine_activation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFingerprint.ProtoReflect.Descriptor instead.
func (*DeviceFingerprint) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_machine_activation_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceFingerprint) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *DeviceFingerprint) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *DeviceFingerprint) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceFingerprint) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceFingerprint) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *DeviceFingerprint) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *DeviceFingerprint) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *DeviceFingerprint) GetAndroidSerial() string {
	if x != nil {
		return x.AndroidSerial
	}
	return ""
}

func (x *DeviceFingerprint) GetBoardSerial() string {
	if x != nil {
		return x.BoardSerial
	}
	return ""
}

func (x *DeviceFingerprint) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *DeviceFingerprint) GetSimSerial() string {
	if x != nil {
		return x.SimSerial
	}
	return ""
}

func (x *DeviceFingerprint) GetSimIccid() string {
	if x != nil {
		return x.SimIccid
	}
	return ""
}

func (x *DeviceFingerprint) GetSimOperator() string {
	if x != nil {
		return x.SimOperator
	}
	return ""
}

func (x *DeviceFingerprint) GetSimCountryIso() string {
	if x != nil {
		return x.SimCountryIso
	}
	return ""
}

func (x *DeviceFingerprint) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DeviceFingerprint) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceFingerprint) GetHardware() string {
	if x != nil {
		return x.Hardware
	}
	return ""
}

func (x *DeviceFingerprint) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *DeviceFingerprint) GetAndroidRelease() string {
	if x != nil {
		return x.AndroidRelease
	}
	return ""
}

func (x *DeviceFingerprint) GetSdkInt() int32 {
	if x != nil {
		return x.SdkInt
	}
	return 0
}

func (x *DeviceFingerprint) GetAppBuildSha() string {
	if x != nil {
		return x.AppBuildSha
	}
	return ""
}

func (x *DeviceFingerprint) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *DeviceFingerprint) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *DeviceFingerprint) GetNetworkState() string {
	if x != nil {
		return x.NetworkState
	}
	return ""
}

type ClaimActivationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivationCode    string                 `protobuf:"bytes,1,opt,name=activation_code,json=activationCode,proto3" json:"activation_code,omitempty"`
	DeviceFingerprint *DeviceFingerprint     `protobuf:"bytes,2,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClaimActivationRequest) Reset() {
	*x = ClaimActivationRequest{}
	mi := &file_avf_machine_v1_machine_activation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimActivationRequest) ProtoMessage() {}

func (x *ClaimActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_machine_activation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimActivationRequest.ProtoReflect.Descriptor instead.
func (*ClaimActivationRequest) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_machine_activation_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimActivationRequest) GetActivationCode() string {
	if x != nil {
		return x.ActivationCode
	}
	return ""
}

func (x *ClaimActivationRequest) GetDeviceFingerprint() *DeviceFingerprint {
	if x != nil {
		return x.DeviceFingerprint
	}
	return nil
}

type ClaimActivationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MachineId             string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	SiteId                string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	MachineName           string                 `protobuf:"bytes,4,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`
	AccessToken           string                 `protobuf:"bytes,5,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	MqttBrokerUrl         string                 `protobuf:"bytes,9,opt,name=mqtt_broker_url,json=mqttBrokerUrl,proto3" json:"mqtt_broker_url,omitempty"`
	MqttTopicPrefix       string                 `protobuf:"bytes,10,opt,name=mqtt_topic_prefix,json=mqttTopicPrefix,proto3" json:"mqtt_topic_prefix,omitempty"`
	// "enterprise" or "legacy"; must match server MQTT_TOPIC_LAYOUT.
	MqttTopicLayout   string `protobuf:"bytes,13,opt,name=mqtt_topic_layout,json=mqttTopicLayout,proto3" json:"mqtt_topic_layout,omitempty"`
	BootstrapHttpPath string `protobuf:"bytes,11,opt,name=bootstrap_http_path,json=bootstrapHttpPath,proto3" json:"bootstrap_http_path,omitempty"`
	BootstrapRequired bool   `protobuf:"varint,12,opt,name=bootstrap_required,json=bootstrapRequired,proto3" json:"bootstrap_required,omitempty"`
	// Per-machine broker credentials (returned once on claim when EMQX provisioning is enabled).
	MqttUsername string `protobuf:"bytes,14,opt,name=mqtt_username,json=mqttUsername,proto3" json:"mqtt_username,omitempty"`
	MqttPassword string `protobuf:"bytes,15,opt,name=mqtt_password,json=mqttPassword,proto3" json:"mqtt_password,omitempty"`
	// Active machine_device_attachments row created or reused during claim.
	DeviceAttachmentId string `protobuf:"bytes,16,opt,name=device_attachment_id,json=deviceAttachmentId,proto3" json:"device_attachment_id,omitempty"`
	// Human-facing machine code printed on the physical machine, e.g. AVF000000.
	// Runtime authorization still uses machine_id UUID.
	MachineCode   string `protobuf:"bytes,17,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimActivationResponse) Reset() {
	*x = ClaimActivationResponse{}
	mi := &file_avf_machine_v1_machine_activation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimActivationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimActivationResponse) ProtoMessage() {}

func (x *ClaimActivationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_machine_v1_machine_activation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimActivationResponse.ProtoReflect.Descriptor instead.
func (*ClaimActivationResponse) Descriptor() ([]byte, []int) {
	return file_avf_machine_v1_machine_activation_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimActivationResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ClaimActivationResponse) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ClaimActivationResponse) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *ClaimActivationResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ClaimActivationResponse) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *ClaimActivationResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ClaimActivationResponse) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

func (x *ClaimActivationResponse) GetMqttBrokerUrl() string {
	if x != nil {
		return x.MqttBrokerUrl
	}
	return ""
}

func (x *ClaimActivationResponse) GetMqttTopicPrefix() string {
	if x != nil {
		return x.MqttTopicPrefix
	}
	return ""
}

func (x *ClaimActivationResponse) GetMqttTopicLayout() string {
	if x != nil {
		return x.MqttTopicLayout
	}
	return ""
}

func (x *ClaimActivationResponse) GetBootstrapHttpPath() string {
	if x != nil {
		return x.BootstrapHttpPath
	}
	return ""
}

func (x *ClaimActivationResponse) GetBootstrapRequired() bool {
	if x != nil {
		return x.BootstrapRequired
	}
	return false
}

func (x *ClaimActivationResponse) GetMqttUsername() string {
	if x != nil {
		return x.MqttUsername
	}
	return ""
}

func (x *ClaimActivationResponse) GetMqttPassword() string {
	if x != nil {
		return x.MqttPassword
	}
	return ""
}

func (x *ClaimActivationResponse) GetDeviceAttachmentId() string {
	if x != nil {
		return x.DeviceAttachmentId
	}
	return ""
}

func (x *ClaimActivationResponse) GetMachineCode() string {
	if x != nil {
		return x.MachineCode
	}
	return ""
}

var File_avf_machine_v1_machine_activation_proto protoreflect.FileDescriptor

const file_avf_machine_v1_machine_activation_proto_rawDesc = "" +
	"\n" +
	"'avf/machine/v1/machine_activation.proto\x12\x0eavf.machine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x06\n" +
	"\x11DeviceFingerprint\x12\x1d\n" +
	"\n" +
	"android_id\x18\x01 \x01(\tR\tandroidId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\"\n" +
	"\fmanufacturer\x18\x03 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12!\n" +
	"\fpackage_name\x18\x05 \x01(\tR\vpackageName\x12!\n" +
	"\fversion_name\x18\x06 \x01(\tR\vversionName\x12!\n" +
	"\fversion_code\x18\a \x01(\x05R\vversionCode\x12%\n" +
	"\x0eandroid_serial\x18\b \x01(\tR\randroidSerial\x12!\n" +
	"\fboard_serial\x18\t \x01(\tR\vboardSerial\x12#\n" +
	"\rdevice_serial\x18\n" +
	" \x01(\tR\fdeviceSerial\x12\x1d\n" +
	"\n" +
	"sim_serial\x18\v \x01(\tR\tsimSerial\x12\x1b\n" +
	"\tsim_iccid\x18\f \x01(\tR\bsimIccid\x12!\n" +
	"\fsim_operator\x18\r \x01(\tR\vsimOperator\x12&\n" +
	"\x0fsim_country_iso\x18\x0e \x01(\tR\rsimCountryIso\x12\x14\n" +
	"\x05brand\x18\x0f \x01(\tR\x05brand\x12!\n" +
	"\fdevice_model\x18\x10 \x01(\tR\vdeviceModel\x12\x1a\n" +
	"\bhardware\x18\x11 \x01(\tR\bhardware\x12\x18\n" +
	"\aproduct\x18\x12 \x01(\tR\aproduct\x12'\n" +
	"\x0fandroid_release\x18\x13 \x01(\tR\x0eandroidRelease\x12\x17\n" +
	"\asdk_int\x18\x14 \x01(\x05R\x06sdkInt\x12\"\n" +
	"\rapp_build_sha\x18\x15 \x01(\tR\vappBuildSha\x12\x17\n" +
	"\aboot_id\x18\x16 \x01(\tR\x06bootId\x12!\n" +
	"\fnetwork_type\x18\x17 \x01(\tR\vnetworkType\x12#\n" +
	"\rnetwork_state\x18\x18 \x01(\tR\fnetworkState\"\x93\x01\n" +
	"\x16ClaimActivationRequest\x12'\n" +
	"\x0factivation_code\x18\x01 \x01(\tR\x0eactivationCode\x12P\n" +
	"\x12device_fingerprint\x18\x02 \x01(\v2!.avf.machine.v1.DeviceFingerprintR\x11deviceFingerprint\"\xe2\x05\n" +
	"\x17ClaimActivationResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12!\n" +
	"\fmachine_name\x18\x04 \x01(\tR\vmachineName\x12!\n" +
	"\faccess_token\x18\x05 \x01(\tR\vaccessToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12#\n" +
	"\rrefresh_token\x18\a \x01(\tR\frefreshToken\x12S\n" +
	"\x18refresh_token_expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAt\x12&\n" +
	"\x0fmqtt_broker_url\x18\t \x01(\tR\rmqttBrokerUrl\x12*\n" +
	"\x11mqtt_topic_prefix\x18\n" +
	" \x01(\tR\x0fmqttTopicPrefix\x12*\n" +
	"\x11mqtt_topic_layout\x18\r \x01(\tR\x0fmqttTopicLayout\x12.\n" +
	"\x13bootstrap_http_path\x18\v \x01(\tR\x11bootstrapHttpPath\x12-\n" +
	"\x12bootstrap_required\x18\f \x01(\bR\x11bootstrapRequired\x12#\n" +
	"\rmqtt_username\x18\x0e \x01(\tR\fmqttUsername\x12#\n" +
	"\rmqtt_password\x18\x0f \x01(\tR\fmqttPassword\x120\n" +
	"\x14device_attachment_id\x18\x10 \x01(\tR\x12deviceAttachmentId\x12!\n" +
	"\fmachine_code\x18\x11 \x01(\tR\vmachineCode2~\n" +
	"\x18MachineActivationService\x12b\n" +
	"\x0fClaimActivation\x12&.avf.machine.v1.ClaimActivationRequest\x1a'.avf.machine.v1.ClaimActivationResponseB?Z=github.com/avf/avf-vending-api/proto/avf/machine/v1;machinev1b\x06proto3"

var (
	file_avf_machine_v1_machine_activation_proto_rawDescOnce sync.Once
	file_avf_machine_v1_machine_activation_proto_rawDescData []byte
)

func file_avf_machine_v1_machine_activation_proto_rawDescGZIP() []byte {
	file_avf_machine_v1_machine_activation_proto_rawDescOnce.Do(func() {
		file_avf_machine_v1_machine_activation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_machine_v1_machine_activation_proto_rawDesc), len(file_avf_machine_v1_machine_activation_proto_rawDesc)))
	})
	return file_avf_machine_v1_machine_activation_proto_rawDescData
}

var file_avf_machine_v1_machine_activation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_avf_machine_v1_machine_activation_proto_goTypes = []any{
	(*DeviceFingerprint)(nil),       // 0: avf.machine.v1.DeviceFingerprint
	(*ClaimActivationRequest)(nil),  // 1: avf.machine.v1.ClaimActivationRequest
	(*ClaimActivationResponse)(nil), // 2: avf.machine.v1.ClaimActivationResponse
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_avf_machine_v1_machine_activation_proto_depIdxs = []int32{
	0, // 0: avf.machine.v1.ClaimActivationRequest.device_fingerprint:type_name -> avf.machine.v1.DeviceFingerprint
	3, // 1: avf.machine.v1.ClaimActivationResponse.access_token_expires_at:type_name -> google.protobuf.Timestamp
	3, // 2: avf.machine.v1.ClaimActivationResponse.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	1, // 3: avf.machine.v1.MachineActivationService.ClaimActivation:input_type -> avf.machine.v1.ClaimActivationRequest
	2, // 4: avf.machine.v1.MachineActivationService.ClaimActivation:output_type -> avf.machine.v1.ClaimActivationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_avf_machine_v1_machine_activation_proto_init() }
func file_avf_machine_v1_machine_activation_proto_init() {
	if File_avf_machine_v1_machine_activation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_machine_v1_machine_activation_proto_rawDesc), len(file_avf_machine_v1_machine_activation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avf_machine_v1_machine_activation_proto_goTypes,
		DependencyIndexes: file_avf_machine_v1_machine_activation_proto_depIdxs,
		MessageInfos:      file_avf_machine_v1_machine_activation_proto_msgTypes,
	}.Build()
	File_avf_machine_v1_machine_activation_proto = out.File
	file_avf_machine_v1_machine_activation_proto_goTypes = nil
	file_avf_machine_v1_machine_activation_proto_depIdxs = nil
}
