// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: avf/machine/v1/machine_activation.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineActivationService_ClaimActivation_FullMethodName = "/avf.machine.v1.MachineActivationService/ClaimActivation"
)

// MachineActivationServiceClient is the client API for MachineActivationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineActivationService exchanges activation codes for machine credentials (public; no Bearer).
type MachineActivationServiceClient interface {
	ClaimActivation(ctx context.Context, in *ClaimActivationRequest, opts ...grpc.CallOption) (*ClaimActivationResponse, error)
}

type machineActivationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineActivationServiceClient(cc grpc.ClientConnInterface) MachineActivationServiceClient {
	return &machineActivationServiceClient{cc}
}

func (c *machineActivationServiceClient) ClaimActivation(ctx context.Context, in *ClaimActivationRequest, opts ...grpc.CallOption) (*ClaimActivationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimActivationResponse)
	err := c.cc.Invoke(ctx, MachineActivationService_ClaimActivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineActivationServiceServer is the server API for MachineActivationService service.
// All implementations must embed UnimplementedMachineActivationServiceServer
// for forward compatibility.
//
// MachineActivationService exchanges activation codes for machine credentials (public; no Bearer).
type MachineActivationServiceServer interface {
	ClaimActivation(context.Context, *ClaimActivationRequest) (*ClaimActivationResponse, error)
	mustEmbedUnimplementedMachineActivationServiceServer()
}

// UnimplementedMachineActivationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineActivationServiceServer struct{}

func (UnimplementedMachineActivationServiceServer) ClaimActivation(context.Context, *ClaimActivationRequest) (*ClaimActivationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimActivation not implemented")
}
func (UnimplementedMachineActivationServiceServer) mustEmbedUnimplementedMachineActivationServiceServer() {
}
func (UnimplementedMachineActivationServiceServer) testEmbeddedByValue() {}

// UnsafeMachineActivationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineActivationServiceServer will
// result in compilation errors.
type UnsafeMachineActivationServiceServer interface {
	mustEmbedUnimplementedMachineActivationServiceServer()
}

func RegisterMachineActivationServiceServer(s grpc.ServiceRegistrar, srv MachineActivationServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineActivationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineActivationService_ServiceDesc, srv)
}

func _MachineActivationService_ClaimActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineActivationServiceServer).ClaimActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineActivationService_ClaimActivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineActivationServiceServer).ClaimActivation(ctx, req.(*ClaimActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineActivationService_ServiceDesc is the grpc.ServiceDesc for MachineActivationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineActivationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineActivationService",
	HandlerType: (*MachineActivationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimActivation",
			Handler:    _MachineActivationService_ClaimActivation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/machine_activation.proto",
}
