// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: avf/machine/v1/product_master_catalog.proto

package machinev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineProductMasterCatalogService_GetProductMasterCatalogSnapshot_FullMethodName = "/avf.machine.v1.MachineProductMasterCatalogService/GetProductMasterCatalogSnapshot"
	MachineProductMasterCatalogService_GetProductMasterCatalogDelta_FullMethodName    = "/avf.machine.v1.MachineProductMasterCatalogService/GetProductMasterCatalogDelta"
)

// MachineProductMasterCatalogServiceClient is the client API for MachineProductMasterCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MachineProductMasterCatalogService distributes the global active product master catalog
// (all active products available for planogram selection), distinct from MachineCatalogService
// slot-oriented sale catalog projection.
type MachineProductMasterCatalogServiceClient interface {
	// Returns the authoritative full active product master snapshot for this machine.
	GetProductMasterCatalogSnapshot(ctx context.Context, in *GetProductMasterCatalogSnapshotRequest, opts ...grpc.CallOption) (*GetProductMasterCatalogSnapshotResponse, error)
	// Compares basis_catalog_version to the current server product-master version.
	GetProductMasterCatalogDelta(ctx context.Context, in *GetProductMasterCatalogDeltaRequest, opts ...grpc.CallOption) (*GetProductMasterCatalogDeltaResponse, error)
}

type machineProductMasterCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineProductMasterCatalogServiceClient(cc grpc.ClientConnInterface) MachineProductMasterCatalogServiceClient {
	return &machineProductMasterCatalogServiceClient{cc}
}

func (c *machineProductMasterCatalogServiceClient) GetProductMasterCatalogSnapshot(ctx context.Context, in *GetProductMasterCatalogSnapshotRequest, opts ...grpc.CallOption) (*GetProductMasterCatalogSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductMasterCatalogSnapshotResponse)
	err := c.cc.Invoke(ctx, MachineProductMasterCatalogService_GetProductMasterCatalogSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineProductMasterCatalogServiceClient) GetProductMasterCatalogDelta(ctx context.Context, in *GetProductMasterCatalogDeltaRequest, opts ...grpc.CallOption) (*GetProductMasterCatalogDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductMasterCatalogDeltaResponse)
	err := c.cc.Invoke(ctx, MachineProductMasterCatalogService_GetProductMasterCatalogDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineProductMasterCatalogServiceServer is the server API for MachineProductMasterCatalogService service.
// All implementations must embed UnimplementedMachineProductMasterCatalogServiceServer
// for forward compatibility.
//
// MachineProductMasterCatalogService distributes the global active product master catalog
// (all active products available for planogram selection), distinct from MachineCatalogService
// slot-oriented sale catalog projection.
type MachineProductMasterCatalogServiceServer interface {
	// Returns the authoritative full active product master snapshot for this machine.
	GetProductMasterCatalogSnapshot(context.Context, *GetProductMasterCatalogSnapshotRequest) (*GetProductMasterCatalogSnapshotResponse, error)
	// Compares basis_catalog_version to the current server product-master version.
	GetProductMasterCatalogDelta(context.Context, *GetProductMasterCatalogDeltaRequest) (*GetProductMasterCatalogDeltaResponse, error)
	mustEmbedUnimplementedMachineProductMasterCatalogServiceServer()
}

// UnimplementedMachineProductMasterCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineProductMasterCatalogServiceServer struct{}

func (UnimplementedMachineProductMasterCatalogServiceServer) GetProductMasterCatalogSnapshot(context.Context, *GetProductMasterCatalogSnapshotRequest) (*GetProductMasterCatalogSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductMasterCatalogSnapshot not implemented")
}
func (UnimplementedMachineProductMasterCatalogServiceServer) GetProductMasterCatalogDelta(context.Context, *GetProductMasterCatalogDeltaRequest) (*GetProductMasterCatalogDeltaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductMasterCatalogDelta not implemented")
}
func (UnimplementedMachineProductMasterCatalogServiceServer) mustEmbedUnimplementedMachineProductMasterCatalogServiceServer() {
}
func (UnimplementedMachineProductMasterCatalogServiceServer) testEmbeddedByValue() {}

// UnsafeMachineProductMasterCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineProductMasterCatalogServiceServer will
// result in compilation errors.
type UnsafeMachineProductMasterCatalogServiceServer interface {
	mustEmbedUnimplementedMachineProductMasterCatalogServiceServer()
}

func RegisterMachineProductMasterCatalogServiceServer(s grpc.ServiceRegistrar, srv MachineProductMasterCatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineProductMasterCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineProductMasterCatalogService_ServiceDesc, srv)
}

func _MachineProductMasterCatalogService_GetProductMasterCatalogSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductMasterCatalogSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineProductMasterCatalogServiceServer).GetProductMasterCatalogSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineProductMasterCatalogService_GetProductMasterCatalogSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineProductMasterCatalogServiceServer).GetProductMasterCatalogSnapshot(ctx, req.(*GetProductMasterCatalogSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineProductMasterCatalogService_GetProductMasterCatalogDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductMasterCatalogDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineProductMasterCatalogServiceServer).GetProductMasterCatalogDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineProductMasterCatalogService_GetProductMasterCatalogDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineProductMasterCatalogServiceServer).GetProductMasterCatalogDelta(ctx, req.(*GetProductMasterCatalogDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineProductMasterCatalogService_ServiceDesc is the grpc.ServiceDesc for MachineProductMasterCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineProductMasterCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.machine.v1.MachineProductMasterCatalogService",
	HandlerType: (*MachineProductMasterCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductMasterCatalogSnapshot",
			Handler:    _MachineProductMasterCatalogService_GetProductMasterCatalogSnapshot_Handler,
		},
		{
			MethodName: "GetProductMasterCatalogDelta",
			Handler:    _MachineProductMasterCatalogService_GetProductMasterCatalogDelta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/machine/v1/product_master_catalog.proto",
}
