// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: avf/v1/internal_queries.proto

package avfv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalMachineQueryService_GetMachineSummary_FullMethodName            = "/avf.v1.InternalMachineQueryService/GetMachineSummary"
	InternalMachineQueryService_GetMachineState_FullMethodName              = "/avf.v1.InternalMachineQueryService/GetMachineState"
	InternalMachineQueryService_GetMachineCabinetSlotSummary_FullMethodName = "/avf.v1.InternalMachineQueryService/GetMachineCabinetSlotSummary"
)

// InternalMachineQueryServiceClient is the client API for InternalMachineQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalMachineQueryServiceClient interface {
	GetMachineSummary(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineSummaryResponse, error)
	GetMachineState(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineStateResponse, error)
	GetMachineCabinetSlotSummary(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineCabinetSlotSummaryResponse, error)
}

type internalMachineQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalMachineQueryServiceClient(cc grpc.ClientConnInterface) InternalMachineQueryServiceClient {
	return &internalMachineQueryServiceClient{cc}
}

func (c *internalMachineQueryServiceClient) GetMachineSummary(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineSummaryResponse)
	err := c.cc.Invoke(ctx, InternalMachineQueryService_GetMachineSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalMachineQueryServiceClient) GetMachineState(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineStateResponse)
	err := c.cc.Invoke(ctx, InternalMachineQueryService_GetMachineState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalMachineQueryServiceClient) GetMachineCabinetSlotSummary(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineCabinetSlotSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineCabinetSlotSummaryResponse)
	err := c.cc.Invoke(ctx, InternalMachineQueryService_GetMachineCabinetSlotSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalMachineQueryServiceServer is the server API for InternalMachineQueryService service.
// All implementations must embed UnimplementedInternalMachineQueryServiceServer
// for forward compatibility.
type InternalMachineQueryServiceServer interface {
	GetMachineSummary(context.Context, *GetMachineRequest) (*GetMachineSummaryResponse, error)
	GetMachineState(context.Context, *GetMachineRequest) (*GetMachineStateResponse, error)
	GetMachineCabinetSlotSummary(context.Context, *GetMachineRequest) (*GetMachineCabinetSlotSummaryResponse, error)
	mustEmbedUnimplementedInternalMachineQueryServiceServer()
}

// UnimplementedInternalMachineQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalMachineQueryServiceServer struct{}

func (UnimplementedInternalMachineQueryServiceServer) GetMachineSummary(context.Context, *GetMachineRequest) (*GetMachineSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineSummary not implemented")
}
func (UnimplementedInternalMachineQueryServiceServer) GetMachineState(context.Context, *GetMachineRequest) (*GetMachineStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineState not implemented")
}
func (UnimplementedInternalMachineQueryServiceServer) GetMachineCabinetSlotSummary(context.Context, *GetMachineRequest) (*GetMachineCabinetSlotSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineCabinetSlotSummary not implemented")
}
func (UnimplementedInternalMachineQueryServiceServer) mustEmbedUnimplementedInternalMachineQueryServiceServer() {
}
func (UnimplementedInternalMachineQueryServiceServer) testEmbeddedByValue() {}

// UnsafeInternalMachineQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalMachineQueryServiceServer will
// result in compilation errors.
type UnsafeInternalMachineQueryServiceServer interface {
	mustEmbedUnimplementedInternalMachineQueryServiceServer()
}

func RegisterInternalMachineQueryServiceServer(s grpc.ServiceRegistrar, srv InternalMachineQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalMachineQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalMachineQueryService_ServiceDesc, srv)
}

func _InternalMachineQueryService_GetMachineSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMachineQueryServiceServer).GetMachineSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMachineQueryService_GetMachineSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMachineQueryServiceServer).GetMachineSummary(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalMachineQueryService_GetMachineState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMachineQueryServiceServer).GetMachineState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMachineQueryService_GetMachineState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMachineQueryServiceServer).GetMachineState(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalMachineQueryService_GetMachineCabinetSlotSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMachineQueryServiceServer).GetMachineCabinetSlotSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMachineQueryService_GetMachineCabinetSlotSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMachineQueryServiceServer).GetMachineCabinetSlotSummary(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalMachineQueryService_ServiceDesc is the grpc.ServiceDesc for InternalMachineQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalMachineQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.v1.InternalMachineQueryService",
	HandlerType: (*InternalMachineQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMachineSummary",
			Handler:    _InternalMachineQueryService_GetMachineSummary_Handler,
		},
		{
			MethodName: "GetMachineState",
			Handler:    _InternalMachineQueryService_GetMachineState_Handler,
		},
		{
			MethodName: "GetMachineCabinetSlotSummary",
			Handler:    _InternalMachineQueryService_GetMachineCabinetSlotSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/v1/internal_queries.proto",
}

const (
	InternalTelemetryQueryService_GetLatestMachineTelemetry_FullMethodName = "/avf.v1.InternalTelemetryQueryService/GetLatestMachineTelemetry"
	InternalTelemetryQueryService_GetMachineIncidentSummary_FullMethodName = "/avf.v1.InternalTelemetryQueryService/GetMachineIncidentSummary"
)

// InternalTelemetryQueryServiceClient is the client API for InternalTelemetryQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalTelemetryQueryServiceClient interface {
	GetLatestMachineTelemetry(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetLatestMachineTelemetryResponse, error)
	GetMachineIncidentSummary(ctx context.Context, in *GetMachineIncidentSummaryRequest, opts ...grpc.CallOption) (*GetMachineIncidentSummaryResponse, error)
}

type internalTelemetryQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalTelemetryQueryServiceClient(cc grpc.ClientConnInterface) InternalTelemetryQueryServiceClient {
	return &internalTelemetryQueryServiceClient{cc}
}

func (c *internalTelemetryQueryServiceClient) GetLatestMachineTelemetry(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetLatestMachineTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestMachineTelemetryResponse)
	err := c.cc.Invoke(ctx, InternalTelemetryQueryService_GetLatestMachineTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalTelemetryQueryServiceClient) GetMachineIncidentSummary(ctx context.Context, in *GetMachineIncidentSummaryRequest, opts ...grpc.CallOption) (*GetMachineIncidentSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineIncidentSummaryResponse)
	err := c.cc.Invoke(ctx, InternalTelemetryQueryService_GetMachineIncidentSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalTelemetryQueryServiceServer is the server API for InternalTelemetryQueryService service.
// All implementations must embed UnimplementedInternalTelemetryQueryServiceServer
// for forward compatibility.
type InternalTelemetryQueryServiceServer interface {
	GetLatestMachineTelemetry(context.Context, *GetMachineRequest) (*GetLatestMachineTelemetryResponse, error)
	GetMachineIncidentSummary(context.Context, *GetMachineIncidentSummaryRequest) (*GetMachineIncidentSummaryResponse, error)
	mustEmbedUnimplementedInternalTelemetryQueryServiceServer()
}

// UnimplementedInternalTelemetryQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalTelemetryQueryServiceServer struct{}

func (UnimplementedInternalTelemetryQueryServiceServer) GetLatestMachineTelemetry(context.Context, *GetMachineRequest) (*GetLatestMachineTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestMachineTelemetry not implemented")
}
func (UnimplementedInternalTelemetryQueryServiceServer) GetMachineIncidentSummary(context.Context, *GetMachineIncidentSummaryRequest) (*GetMachineIncidentSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMachineIncidentSummary not implemented")
}
func (UnimplementedInternalTelemetryQueryServiceServer) mustEmbedUnimplementedInternalTelemetryQueryServiceServer() {
}
func (UnimplementedInternalTelemetryQueryServiceServer) testEmbeddedByValue() {}

// UnsafeInternalTelemetryQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalTelemetryQueryServiceServer will
// result in compilation errors.
type UnsafeInternalTelemetryQueryServiceServer interface {
	mustEmbedUnimplementedInternalTelemetryQueryServiceServer()
}

func RegisterInternalTelemetryQueryServiceServer(s grpc.ServiceRegistrar, srv InternalTelemetryQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalTelemetryQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalTelemetryQueryService_ServiceDesc, srv)
}

func _InternalTelemetryQueryService_GetLatestMachineTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalTelemetryQueryServiceServer).GetLatestMachineTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalTelemetryQueryService_GetLatestMachineTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalTelemetryQueryServiceServer).GetLatestMachineTelemetry(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalTelemetryQueryService_GetMachineIncidentSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineIncidentSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalTelemetryQueryServiceServer).GetMachineIncidentSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalTelemetryQueryService_GetMachineIncidentSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalTelemetryQueryServiceServer).GetMachineIncidentSummary(ctx, req.(*GetMachineIncidentSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalTelemetryQueryService_ServiceDesc is the grpc.ServiceDesc for InternalTelemetryQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalTelemetryQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.v1.InternalTelemetryQueryService",
	HandlerType: (*InternalTelemetryQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestMachineTelemetry",
			Handler:    _InternalTelemetryQueryService_GetLatestMachineTelemetry_Handler,
		},
		{
			MethodName: "GetMachineIncidentSummary",
			Handler:    _InternalTelemetryQueryService_GetMachineIncidentSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/v1/internal_queries.proto",
}

const (
	InternalCommerceQueryService_GetOrderPaymentVendState_FullMethodName = "/avf.v1.InternalCommerceQueryService/GetOrderPaymentVendState"
)

// InternalCommerceQueryServiceClient is the client API for InternalCommerceQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalCommerceQueryServiceClient interface {
	GetOrderPaymentVendState(ctx context.Context, in *GetOrderPaymentVendStateRequest, opts ...grpc.CallOption) (*GetOrderPaymentVendStateResponse, error)
}

type internalCommerceQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalCommerceQueryServiceClient(cc grpc.ClientConnInterface) InternalCommerceQueryServiceClient {
	return &internalCommerceQueryServiceClient{cc}
}

func (c *internalCommerceQueryServiceClient) GetOrderPaymentVendState(ctx context.Context, in *GetOrderPaymentVendStateRequest, opts ...grpc.CallOption) (*GetOrderPaymentVendStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderPaymentVendStateResponse)
	err := c.cc.Invoke(ctx, InternalCommerceQueryService_GetOrderPaymentVendState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalCommerceQueryServiceServer is the server API for InternalCommerceQueryService service.
// All implementations must embed UnimplementedInternalCommerceQueryServiceServer
// for forward compatibility.
type InternalCommerceQueryServiceServer interface {
	GetOrderPaymentVendState(context.Context, *GetOrderPaymentVendStateRequest) (*GetOrderPaymentVendStateResponse, error)
	mustEmbedUnimplementedInternalCommerceQueryServiceServer()
}

// UnimplementedInternalCommerceQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalCommerceQueryServiceServer struct{}

func (UnimplementedInternalCommerceQueryServiceServer) GetOrderPaymentVendState(context.Context, *GetOrderPaymentVendStateRequest) (*GetOrderPaymentVendStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderPaymentVendState not implemented")
}
func (UnimplementedInternalCommerceQueryServiceServer) mustEmbedUnimplementedInternalCommerceQueryServiceServer() {
}
func (UnimplementedInternalCommerceQueryServiceServer) testEmbeddedByValue() {}

// UnsafeInternalCommerceQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalCommerceQueryServiceServer will
// result in compilation errors.
type UnsafeInternalCommerceQueryServiceServer interface {
	mustEmbedUnimplementedInternalCommerceQueryServiceServer()
}

func RegisterInternalCommerceQueryServiceServer(s grpc.ServiceRegistrar, srv InternalCommerceQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalCommerceQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalCommerceQueryService_ServiceDesc, srv)
}

func _InternalCommerceQueryService_GetOrderPaymentVendState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderPaymentVendStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalCommerceQueryServiceServer).GetOrderPaymentVendState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalCommerceQueryService_GetOrderPaymentVendState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalCommerceQueryServiceServer).GetOrderPaymentVendState(ctx, req.(*GetOrderPaymentVendStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalCommerceQueryService_ServiceDesc is the grpc.ServiceDesc for InternalCommerceQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalCommerceQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avf.v1.InternalCommerceQueryService",
	HandlerType: (*InternalCommerceQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderPaymentVendState",
			Handler:    _InternalCommerceQueryService_GetOrderPaymentVendState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avf/v1/internal_queries.proto",
}
